### ISSUE TITLE
Compatibility issue between @nuxtjs/i18n and Bridge's vite option

### ISSUE THREAD

**Issue by wJoenn** [nuxt/bridge#1029]
### Environment

```
- Operating System: Linux
- Node Version:     v18.19.0
- Nuxt Version:     2.17.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          webpack
- User Config:      bridge, ssr, build, css, components, env, head, http2, loading, loadingIndicator, plugins, buildModules, modules, i18n, pwa, router, sentry
- Runtime Modules:  @nuxtjs/pwa@3.3.4, @nuxtjs/sentry@5.1.0, @nuxtjs/i18n@8.0.0-rc.11, nuxt-vuex-router-sync@0.0.3
- Build Modules:    @nuxt/typescript-build@2.1.0, @nuxtjs/composition-api/module@0.33.1
```

### Reproduction

The issue is bound to packages not compatible with each other so it shouldn't need a reproduction.

### Describe the bug

I'm trying to migrate a Nuxt 2 project to Nuxt Bridge before upgrading to Nuxt 3.
I've installed Nuxt Bridge without issue and have updated my config file to
```ts
export default defineNuxtConfig({
  bridge: false
})
```

The problem is that because I have some JSX components, as soon as I enable any feature of `bridge`, in my case that'd be `bridge: { typescript: true, nitro: false }`, I get errors like this one
![image](https://github.com/nuxt/bridge/assets/75388869/0d52b360-66ca-43fb-9499-4803f36405e3)

It is an issue known since 2021 that hasn't been fixed yet and Daniel's recommendation is to migrate to Vite
https://github.com/nuxt/bridge/issues/17#issuecomment-1179561642
![image](https://github.com/nuxt/bridge/assets/75388869/a81d0f36-f822-4aea-9cda-b203c436ecee)

The problem is that my project is also still using `nuxt-i18n` with plenty of custom `i18n` blocks in my SPCs like this example
```html
<template>
  <div>{{ $t("hello") }}
</template>

<i18n lang="yml">
  en:
    hello: Hello there
    
  fr:
    hello: Bien le bonjour
</i18n>
```
This is possible because `nuxt-i18n` installs `vue-i18n-loader` which enables Webpack to parse these custom blocks.
Of course this doesn't work with Vite so the solution is to migrate from `nuxt-i18n` to `@nuxtjs/i18n` version 8+ because it introduces `unplugin-vue-i18n` which enables custom blocks for Vite too.

Here's the problem
`@nuxtjs/i18n@8` is not compatible with Nuxt `2.7.x` so I can't upgrade past `@nuxtjs/i18n@7`. And if I can't upgrade it means I can't migrate to Vite, which means I can't enable Bridge because of my JSX components which means I can't upgrade to Nuxt 3 later on without having to update everything at once instead of taking the gradual approach that Bridge enables.

What can I do ?

**Comment by wJoenn** [comment]
In the end I ended up converting all of my JSX files to .vue files which allowed me to enable most features of Bridge.
I'm still interested in a way to make `@nuxtjs/i18n` and `bridge: { vite: true }` though but I suppose that's bound to the i18n module, not bridge itself.
Feel free to close if you deem this not to be an issue with bridge

**Comment by wattanx** [comment]
The problem with jsx not working with webpack is the same as the following issue.(It will be fixed shortly.)
https://github.com/nuxt/bridge/issues/17

I think vite support for i18n module should be tracked in i18n.
