### ISSUE TITLE
`reactive` does not work as expected

### ISSUE THREAD

**Issue by rklos** [nuxt/bridge#1053]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     2.17.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          webpack
- User Config:      bridge, serverHandlers, devServerHandlers, devServer, typescript, nitro, buildModules
- Runtime Modules:  -
- Build Modules:    (), @nuxt/bridge@3.0.0-rc.4-28407367.8f1f89e
------------------------------

### Reproduction

https://stackblitz.com/edit/github-facyda-nt8mqs?file=pages%2Findex.vue

### Describe the bug

`reactive` provided by `@nuxt/bridge` does not work as expected (compared to the `@nuxtjs/composition-api`, Nuxt 3 or Vue 3).

If you define an empty reactive object with `reactive`, then you cannot add new **reactive** properties to it. They will be assigned as a "regular" values instead of setters/getters.

Newly added properties won't trigger their own watchers:
```js
import { reactive, watch } from '#imports';

const state = reactive({});

// It doesn't matter where the initialisation is
// because if it's outside the initial value of the `reactive`, it won't trigger its watchers.
state.foo = 0;

watch(
  // Will never be triggered
  () => state.foo,
  () => {
    alert('Change!');
  }
);

const incr = () => {
  state.foo += 1;
};
```
The only way to deal with this problem is to include every possible property in the initial object literal (even with a nullish value):
```js
const state = reactive({ foo: null });
```

This behaviour is inconsistent with `@nuxtjs/composition-api`, Nuxt 3 and Vue 3, which allow new properties to be added at any time without losing reactivity.

**Comment by wattanx** [comment]
This is the expected behavior. (Behavior is different from Vue 3)
https://github.com/vuejs/vue/issues/13139#issuecomment-1868536357
