### ISSUE TITLE
Unexpected token '!'

### ISSUE THREAD

**Issue by Eddie344** [nuxt/bridge#1066]
### Environment

- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     2.17.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          webpack
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Usual nuxt 2 project with @nuxtjs/composition-api v0.31.0

I'm going through nuxt bridge migration guide.
I try to set anything inside `bridge` field inside `nuxt.config`, for example:
```
bridge {
  typescript: true
}
```
When `bridge: false`, everything is ok

### Describe the bug

<img width="1440" alt="image" src="https://github.com/nuxt/bridge/assets/53879350/5e1a4b27-e7bd-415a-8485-842bc2a9faef">
<img width="1007" alt="image" src="https://github.com/nuxt/bridge/assets/53879350/0f9aece7-20f9-4c81-a6c5-1a91a6f731b5">

**Comment by Eddie344** [comment]
Also I tried other node js versions: 16, 18

**Comment by wattanx** [comment]
Maybe it is the same as https://github.com/nuxt/bridge/issues/1063.

**Comment by Eddie344** [comment]
I found the reason: the problem was in my server middleware for recaptcha 
```
import { readBody } from 'h3';
import { ofetch } from 'ofetch';

// const IS_DEV = process.env.NODE_ENV === 'development';
const SECRET_KEY = process.env.RECAPTCHA_PRIVATE_KEY;

export default async (req, res) => {
  res.setHeader('Content-Type', 'application/json');

  // eslint-disable-next-line no-unreachable
  try {
    const { token } = await readBody({ node: { req }, method: 'POST' });

    if (!token) {
      res.end(
        JSON.stringify({
          success: false,
          message: 'Invalid token',
        }),
      );
      return;
    }

    const response = await ofetch(
      `https://www.google.com/recaptcha/api/siteverify?secret=${SECRET_KEY}&response=${token}`,
      {
        method: 'POST',
      },
    );

    res.end(
      JSON.stringify({
        success: response.success,
        response,
      }),
    );
  } catch (error) {
    console.error(error);
    res.end(
      JSON.stringify({
        success: false,
        message: 'Internal error',
        error,
      }),
    );
  }
};

```
I have not figured out exactly what the problem is, just turn off this file

**Comment by kyumoon** [comment]
+ 1
