### ISSUE TITLE
Bridge & Vite: Do not load all chunks at the same time

### ISSUE THREAD

**Issue by hamedniroumand** [nuxt/bridge#1126]
### Environment

- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     2.17.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          vite
- User Config:      target, ssr, bridge, features, build, spaloadingtemplate, components, head, serverHandlers, devServerHandlers, devServer, typescript, nitro, buildModules
- Runtime Modules:  -
- Build Modules:    (), @nuxt/bridge@3.0.1

### Reproduction

https://github.com/hamedniroumand/nuxt-bridge-sample

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/55133282/b3dfbf8c-5a66-42fc-9949-121c5c50b223)

I have a nuxt bridge project consisting of three pages that are linked to each other, each utilizing the no-prefetch prop in all links. However, upon generating and starting the project, all chunks related to my pages and components are loaded in a single location, rather than loading only the chunks relevant to the currently opened page.
Consequently, this leads to unused component styles from other pages being loaded on the main page, resulting in unnecessary bloat and potential styling conflicts.

### Additional context

This issue is not present in Nuxt 3, suggesting a discrepancy in behavior between the versions.

If you set `isAsync: true` inside the `components` configs, this issue be solved only in dev mode.

**Comment by marcos-vinicius-dev** [comment]
I have the same error:

I tested with nitro using dev script: 'nuxi dev' and without nitro using dev script: 'nuxt2', but both models have the same error.
![Captura de tela 2024-03-08 122706](https://github.com/nuxt/bridge/assets/37404158/decc0c39-b6b9-49c7-8b2c-1dfaf919b528)

**Comment by AndreyYolkin** [comment]
This is happened because bridge utilises Legacy Plugin and generates manifest with SystemJS. I gave more details here: https://discord.com/channels/473401852243869706/992155295927251074/1171782196974075984 

Maybe it's good time to raise the question again

**Comment by wattanx** [comment]
We have added an option to not use `@vitejs/plugin-legacy`.
It will be released with Nuxt Bridge 3.2.0!
(If you want to use it quickly, it is available after `bridge-edge@3.1.0-28522654.a6eae9b`.)
