### ISSUE TITLE
[Middleware] To and From are always one route late when using automatic middleware mapping (01,02...etc)

### ISSUE THREAD

**Issue by rrochaTG** [nuxt/bridge#1134]
### Environment

- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     2.17.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          webpack
- User Config:      ssr, head, css, plugins, buildModules, modules, axios, app, build, serverHandlers, devServerHandlers, devServer, typescript, nitro, bridge
- Runtime Modules:  @nuxtjs/axios@5.13.6
- Build Modules:    (), @nuxtjs/eslint-module@3.1.0, @nuxt/bridge@3.0.1-28463876.5503879

### Reproduction

2.0 With Bridge: https://github.com/rrochaTG/reproduction-error-middleware-bridge
3:0: https://github.com/rrochaTG/reproduction-correct-vue-3

### Describe the bug

Go to localhost:3000/clients and then click the link. 
You will see that **from** is undefined (there is already an issue for that: https://github.com/nuxt/bridge/issues/954), but after clicking the link both **from** and **to** have the same route. Changing routes again and is always a route late.

This issue has caused problems in some of our systems during the upgrade process, so I'm keen to determine if it's truly a bug or a misconfiguration on our end. It seems to be a bug, as in Vue 3, it works as expected: https://github.com/rrochaTG/reproduction-correct-vue-3

**Comment by wattanx** [comment]
It would be easier to investigate if you could describe what kind of logs you expect to get. 🙏

**Comment by rrochaTG** [comment]
Good point, sorry about that. 
I would expect the same in the Vue 3 version.

If you are in /clients and go to /categories, I would expect the names of the routes to be:
to: "categories"
from: "clients"

However, what I get is this:
![image](https://github.com/nuxt/bridge/assets/160048674/8d208511-b2f7-4e50-8322-1300c353813c)

This is different from what I get in the Nuxt 3 version (The 3.0 example I posted has different URLs, but it shows it working as expected):

![image](https://github.com/nuxt/bridge/assets/160048674/8fc282a4-c965-4ae6-b4f7-a949d63db320)

Now if I keep going in the 2.0 version to '/products' what I get is this:
![image](https://github.com/nuxt/bridge/assets/160048674/e6fe8d73-bcd1-48ab-a386-f4bf0892abe1)

Which it is the correct answer one route early (when we were in /categories), but dons't make sense here, since whe are going to '/products'. What I would expect in this case is:
to: 'products'
from: 'categories'

**Comment by Ttou** [comment]
the global middleware can't get the real value，different from nuxt3

> auth.global.ts

```ts
export default defineNuxtRouteMiddleware((to, from) => {
  console.log('to', to) // when navigateTo other page from index.vue, to.path always be /
  console.log('from', from)

  const { token } = useMainStore()

  if (to.path !== '/') {
    if (!token && to.path === '/requiredAuth') {
      return navigateTo('/login')
    }

    if (token && to.path === '/login') {
      return navigateTo('/requiredAuth')
    }
  }
})
```

change `auth.global.ts` to `auth.ts`，`to.path` get the real value
