### ISSUE TITLE
useLazyFetch does not work with reactive values

### ISSUE THREAD

**Issue by htmlfactorycz** [nuxt/bridge#1135]
### Environment

- Operating System: Darwin
- Node Version:     v18.19.1
- Nuxt Version:     2.17.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.1
- Package Manager:  npm@10.4.0
- Builder:          webpack
- User Config:      bridge, target, ssr, nitro, head, app, css, plugins, components, imports, buildModules, publicRuntimeConfig, env, router, modules, loading, dayjs, build, serverHandlers, devServerHandlers, devServer, typescript
- Runtime Modules:  nuxt-validate@1.0.1, @nuxtjs/i18n@7.3.1, nuxt-svg-loader@1.2.0, nuxt-uid-module@0.2.0, nuxt-vuex-localstorage@1.3.0, @nuxtjs/gtm@2.4.0, nuxt-polyfill@1.0.3, @nuxtjs/axios@5.13.6
- Build Modules:    (), @nuxtjs/dayjs@1.4.1, @nuxt/bridge@3.1.0

### Reproduction

[Nuxt3 working example](https://codesandbox.io/p/devbox/nuxt3-usefetch-reactive-values-m24g7s?file=%2Fpages%2Findex.vue%3A11%2C12&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clti5sawi00073b6io7p6nz9r%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clti5sawh00023b6iv7vkjg7o%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clti5sawi00043b6ifz063jyj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clti5sawi00063b6it2r3ov9i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clti5sawh00023b6iv7vkjg7o%2522%253A%257B%2522id%2522%253A%2522clti5sawh00023b6iv7vkjg7o%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clti6uksc00023b6icpomrwq4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A12%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A12%257D%255D%252C%2522filepath%2522%253A%2522%252Fpages%252Findex.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clti6uksc00023b6icpomrwq4%2522%257D%252C%2522clti5sawi00063b6it2r3ov9i%2522%253A%257B%2522id%2522%253A%2522clti5sawi00063b6it2r3ov9i%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clti6960o00gd3b6ipooqfle6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clti6960o00gd3b6ipooqfle6%2522%257D%252C%2522clti5sawi00043b6ifz063jyj%2522%253A%257B%2522id%2522%253A%2522clti5sawi00043b6ifz063jyj%2522%252C%2522activeTabId%2522%253A%2522clti67qh900dl3b6itxy05r2l%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clti67qh900dl3b6itxy05r2l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clti67qkl07i8dig71nuk43v1%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 

[Nuxt + bridge not working](https://codesandbox.io/p/devbox/nuxt-bridge-usefetch-reactive-values-not-working-s42zc2?file=%2Fpages%2Findex.vue%3A26%2C30&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clti5shws00073b6i2lhb8nck%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clti5shwr00023b6i21tyvy5s%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clti5shwr00043b6i5vato0xn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clti5shws00063b6iagrk032t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clti5shwr00023b6i21tyvy5s%2522%253A%257B%2522id%2522%253A%2522clti5shwr00023b6i21tyvy5s%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clti5w8xe005i3b6iz77x1uts%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A26%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A26%252C%2522endColumn%2522%253A30%257D%255D%252C%2522filepath%2522%253A%2522%252Fpages%252Findex.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clti5w8xe005i3b6iz77x1uts%2522%257D%252C%2522clti5shws00063b6iagrk032t%2522%253A%257B%2522id%2522%253A%2522clti5shws00063b6iagrk032t%2522%252C%2522activeTabId%2522%253A%2522clti68pcc00s53b6ii93c8zwl%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clti5shws00053b6ik2l35n7q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clti68pcc00s53b6ii93c8zwl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clti5shwr00043b6i5vato0xn%2522%253A%257B%2522id%2522%253A%2522clti5shwr00043b6i5vato0xn%2522%252C%2522activeTabId%2522%253A%2522clti65wgc00ow3b6i840tdibj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clti65wgc00ow3b6i840tdibj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clti65wia000mdid91pkh96tv%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Describe the bug

I want to use reactive values in useLazyFetch function, but nuxt bridge seems to not support this.

`const username = ref("");
const password = ref("");

const queryParams = computed(() => ({
  username: username.value,
  password: password.value,
}));

const { data, pending, error, refresh } = useLazyFetch("/login", {
  query: queryParams
});`

![Snímek obrazovky 2024-03-08 v 6 24 11](https://github.com/nuxt/bridge/assets/29103850/69724b37-420d-477e-bef5-38dcbbbf7bd4)

I tried to use not computed, but refs. Seems to work => values are updated after every send request, but it sends not the value itself but object {value: 'value of input'}

`const username = ref("");
const password = ref("");

const { data, pending, error, refresh } = useLazyFetch("/login", {
  query: {
    username: username,
    password: password,
  }
});`

![Snímek obrazovky 2024-03-08 v 6 23 56](https://github.com/nuxt/bridge/assets/29103850/1bd864b1-1cf3-4062-b99e-d5b686c76923)

In nuxt3 version all working fine, so there must a bug in bridge version of function useLazyFetch. 

### Logs

```shell
logs are in reproduction links
```

**Comment by htmlfactorycz** [comment]
hey @wattanx thank you for your quick response to this issue. When do you think your pull request will be resolved? It seems good and I would love to start using this :)

**Comment by htmlfactorycz** [comment]
@wattanx, I found a BUG, you fixed it, all are happy, but not untill this ticket is merged and closed. I dont  understand why it already isnt..
How can developers use funkction useLazyFetch if it is a buggy and not working? Isnt it an important bug? Fetching is the most often functionality fot nuxt apps.. Guys please check this out and make merge happen please :)

**Comment by wattanx** [comment]
If you want a quick fix, use `patch-package`. 
https://www.npmjs.com/package/patch-package

Please read the following statement as to why we do not merge immediately.
https://github.com/pi0/tired-maintainer?tab=readme-ov-file#this-pr-looks-good-to-me-or-tell-me-what-to-do

**Comment by htmlfactorycz** [comment]
Thank you! I solved my issue by `pnpm patch` and all working nice.
