### ISSUE TITLE
Vue's exclusion from dependency optimization breaks element-ui in development mode

### ISSUE THREAD

**Issue by mishjj** [nuxt/bridge#1273]
### Environment

.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-6awqdy?file=vite.config.js (vue excluded) 
Element-ui is broken in development mode, but does work in production (build)

https://stackblitz.com/edit/vitejs-vite-nzzrdt?file=vite.config.js (vue not excluded)
Element-ui works in both production and development mode.

Nuxt (example just in case)
https://stackblitz.com/edit/github-puhhfa?file=nuxt.config.ts

### Describe the bug

Seems to affect Vite v4+. 

Element-ui is transpiled from ESM/mixed to CJS and has a interopRequireDefault helper that considers a module a CJS if it lacks _esModule property. And Vite seems to namespace import Vue in dev without setting an _esModule property so the interop helper returns a nested module `[module].default.default -> vue`.

Does not affect production build because the import is converted by the getAugmentedNamespace rollup helper.

Removing Vue from dependecy optimization exclusion will solve the issue in development (https://github.com/nuxt/bridge/blob/main/packages/bridge/src/vite/vite.ts#L68)

**Comment by wattanx** [comment]
It can be solved in the following ways:

// nuxt.config.js/ts
```ts
export default defineNuxtConfig({
hooks: {
  'vite:extend': (ctx) => {
      ctx.config.optimizeDeps = {
        exclude: ['ufo', 'date-fns', 'nanoid'],
      };
    },
  },
})
```

https://stackblitz.com/edit/github-puhhfa-18pq6j?file=nuxt.config.ts

**Comment by mishjj** [comment]
That solved the issue a lot more elegantly than using patching. Thanks for the help!
