### ISSUE TITLE
postcss not working after using `vite: true`

### ISSUE THREAD

**Issue by medz** [nuxt/bridge#1282]
### Environment

- Operating System: Darwin
- Node Version:     v22.6.0
- Nuxt Version:     2.18.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.2
- Builder:          vite
- User Config:      bridge, vite, nitro, alias, routeRules, css, modules, head, plugins, components, buildModules, moment, axios, build, vue, router, serverHandlers, devServerHandlers, devServer, typescript
- Runtime Modules:  @nuxtjs/axios@5.13.6, @nuxtjs/tailwindcss@6.12.1
- Build Modules:    (), @nuxtjs/moment@1.6.1, @nuxt/bridge@3.3.1

### Reproduction

https://stackblitz.com/~/github.com/medz/github-tvvdvm

### Describe the bug

After using Vite, postcss no longer works, I just use `@nuxtjs/tailwindcss` package for simple demonstration.

**Comment by medz** [comment]
Fixed: 

```dart
import tailwind from "tailwindcss";

export default defineNuxtConfig({
    bridge: { vite: true },
    vite: {
        css: {
             postcss: [tailwind()],
        }
    }
});
```

**Comment by medz** [comment]
This is not a very reasonable behavior. In Vite documents and other Nuxt documents, postcss is automatically executed, but in vite/tailwindcss or @nuxtjs/tailwindcss, it is not required to be configured.

But the actual situation is that any postcss plugin must be manually configured, otherwise it will not take effect.

**Comment by cain** [comment]
@medz you bloody legend thank you sir! (spent hours trying to fix this)

**Comment by medz** [comment]
> [@medz](https://github.com/medz) you bloody legend thank you sir! (spent hours trying to fix this)

Upgrading an old project from Nuxt 2 to Nuxt 3 is really challenging.

I have been stuck in the partial bridge migration stage since last year, and the bridge has many obstacles to upgrading. There are also some old packages used in the code.
