### ISSUE TITLE
Error on Startup after Migration to Nuxt Bridge on Fresh Project

### ISSUE THREAD

**Issue by timgoeller** [nuxt/bridge#138]

**Comment by Cally99** [comment]
Anyone fix this issue? Followed the documentation on the nuxt bridge page and came across this error. The core team seriously roll out buggy features.

**Comment by danielroe** [comment]
@Cally99 If you are encountering an issue, please create a new issue with a reproduction and we'll look into it. 😉

**Comment by Remo** [comment]
@danielroe there is another issue with the same problem and a repo where you can reproduce the problem: https://github.com/nuxt/bridge/issues/314

**Comment by klausXR** [comment]
Any movement on this?

**Comment by klausXR** [comment]
If you are still getting this error while debugging your migration process, I encountered severe issues in development and according to the migration guide that says that you can disable Bridge if you set `bridge: false` in your nuxt.config.js file.

If you do this, you have to start nuxt with the legacy script, because `nuxi dev` doesn't work. 

Use `nuxt dev`

**Comment by kovan** [comment]
Any updates on this?

` ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'callHook')                                                                                                                   05:45:23

  at load (node_modules/nuxi/dist/chunks/dev.mjs:6780:33)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6828:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)`

I really have no idea of even where to start looking.

**Comment by gokatz** [comment]
Facing similar issue when starting dev server. `nuxi build` is working though.

Terminal Output:
<img width="454" alt="Screenshot 2022-10-21 at 7 48 41 PM" src="https://user-images.githubusercontent.com/15158776/197218008-6fe604fc-b5a6-4708-910b-bd50c871a06c.png">

Browser:
<img width="1188" alt="Screenshot 2022-10-21 at 7 48 54 PM" src="https://user-images.githubusercontent.com/15158776/197218064-d4f4b82a-fe06-47cf-9f9b-199524c60cbd.png">

**Comment by oemer-sellwerk** [comment]
> Facing similar issue when starting dev server. `nuxi build` is working though.
> 
> Terminal Output: <img alt="Screenshot 2022-10-21 at 7 48 41 PM" width="454" src="https://user-images.githubusercontent.com/15158776/197218008-6fe604fc-b5a6-4708-910b-bd50c871a06c.png">
> 
> Browser: <img alt="Screenshot 2022-10-21 at 7 48 54 PM" width="1188" src="https://user-images.githubusercontent.com/15158776/197218064-d4f4b82a-fe06-47cf-9f9b-199524c60cbd.png">

I have the exact same issue: 
<img width="1777" alt="image" src="https://user-images.githubusercontent.com/84452458/210378747-50271cce-500b-4844-9f61-ba78fd56baec.png">

<img width="358" alt="image" src="https://user-images.githubusercontent.com/84452458/210378789-556e171c-ddc2-4b6a-adab-33ae7a2348c9.png">
