### ISSUE TITLE
Nuxt hook "listen" is not firing

### ISSUE THREAD

**Issue by richardeschloss** [nuxt/bridge#149]

**Comment by dabrowiecki** [comment]
@richardeschloss I have a similar problem, I want to provided prometheus metrics from the application on a separate port. What is the event that you are listening to in order to open socket.io connection? `Listen` hook sounds like a good moment to open the second connection.

**Comment by richardeschloss** [comment]
> @richardeschloss I have a similar problem, I want to provided prometheus metrics from the application on a separate port. What is the event that you are listening to in order to open socket.io connection? `Listen` hook sounds like a good moment to open the second connection.

I'm listening for `listen` (all lowercase):
https://github.com/richardeschloss/nuxt-socket-io/blob/5c04b4215584d2af1a4bdf1b02e5c987a68e703a/lib/module.js#L206
