### ISSUE TITLE
Several issues about dependencies (node:*) not found

### ISSUE THREAD

**Issue by azpery** [nuxt/bridge#158]
### Environment

Nuxt CLI v3.0.0-27307420.6a25d3e                                             15:39:57
RootDir: /Users/robindelaporte/Documents/Workspace/tenk                      15:39:57
Nuxt project info:                                                           15:39:57

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.10.0`
- Nuxt Version:     `2.16.0-27306734.ab1c6cb4`
- Package Manager:  `npm@7.24.0`
- Bundler:          `Webpack`
- User Config:      `buildModules`, `$bect`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27307420.6a25d3e`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new             15:39:57

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

I followed the steps to migrate from nuxt 2 to nuxt 3 until this step : https://v3.nuxtjs.org/getting-started/bridge/#update-nuxtconfig 

Then I have dependencies errors with node:http node:https, etc..

### Describe the bug

While building the project I have dependencies errors coming from @nuxt/bridge 

please see the log file attached
[nuxt bug.log](https://github.com/nuxt/framework/files/7642781/nuxt.bug.log)

**Comment by edwardcastle** [comment]
I ran into this issue I downgrade to node-fetch@2.x.x and  `npm install --save buffer http https net stream url util zlib`
without node: , that solved the issue for me

**Comment by danielroe** [comment]
Downgrading node fetch should work. But you should not try to manually install node built ins. They are provided by node itself and do not need to be installed.
