### ISSUE TITLE
Nuxt Bridge app.baseURL doesn't work with i18n module

### ISSUE THREAD

**Issue by thomas4Bitcraft** [nuxt/bridge#16]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `latest`
- Package Manager:  `npm@6.14.15`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

_nuxt.config.js_

```
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
router: {
    base: '/d/'
  },
})
```

### Describe the bug

The base path in nuxt bridge seems to be broken. If I set it to the above `/d/` every preload link in the frontend is set to `/d/d/` and all files are also reachable only with this path.

<img width="444" alt="image" src="https://user-images.githubusercontent.com/44415527/154579681-2e30740b-87a7-405e-b731-728ffe2eb3b9.png">
<img width="351" alt="image" src="https://user-images.githubusercontent.com/44415527/154579710-74c27e43-2912-4e9f-b00d-0bb74a2b1c08.png">

It seems the only url which is not affected by this is the one to the header js file in production
<img width="426" alt="image" src="https://user-images.githubusercontent.com/44415527/154580901-74b4a660-e48c-4ca2-b2e2-710658e1d6b5.png">

What makes the thing worse - because the file lies under `/d/d/` and the whole site is broken

**Comment by sweetpalma** [comment]
I have the exact same issue with a `nuxt/bridge` even without using any third-party modules. When I define `router.base` with some value - let's assume `/test/` for example - it gets doubled in the script routes, embedded to the header. Any solution for this yet?

<img width="800" alt="Снимок экрана 2022-08-12 в 17 34 44" src="https://user-images.githubusercontent.com/17027163/184377217-4261ed80-c692-4061-b2bc-55dd1122b65f.png">

**Comment by sweetpalma** [comment]
I was able to hard code __nuxt folder path using `buildAssetsDir` (it's not even documented!) - but I guess that's a pretty weak solution. Hope this issue will get addressed soon.

<img width="751" alt="Снимок экрана 2022-08-15 в 23 53 50" src="https://user-images.githubusercontent.com/17027163/184716512-2ffb7803-3f81-4b97-b322-98a93ab25982.png">

**Comment by emretepedev** [comment]
Same issue here.

**Comment by saraha33** [comment]
yes - also had the problem that my fonts in `/assets` were not found - because the prefix was missing - the key was to specify the `buildAssetsDir` string as specified by @sweetpalma even though it should be the default anyway...(i also added `baseURL` and `router.base` but `buildAssetsDir` really made all the difference)

```
app: {
  buildAssetsDir: '/_nuxt/'
}
```

**Comment by ldavisCEI** [comment]
I also had the same issue. I followed the work around by @sweetpalma and @saraha33. That fixed the issue. Thanks!
At least `buildAssetsDir` is now in the [docs](https://nuxt.com/docs/api/configuration/nuxt-config#buildassetsdir).
