### ISSUE TITLE
Internal server error - Object(...) is not a function on page load

### ISSUE THREAD

**Issue by kadlinobit** [nuxt/bridge#162]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.17.3`
- Nuxt Version:     `2.16.0-27296655.ab1c6cb4`
- Package Manager:  `npm@6.14.13`
- Bundler:          `Webpack`
- User Config:      `bridge`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `i18n`, `axios`, `auth`, `strapi`, `build`, `publicRuntimeConfig`, `privateRuntimeConfig`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/auth@4.9.1`, `@nuxtjs/strapi@0.3.4`, `@nuxtjs/i18n@7.2.0`
- Build Modules:    `@nuxtjs/eslint-module@3.0.2`, `@nuxt/bridge@3.0.0-27296423.f3082ca`

### Reproduction

Github repo (nuxt-3-bridge branch)
https://github.com/kadlinobit/djspot-fe/tree/nuxt-3-bridge

### Describe the bug

When nuxt server is starting, there is a warning message:
```
 in ./.nuxt/runtime.app.plugin.75f1febc.mjs                                                                                                                                    
"export 'createHooks' was not found in 'hookable'       
```
Nuxt starts, but when I try to load homepage, I get this error:
```
Object(...) is not a function
  at module.exports../.nuxt/runtime.app.plugin.75f1febc.mjs.__webpack_exports__.default (./.nuxt/dist/server/server.js:5378:79)  
  at createApp (./.nuxt/dist/server/server.js:2868:105)  
  at async module.exports../.nuxt/server.js.__webpack_exports__.default (./.nuxt/dist/server/server.js:5547:7)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:254:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:186:20)  
  at async handle (file://./node_modules/h3/dist/index.mjs:598:19)
```

**Comment by M1seRy** [comment]
yarn add --dev hookable  doesn't work here。same problem with :
```
    "@nuxt/bridge": "npm:@nuxt/bridge-edge@^3.0.0-27454252.7bf338d",
    "@nuxt/kit": "npm:@nuxt/kit-edge@^3.0.0-27454252.7bf338d",
```

**Comment by Cheaterman** [comment]
If `yarn add --dev hookable` doesn't fix it for you, it could be a good idea to check nuxt/nuxt#5661 (possibly related).
