### ISSUE TITLE
JSX Render Functions in Nuxt 2 with Nuxt Bridge are failing

### ISSUE THREAD

**Issue by loweoj** [nuxt/bridge#17]
###  Environment

Nuxt CLI v3.0.0-27234503.d5127e9
RootDir: /sandbox
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.17.6`
- Nuxt Version:     `2.16.0-27226092.034b9901`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27234503.d5127e9`
------------------------------

### Describe the bug and expected behavior

Attempting to use JSX inside a render function is now failing with `Syntax Error: Unexpected token, expected ","` 

### Steps to reproduce

View the compilation error in context here:
https://codesandbox.io/s/suspicious-euclid-g904s?

I expect to see "Hello Nuxt!" wrapped in a div with a class of "a-container-class".

### Additional context
This code was working without the upgrade nuxt bridge.

**Comment by lauer3912** [comment]
+1

**Comment by danielroe** [comment]
Yes, I can confirm the issue persists (**[reproduction](https://stackblitz.com/edit/github-xzq91u)**), though a workaround is to enable vite mode @tylerforesthauser:

```js
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
  bridge: {
    vite: true,
  },
})
```

**Comment by homerjam** [comment]
Does anyone have a workaround for this?

**Comment by Chapaev17** [comment]
+1

**Comment by gokalpfirat** [comment]
@danielroe Any updates for webpack?

**Comment by chuckadams** [comment]
The workaround to enable vite does not work for me, though it does give me nicer-looking error messages:

```
 ERROR  [commonjs--resolver] Unexpected token (Note that you need plugins to import files that are not JavaScript)                                           9:12:36 AM
file: [redacted]
225: 
226:         return (
227:             <div class={['p-splitter p-component', 'p-splitter-' + this.layout]}>
                 ^
228:                 {this.$slots.default}
229:                 {
```

**Comment by wattanx** [comment]
If you use jsx/tsx with nuxt/bridge, you need to add the `isTSX` option.
https://github.com/nuxt/bridge/pull/1064

```ts
export default defineNuxtConfig({
  birdge: {
    typescript: { isTSX: true }
  }
})
```
