### ISSUE TITLE
Error using nuxi preview

### ISSUE THREAD

**Issue by claytongf** [nuxt/bridge#19]
### Environment

Nuxt CLI v3.0.0-27454426.4cefce4                                                                                                                                                                             18:24:52
RootDir: /var/www/frontend                                                                                                                                                                                   18:24:52
Nuxt project info:                                                                                                                                                                                           18:24:52

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `npm@8.1.3`
- Bundler:          `Webpack`
- User Config:      `head`, `env`, `css`, `plugins`, `components`, `buildModules`, `modules`, `axios`, `auth`, `router`, `vuetify`, `build`, `bridge`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/auth-next@5.0.0-1624817847.21691f1`
- Build Modules:    `@nuxtjs/vuetify@1.12.3`, `cookie-universal-nuxt@2.1.5`, `@nuxt/bridge@3.0.0-27454426.4cefce4`

### Reproduction

npm run build
npm run start

In the codesandbox, the error shown is different
https://codesandbox.io/s/white-dust-7rnv05

### Describe the bug

When I build  the project for production using `npm run build`, it finishes correctly with no errors.
The error shows when I use to start a server with `npm run start`
The error is in loop
`Cannot find module '/var/www/frontend/.output/server/node_modules/tslib/modules/index.js' imported from /var/www/frontend/.output/server/chunks/app/server.mjs
  at new NodeError (node:internal/errors:371:5)  
  at finalizeResolution (node:internal/modules/esm/resolve:418:11)  
  at moduleResolve (node:internal/modules/esm/resolve:981:10)  
  at defaultResolve (node:internal/modules/esm/resolve:1078:11)  
  at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)  
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)  
  at link (node:internal/modules/esm/module_job:78:36)`

**Comment by danielroe** [comment]
This doesn't reproduce for me using the repro above and the latest bridge. Let me know if it's still present for you, with a reproduction.
