### ISSUE TITLE
Vue Warn: Configure your bundler to alias "vue" to "vue/dist/vue.esm-bundler.js"

### ISSUE THREAD

**Issue by jimhucksly** [nuxt/bridge#198]

**Comment by shtse8** [comment]
seems adding this in `nuxt.config.ts` to make it work.

```json
  hooks: {
    'vite:extendConfig': (config, { isClient, isServer }) => {
      if (isClient)
        config.resolve.alias.vue = 'vue/dist/vue.esm-bundler.js'
    },
  },
```

**Comment by abdonrd** [comment]
We have an issue with TS types:

```
Property 'vue' does not exist on type 'AliasOptions'.
  Property 'vue' does not exist on type 'readonly Alias[]'.
```

<img width="755" alt="Screenshot 2022-11-22 at 12 10 49 PM" src="https://user-images.githubusercontent.com/1007051/203378009-05ca7026-3f12-4097-b034-828da1a961d6.png">

Have you been able to solve it?

**Comment by rmdhanrama** [comment]
> I have the same problem when I try to use `.js` components instead of `.vue`:
> 
> ```js
> // app.js
> export default {
>   template: '<h1>App</h1>',
> 
>   setup() {
>     console.log('setup')
>   }
> }
> ```
> 
> I tried to fix this warn added this to nuxt config:
> 
> ```js
> import { defineNuxtConfig } from 'nuxt3'
> 
> import vue from '@vitejs/plugin-vue'
> 
> // https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
> export default defineNuxtConfig({
>   target: 'static',
> 
>   vite: {
>     resolve: {
>       alias: {
>         vue: 'vue/dist/vue.esm-bundler'
>       }
>     },
> 
>     plugins: [
>       vue()
>     ]
>   }
> })
> ```
> 
> But then I have this other warn: `runtime-core.esm-bundler.js:6589 [Vue warn]: Component is missing template or render function. at <NuxtRoot>`
> 
> How we should configure nuxt3 to work with `template` option ?




> I have the same problem when I try to use `.js` components instead of `.vue`:
> 
> ```js
> // app.js
> export default {
>   template: '<h1>App</h1>',
> 
>   setup() {
>     console.log('setup')
>   }
> }
> ```
> 
> I tried to fix this warn added this to nuxt config:
> 
> ```js
> import { defineNuxtConfig } from 'nuxt3'
> 
> import vue from '@vitejs/plugin-vue'
> 
> // https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
> export default defineNuxtConfig({
>   target: 'static',
> 
>   vite: {
>     resolve: {
>       alias: {
>         vue: 'vue/dist/vue.esm-bundler'
>       }
>     },
> 
>     plugins: [
>       vue()
>     ]
>   }
> })
> ```
> 
> But then I have this other warn: `runtime-core.esm-bundler.js:6589 [Vue warn]: Component is missing template or render function. at <NuxtRoot>`
> 
> How we should configure nuxt3 to work with `template` option ?

so helpful thank a lot
