### ISSUE TITLE
Error when integrating Firebase V9 only with Nuxt Bridge

### ISSUE THREAD

**Issue by jeverduzco** [nuxt/bridge#205]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `2.16.0-27266415.3ab12f9f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `publicRuntimeConfig`, `head`, `components`, `modules`, `css`, `plugins`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27267163.9b8d44d`

### Describe the bug

I have a Firebase V9 integration with Nuxt 2.15.8 and it works perfect. But when I try to do the same integration with Nuxt Bridge I get this error in console:

`Uncaught TypeError: Cannot destructure property '__extends' of '_tslib_js__WEBPACK_IMPORTED_MODULE_0___default.a' as it is undefined.
    at eval (index.js?8a15:3)
    at Module../node_modules/tslib/modules/index.js (app.js:417)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at eval (index.esm.js?ffa6:1)
    at Module../node_modules/@firebase/component/dist/index.esm.js (app.js:23)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at eval (index.esm2017.js?5606:1)
    at Module../node_modules/@firebase/app/dist/index.esm2017.js (app.js:11)`

### Reproduction

I made a project in Code Sandbox for a better reproduction of the problem which can be accessed here: [https://codesandbox.io/s/icy-dawn-c7eri?file=/nuxt.config.js](https://codesandbox.io/s/icy-dawn-c7eri?file=/nuxt.config.js)

The problem is visible by opening in a new tab and checking the browser console.

It only happens when loading the `firebase.js` file located in the plugins folder. The same plugin in Nuxt 2.15.8 works perfectly.

**Comment by FfionTree** [comment]
You can temporarily solve this problem and get firebase working with nuxt-bridge by adding an alias to fix the missing tslib exports.

// nuxt.config.js
alias: {
        tslib: 'tslib/tslib.es6.js'
}
    
Here is a ref to the same issue and the solution.
https://sam-ngu.medium.com/solved-rxjs-typeerror-cannot-destructure-property-extends-of-tslib-js-e378a98b7aec
