### ISSUE TITLE
nuxt bridge __webpack_hmr/client 404 Not Found

### ISSUE THREAD

**Issue by cpt-n3mo** [nuxt/bridge#223]
### Environment

Nuxt project info:                                                                                                                           18:38:21

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.11.1`
- Nuxt Version:     `0.0.0`
- Package Manager:  `unknown`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

when project is running devtools complains about __webpack_hmr/client 404 Not Found

### Reproduction

create a new nuxt2 app with npx create-nuxt-app
follow the docs to convert  it to bridge.
run npm run dev open browser on hosted server, then open devtools.

### Additional context

non

### Logs

```shell
Firefox can’t establish a connection to the server at http://127.0.0.1:3000/__webpack_hmr/client.
```

**Comment by existe-deja** [comment]
Hi,

it's happening on nuxt 2.16.1, nuxt-bridge without any bridge config (so it uses webpack)
a temporary fix for my nuxt server plugin is :
```
export default defineNuxtPlugin(async (nuxtApp) => {
  const event = useRequestEvent()
  if (event.node.req.url.startsWith('/__webpack_hmr') || event.node.req.url.startsWith('/__nuxt_error')) {
    return
  }
  ...
})
```
