### ISSUE TITLE
Global styles are not inlined in HTML

### ISSUE THREAD

**Issue by Destaq** [nuxt/bridge#26]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.17.4`
- Nuxt Version:     `2.15.8`
- Package Manager:  `npm`
- Bundler:          `Webpack`
- User Config:      `head`, `css`, `plugins`, `bridge`, `components`, `buildModules`, `modules`, `build`
- Runtime Modules:  `cookie-universal-nuxt@2.1.5`, `@nuxtjs/axios@5.13.6`
- Build Modules:    `@nuxt/bridge@3.0.0-27237089.3e38eb8`
------------------------------

### Describe the bug

TailwindCSS plugins requirements are not being loaded as they should, being run only after the plugin has been rendered. For this specific case, I'm using the [TailwindCSS](https://tailwindcss.com/) framework which is being enhanced by [DaisyUI](https://daisyui.com/).

However, there is an initial flicker from TailwindCSS styling to DaisyUI after the page loads. See below recording:

https://user-images.githubusercontent.com/61620873/137582807-4ec2eec8-ab0a-437c-a15d-642447fda13a.mov

I brought up this issue on the DaisyUI repo here: https://github.com/saadeghi/daisyui/issues/249, but the creator noted that it was an issue with a lack of details on Nuxt 3 and Bridge documentation. They provided a [working example for Nuxt 3](https://github.com/saadeghi/daisyui/tree/master/examples/nuxtjs-v3) in addition to [that for Nuxt 2](https://github.com/saadeghi/daisyui/tree/master/examples/nuxtjs), but neither is functional in Bridge.

### Reproduction

[Modified NuxtJS Bridge example](https://github.com/Destaq/daisyui-nuxt-bridge/tree/main/examples/nuxtjs).

**Comment by Torgian** [comment]
I've tried quite a few different things to try to resolve this issue on my own project;

1) Add the css file in an `app.vue` file
2) Add the css to the `default.vue` layout
3) Import it in the `style` block
4) Original css import in `Nuxt.config` did not seem to work 

Basically, css seemed to work fine in nuxtjs. But, after adding Nuxt Bridge, we get that flash of un-styled pages when doing a hard refresh of the browser. 

Haven't found a solution. Pretty much stuck at this point.

**Comment by phoenix-ru** [comment]
> I've tried quite a few different things to try to resolve this issue on my own project;

Hi, in my setup everything works fine when adding it via SCSS (Nuxt Bridge):
```vue
<style scoped lang="scss">
@use './my_styles.css';
</style>
```

**Comment by Torgian** [comment]
> > I've tried quite a few different things to try to resolve this issue on my own project;
> 
> Hi, in my setup everything works fine when adding it via SCSS to `layouts/default.vue` and all other layout files (Nuxt Bridge):
> 
> ```
> <style lang="scss">
> @use './my_styles.css';
> </style>
> ```

Thanks for the reply, but this did nothing for me. I even tried setting the styles directly in the `default.vue` file for my default layout, but this also did nothing. It has something to do with processing the style and setting it before the screen renders. This has never been a problem before attempting to update to `bridge`.

As it is, this, as well as an issue with `nuxt auth` compatibility makes `bridge` a non-starter for our app.

**Comment by patrickalima98** [comment]
Hi,

I'm with the same problem in my Nuxt js project, using in SSR mode. The problem is the Nuxt is not sending CSS in inline style like the 2.x version. I have tried with local CSS and with my UI Lib.

But I can confirm this works if i import the CSS in any layout file component.

**Comment by patrickalima98** [comment]
> > I've tried quite a few different things to try to resolve this issue on my own project;
> 
> Hi, in my setup everything works fine when adding it via SCSS to `layouts/default.vue` and all other layout files (Nuxt Bridge):
> 
> ```
> <style lang="scss">
> @use './my_styles.css';
> </style>
> ```

HI, this works for me, but I get a new error when my CSS is from my node_modules with relative paths for font-files, like the bellow screenshot.

![image](https://user-images.githubusercontent.com/17622137/172077171-093d1218-fdc8-4fb6-9bc5-e11b889aeada.png)

**Comment by phoenix-ru** [comment]
> > > I've tried quite a few different things to try to resolve this issue on my own project;
> > 
> > 
> > Hi, in my setup everything works fine when adding it via SCSS to `layouts/default.vue` and all other layout files (Nuxt Bridge):
> > ```
> > <style lang="scss">
> > @use './my_styles.css';
> > </style>
> > ```
> 
> HI, this works for me, but I get a new error when my CSS is from my node_modules with relative paths for font-files, like the bellow screenshot.
> 
> ![image](https://user-images.githubusercontent.com/17622137/172077171-093d1218-fdc8-4fb6-9bc5-e11b889aeada.png)

This is not related to the topic, but I had the same issue.
If that is your library, make sure you either set webpack's `publicPath` to the name of your library (e.g. `publicPath: '@yourscope/yourlib'`) or you do a construction like this:
```scss
// your_library.scss
$module-path: '@' !default; // or any alias to project root

// same file, in your font-face definition
src: url(#{$module-path}/path/to/font)

// when consuming (e.g. in nuxt)
@use '@yourscope/yourlib/your_library.scss' with (
  $module-path: '@yourscope/yourlib'
);
```

**Comment by justindasilva** [comment]
My solution for now was to remove this from my `nuxt.config.ts`
```
css: [
    `~/assets/scss/index.scss`,
  ],
```

And add this to my `layouts/default.vue`
```
<style lang="scss">
@import '~/assets/scss/index.scss';
</style>
```

**Comment by azelalynetan** [comment]
@justindasilva I have the same issue. I tried your solution but it didn't worked for me. I'm still seeing my app being unstyled for a second after hard refresh. I'm using nuxt bridge with tailwind. 

Do you have or does anyone have a suggestion or workaround for this?

**Comment by enkot** [comment]
I also have this issue, but when disable nitro - it works fine (inlines css in SSR):
```
export default defineNuxtConfig({
  ...
  bridge: {
    nitro: false,
  }
})
```

**Comment by azelalynetan** [comment]
I tried disabling the nitro and it works. I no longer encountered unstyled components for a second after reloading the page. Is there other way to fix it without disabling the nitro?

**Comment by AndrewBogdanovTSS** [comment]
Disabling nitro is not the solution as well as placing CSS in layouts, all of that are dirty workarounds. Nuxt Bridge should support it's default feature of referencing CSS files in nuxt config.

**Comment by AndrewBogdanovTSS** [comment]
@danielroe any ETA for this fix? Could it be prioritized for RC11 ?

**Comment by danielroe** [comment]
Just looking into this, I can't reproduce - _in production_ - with the following config:

```js
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
  bridge: {
    nitro: true,
    vite: false
  },
})
```

Note that:

1. I can reproduce with vite enabled (as it is by default), as vite currently does not have support for inlining styles
2. I can reproduce in _development_ mode with webpack

**Comment by AndrewBogdanovTSS** [comment]
@danielroe yes, that's correct, the issue is reproducible is only in development mode with Webpack, but it has to work the same as in production, right?

**Comment by AndrewBogdanovTSS** [comment]
@danielroe is there any issue where I could track progress on adding inline styles for Vite?

**Comment by maxarias-io** [comment]
This still seems to be an issue on Birdge `3.0.0-27833237.ddd8ecc`

Even with this config: https://github.com/nuxt/bridge/issues/26#issuecomment-1256707353
