### ISSUE TITLE
can't use `export from` syntax

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt/bridge#305]
### Environment

Nuxt project info:                                                                                                                                                                                 10:12:03

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.18`
- Builder:          `webpack`
- User Config:      `plugins`, `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27498038.f18e68b`
------------------------------

### Reproduction

https://codesandbox.io/s/q79osj?file=/plugins/index.js

### Describe the bug

code like this
```js
export { default as test} from '~/utils/test'
console.log(test)
```
show me error:
```
[nuxt] [request error] test is not defined
  at Module../plugins/index.js (./.nuxt/dist/server/server.js:8054:13)
  at __webpack_require__ (./.nuxt/dist/server/server.js:27:30)
  at Module../.nuxt/index.js (./.nuxt/dist/server/server.js:816:85)
  at __webpack_require__ (./.nuxt/dist/server/server.js:27:30)
  at Module../.nuxt/server.js (./.nuxt/dist/server/server.js:1624:67)
  at __webpack_require__ (./.nuxt/dist/server/server.js:27:30)
  at Object.0 (./.nuxt/dist/server/server.js:8079:18)
  at __webpack_require__ (./.nuxt/dist/server/server.js:27:30)
  at ./.nuxt/dist/server/server.js:133:18
  at Object.<anonymous> (./.nuxt/dist/server/server.js:136:10)
```

**Comment by danielroe** [comment]
This is just JS syntax. You're exporting the variable but not making it available within the JS scope.

To _use_ it (like console.logging it) you would need to import it, not just export it. And to use it as a plugin, you need to export it as `default`, not `test`.

```diff
- export { default as test } from "~/utils/test";
+ export { default } from "~/utils/test";

- console.log(test)
```

or

```diff
- export { default as test } from "~/utils/test";
+ import { default as test } from "~/utils/test";

  console.log(test)

+ export default test
```

Here's a working example: https://codesandbox.io/s/learn-nuxt-bridge-forked-dkt0x2

**Comment by baixiaoyu2997** [comment]
ops, my bad
