### ISSUE TITLE
`useHead`  and `@vueuse/nuxt` conflict

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt/bridge#307]
### Environment

Nuxt project info:                                                                                                                                                                                 13:19:29

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.18`
- Builder:          `webpack`
- User Config:      `plugins`, `buildModules`, `bridge`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@8.2.5`, `@nuxt/bridge@3.0.0-27498038.f18e68b`
------------------------------

### Reproduction

https://codesandbox.io/s/gj3p08?file=/plugins/index.js

### Describe the bug

when buildModules add `@vueuse/nuxt`, then in plugins  use `useHead` :
```js
export default defineNuxtPlugin((nuxtApp) => {
  useHead({
    title: "你好",
  });
});

```
will show error
```
[Vue warn]: inject() can only be used inside setup() or functional components.
```
`useHead` autoimport seems have a problem with order,change to this can fix
```js
import { useHead } from '#head'
export default defineNuxtPlugin((nuxtApp) => {
  useHead({ title: '你好' })
})

```

### Additional context

@antfu 大佬翻我

**Comment by antfu** [comment]
@vueuse/nuxt v8.2.6 should fix it.

**Comment by baixiaoyu2997** [comment]
感谢~
