### ISSUE TITLE
Nuxt Bridge TailwindCSS Issue

### ISSUE THREAD

**Issue by madeofcloud** [nuxt/bridge#313]
Also experiencing issues with this. What causes the issue for me is that the configuration syntax seems to have changed. You have to change this:

```js
// nuxt2, no bridge:
export default {
  build: {
    postcss: {
      plugins: {
        tailwindcss: {},
        autoprefixer: {}
      }
    }
  },
}
```

to this:
```js
// nuxt2, with bridge:
export default defineNuxtConfig({
  build: {
    postcss: {
      postcssOptions: {
        plugins: {
          tailwindcss: {},
          autoprefixer: {},
        },
      }
    },
  },
})
```

That's fine so far. Now the infinite refresh loop is gone. Issue now that postcss seems not to work quite right anymore. It doesn't pick up the .css file and therefore tailwind just doesn't work. 

My question to the authors of nuxtjs: Where would the best place be to create issues for this? (I am not using nuxt-tailwind, so not there). 
- here in nuxt/framework?
- in @nuxt/postcss8
- or at tailwind?

_Originally posted by @madebyfabian in https://github.com/nuxt/bridge/issues/29#issuecomment-1097947259_

Has this issue been fixed yet or does it work on the beta for version 3?

**Comment by dargmuesli** [comment]
Would you mind showing us your tailwind config?

**Comment by madeofcloud** [comment]
`const colors = require('tailwindcss/colors')

module.exports = {
  content: [
    "./components/**/*.js",
    "./components/**/*.vue",
    "./components/**/*.ts",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.js",
    "./plugins/**/*.ts",
    "./nuxt.config.js",
    "./nuxt.config.ts",
  ],
  theme: {
    extend: {
      colors: {
        primary: colors.blue,
        secondary: colors.cyan,
        plain: colors.gray
      }
    }
  },
  variants: {
    extend: {
      scale: ['active'],
      textColor: ['active']
    }
  }
}`

Although I would try to fix the issue, instead I am in the process of migrating directly from Nuxt 2 to Nuxt 3 without using Nuxt bridge between them. I have made previous projects starting with Nuxt 3 where Tailwind worked so migrating directly to version 3 would probably work fine.
