### ISSUE TITLE
nuxt app instance unavailable while using autoImports and nitro set false

### ISSUE THREAD

**Issue by antlionguard** [nuxt/bridge#319]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.17.6`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.18`
- Builder:          `webpack`
- User Config:      `target`, `head`, `css`, `components`, `buildModules`, `build`, `bridge`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`, `@nuxt/bridge@3.0.0-27498038.f18e68b`
------------------------------

### Reproduction

https://github.com/piniajs/example-nuxt-bridge

I used this example project. Also nuxt bridge version is: [3.0.0-27498038.f18e68b](https://www.npmjs.com/package/@nuxt/bridge-edge/v/3.0.0-27498038.f18e68b)
### Describe the bug

1. Set ```autoImports: true``` and ```nitro: false```  in ```nuxt.config.js```
2. Add ```const route = useRoute();``` line anywhere in setup inside the ```index.vue``` page.
3. Run project and try refresh page twice.

Cannot use autoImports when nitro is set false.

### Additional context
I commented this 3 line and error gone. 
<img width="449" alt="image" src="https://user-images.githubusercontent.com/26603638/165938509-5f999ef8-f948-4ff9-a416-a3ab7db6bb2f.png">

But i got some errors on console after removing these lines. Because these lines added for prevent context-sharing in server-side. 
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/26603638/165938836-21fc3faf-865a-4e2b-9dd6-b4d097ef2c17.png">

**Comment by Luferov** [comment]
Same.

**Comment by Luferov** [comment]
@antlionguard  Have you any results?

**Comment by antlionguard** [comment]
> @antlionguard Have you any results?

unfortunately not. i need to focus my project. i don't have any free time for looking this issue. i hope this will be resolved from nuxt team asap.

**Comment by Luferov** [comment]
@antlionguard are you using vuex and pinia together?

**Comment by antlionguard** [comment]
> @antlionguard are you using vuex and pinia together?

yep.

**Comment by Luferov** [comment]
> > @antlionguard are you using vuex and pinia together?
> 
> yep.

Ok, it’s all in store folder?

**Comment by antlionguard** [comment]
> > > @antlionguard are you using vuex and pinia together?
> > 
> > 
> > yep.
> 
> Ok, it’s all in store folder?

yes. pinia stores inside store/modules. vuex stores are inside store folder.

**Comment by danielroe** [comment]
**Minimal reproduction**: https://stackblitz.com/edit/github-tas3ez

**Comment by Luferov** [comment]
> **Minimal reproduction**: https://stackblitz.com/edit/github-tas3ez

Yep, 
![image](https://user-images.githubusercontent.com/26242554/177831789-4e234f73-5f0e-4be2-9c5c-bfb3a1769f3a.png)

**Comment by MartinX3** [comment]
Using the latest nuxt/bridge-edge version the reproducer gives me a `Hello Nuxt! /`
So the issue is fixed?

**Comment by danielroe** [comment]
It seems so: https://stackblitz.com/edit/github-tas3ez.

Let me know if not and I'll reopen.

**Comment by antlionguard** [comment]
> It seems so: https://stackblitz.com/edit/github-tas3ez.
> 
> Let me know if not and I'll reopen.

Last version of bridge working great at my project. Thanks!
