### ISSUE TITLE
`nuxi generate` does not create `.output` directory anymore

### ISSUE THREAD

**Issue by dargmuesli** [nuxt/bridge#32]
### Environment

- Nuxt version: `2.16.0-27358576.777a4b7f`
- @nuxt/bridge version: `3.0.0-27495976.e31c604`
- nitropack version: `0.2.5`

### Reproduction

As the linked, simple renovate-PR highlights the issue, I don't think another repro is needed. If it is, feel free to tell me.

### Describe the bug

After upgrading `@nuxt/bridge` I receive the [error](https://github.com/dargmuesli/jonas-thelemann/runs/5992266520?check_suite_focus=true#step:5:199) `FATAL  [nitro] Please use nuxt generate for static target`, which I (kinda) already do (`nuxi generate`).
Later on in the same build I now receive a webpack [error](https://github.com/dargmuesli/jonas-thelemann/runs/5992266520?check_suite_focus=true#step:5:247) originating from `@nuxt/bridge`, which I can "fix" by adding `@nuxt/bridge` to the `build.transpile` array.
After doing so tough, **there is no `.output` directory created anymore**.

### Additional context

Sounds similar to https://github.com/nuxt/framework/issues/4179.

### Logs

```shell
https://github.com/dargmuesli/jonas-thelemann/runs/5992266520
```

**Comment by jegardiner** [comment]
I'm also having this problem, although I've **not** added `@nuxt/bridge` to the `build.transpile array`.

`nuxi generate` does not create the `.ouput` folder, despite mentioning it in it's success message:

`✔ You can now deploy .output/public to any static hosting!`

I can use `nuxt generate`, which outputs to the `dist` folder as a workaround for now.

**Comment by roseMix** [comment]
@jegardiner I was able to to use `nuxt generate` but only after adding `"nuxt": "npm:nuxt-edge"` to my `package.json`. 

@danielroe is this intended behavior?

**Comment by dargmuesli** [comment]
The `dist` directory with `nuxt generate` does not contain the same files as the `.output` does with `nuxi generate`. My intention is to keep all files directly deployable to a static file hoster / nginx with `nuxi`, while what `nuxt`/`dist` gives me is a "server and client" output.

**Comment by roseMix** [comment]
@dargmuesli hmm did you set ` target: 'static'` in `nuxt.config.js`? You're output in `dist` should then be uploadable to any static host.

BTW This is just a temporary workaround using the old `nuxt` command line. Hopefully once  #324 lands we'll be able to use the new `nuxi` command.

**Comment by dargmuesli** [comment]
Yes, I have `target` set to `static`.

**Comment by dargmuesli** [comment]
> put the nuxi generate as the script for build not under generate not sure why.

I guess `build` is kind of the standard and for generated projects building is equivalent to generating.
