### ISSUE TITLE
Cannot find package '/usr/src/app/.output/server/node_modules/ufo

### ISSUE THREAD

**Issue by rvmourik** [nuxt/bridge#345]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Builder:          `webpack`
- User Config:      `alias`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `router`, `auth`, `axios`, `build`, `runtimeConfig`, `bridge`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-storm@1.1.3`, `nuxt-webfontloader@1.1.0`, `@nuxtjs/router-extras@1.1.1`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/auth-next@5.0.0-1643791578.532b3d6`, `@nuxtjs/dotenv@1.4.1`, `@nuxtjs/universal-storage@0.5.9`, `nuxt-fontawesome@0.4.0`, `vue-scrollto/nuxt`, `@webstacknl/crud/nuxt@1.0.0-alpha.34`, `@nuxt/bridge@3.0.0-27530716.c4f8671`
------------------------------

### Reproduction

.

### Describe the bug

If I run the `nuxi preview` command after building it, it produces the following error:

```
 Cannot find package '.output/server/node_modules/ufo/'
```

I saw this issue nuxt/framework#4585 with the same message but this is for Nuxt 3 and I am using Bridge for this project. I have deleted the .output/.nuxt/node_modules/yarn.lock and installed everything from scratch to see if that resolves the problem. Sadly it doesn't.

As @pi0 asked in the related issue if the `.output/server/node_modules` directory exists, it does and there is also a folder with the name `ufo` with an `index.cjs` en `index.mjs` in it. However, the package.json is missing in the folder. Could that be the problem the import doesn't work.

Also if I inspect the `./server/index.mjs` in Webstorm, Webstorm can't open the `import 'ufo'` line, but it can open the others like `import 'unstorage'`.

Hope you can help me out with this.

**Comment by P4sca1** [comment]
Related (including a reproduction): https://github.com/nuxt/bridge/issues/344

**Comment by Luferov** [comment]
And if added “ufo” to transpile?

**Comment by rvmourik** [comment]
> And if added “ufo” to transpile?

nope, that doesn't work. But I guess the missing package.json in the ufo folder is the issue.

**Comment by dargmuesli** [comment]
I guess a merge of https://github.com/nuxt/nuxt.js/pull/10013 could help, which upgrade ufo to `0.8.4`.

**Comment by rvmourik** [comment]
> I guess a merge of [nuxt/nuxt.js#10013](https://github.com/nuxt/nuxt.js/pull/10013) could help, which upgrade ufo to `0.8.4`.

I manually added it to a resolves in package.json and installed 0.8.4, for now that causes the error to be gone.

**Comment by gustawdaniel** [comment]
This can be connected:

https://github.com/nuxt/framework/issues/4883

I prepared PR that updates only ufo but need a maintainer to approve running workflows:

https://github.com/nuxt/nuxt.js/pull/10503

**Comment by P4sca1** [comment]
After upgrading my dependencies by refreshing the lock file, this issue is gone for me. Can you confirm?

**Comment by dargmuesli** [comment]
I can confirm. @danielroe do your thing 😜❌
