### ISSUE TITLE
Nuxt bridge does not respect render.resourceHints false

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [nuxt/bridge#346]
### Environment

sandbox@sse-sandbox-mc2cu5:/sandbox$ npx nuxi info
Nuxt CLI v3.0.0-rc.3-27540667.2886dfd                                  23:06:13
RootDir: /sandbox                                                      23:06:14
Nuxt project info:                                                     23:06:14

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Builder:          `webpack`
- User Config:      `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27530716.c4f8671`

### Reproduction

https://codesandbox.io/s/nuxt-bridge-resourcehints-issue-mc2cu5

### Describe the bug

`render.resourceHints: false`  seems to do nothing in the bridge.

```ts
// nuxt.config.js
import { defineNuxtConfig } from "@nuxt/bridge";

export default defineNuxtConfig({
  render: {
    resourceHints: false
  }
});

```

### Additional context

https://nuxtjs.org/docs/configuration-glossary/configuration-render/#resourcehints

**Comment by danielroe** [comment]
This is the case. Using nitro, the `render` property in your `nuxt.config` is not taken into account. Instead, https://github.com/nuxt/vue-bundle-renderer is used to render the page response.

**Comment by Envoy49** [comment]
Have the same issue here! 

```
  render: {
    resourceHints: false
  }
```
Doesn't have any effect on anything

**Comment by Envoy49** [comment]
Whoever comes here, I ended up patching vue-bundle-renderer to match my needs. I had to disable all preloaded and prefetched link tags and redirect them to the script tag before body close, which was not possible from nuxt.config

**Comment by wattanx** [comment]
If you want to disable prefetch in nuxt/bridge, you can configure the following settings as in nuxt 3.
(Must be the latest `@nuxt/bridge-edge` until RC.5 or stable is released.)

```ts
// nuxt.config.ts
export default defineNuxtConfig({
  hooks: {
    nuxt.hook('build:manifest', (manifest) => {
      for (const key in manifest) {
        // or other logic
        manifest[key].dynamicImports = []
      }
    })
  }
})
```
