### ISSUE TITLE
Will Nuxt bridge continue to get updates?

### ISSUE THREAD

**Issue by nayils** [nuxt/bridge#354]
Will nuxt bridge continue to be supported as a continuation of nuxt 2? Or will it close eventually?

Does it make sense to start a project on nuxt bridge? Nuxt 3 doesn't support my plugins yet.
Can I start a project on the bridge? So that in half a year (when all add-ons will have a stable release) to switch to a full-fledged 3.0?

**Comment by klausXR** [comment]
This package doesn't seem to be very well maintained, unfortunately. There are many people complaining about issues on discord and not much help, even the reported issues here go unnoticed. 

The recommendation is to start new projects using Nuxt 3, but yeah, some important modules are missing.

Sentry, for example, doesn't work. I don't know who starts a production ready application with no error reporting.

Its very weird building with this tech stack currently

**Comment by yshrsmz** [comment]
They are currently focusing on stabilizing Nuxt 3.
Their resource is finite, we should let them focus on Nuxt 3 for now (though I too share your frustration ;D

**Comment by nayils** [comment]
Does this mean that nuxt bridge will no longer be supported after nuxt 3?

**Comment by antlionguard** [comment]
> Does this mean that nuxt bridge will no longer be supported after nuxt 3?

no that's not i mean. because this repo is really good helping for nuxt 2 to 3 migration process. The nuxt team cannot allocate resources for this place for now.

**Comment by danielroe** [comment]
Closing in favour of https://github.com/nuxt/bridge/discussions/353.
