### ISSUE TITLE
OnActivated does not trigger when element is added to the page after timeout

### ISSUE THREAD

**Issue by timgoeller** [nuxt/bridge#358]
### Environment

Nuxt CLI v3.0.0-rc.3-27550969.a4a3cff                                                                                                                                                  13:02:47
RootDir: /Users/tim.goeller/Documents/GitRepos/testactivated                                                                                                                           13:02:47
Nuxt project info:                                                                                                                                                                     13:02:47

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.17.6`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.15`
- Builder:          `webpack`
- User Config:      `bridge`, `ssr`, `target`, `components`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27545203.75e046f`
------------------------------

### Reproduction

https://github.com/timgoeller/Nuxt-OnActivated-Bug

### Describe the bug

When adding a component via `v-if` once a timeout runs out, `onActivated` is not triggered.

**Comment by danielroe** [comment]
I don't believe this is a bug in Nuxt. Neither vue 2.7 nor vue 3 behave as you are expecting - see https://stackblitz.com/edit/vitejs-vite-htwvba for example, and feel free to raise an issue in https://github.com/vuejs/core or https://github.com/vuejs/vue.
