### ISSUE TITLE
Garbage .js files if using pinia store or `date-holidays`

### ISSUE THREAD

**Issue by MartinX3** [nuxt/bridge#395]
### Environment

Nuxt CLI v3.0.0-rc.4                                                                                                                                                           22:26:06
RootDir: /home/martin/Downloads/000Verein/0                                                                                                                                    22:26:06
Nuxt project info:                                                                                                                                                             22:26:06

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.5.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `npm@8.13.0`
- Builder:          `webpack`
- User Config:      `build`, `buildModules`, `components`, `css`, `head`, `modules`, `plugins`, `ssr`, `target`, `serverHandlers`, `devServerHandlers`, `bridge`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/stylelint-module@4.1.0`, `@nuxtjs/vuetify@1.12.3`, `@pinia/nuxt@0.1.9`, `@nuxt/bridge@3.0.0-27621666.ee600b4`
------------------------------

### Reproduction

`npm run build`
`nuxi generate`
[reproducer.zip](https://github.com/nuxt/bridge/files/9074875/reproducer.zip)

### Describe the bug

The generated `*.js` files containing garbage code.
As example `Uncaught SyntaxError: Invalid or unexpected token (at d8fda42.js:2:71005)`
`y=t.d*n+t.m*o+t.n*l+t.f*m+t.Ï‰*d,[s,M]=r.b.sincos(y);`
The `Ï‰` is one of the invalid characters.

It seems the execution of
`new Holidays('DE', { languages: ['de'] })` from [date-holidays](https://www.npmjs.com/package/date-holidays) causes it.

### Additional context

```
ssr: false,
target: 'static',
```

### Logs

```shell
No errors.
```

**Comment by danielroe** [comment]
Would you be able to create a reproduction from https://stackblitz.com/github/nuxt/starter/tree/v2-bridge?

I can't reproduce this locally with the zipfile you provided. It feels like this and https://github.com/nuxt/bridge/issues/396 have the same cause, and that this cause is to do with something else about your setup.

**Comment by MartinX3** [comment]
It works with `node .output/server/index.mjs`.
The problem is, I need it as a static website on a static webspace without node.

**Comment by danielroe** [comment]
Let's track in #396 as I believe the cause is the same in both cases.

**Comment by MartinX3** [comment]
For reference

https://github.com/nuxt/bridge/issues/396#issuecomment-1179546974

Tracked in #20
