### ISSUE TITLE
render `<head>` with `ssr: false`

### ISSUE THREAD

**Issue by MartinX3** [nuxt/bridge#396]
### Environment

Nuxt CLI v3.0.0-rc.4                                                                      00:21:45
RootDir: /home/developer/verein/rtc-koeln/codesandbox-nuxt-master                         00:21:46
Nuxt project info:                                                                        00:21:46

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.5.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `head`, `components`, `modules`, `css`, `plugins`, `ssr`, `target`, `serverHandlers`, `devServerHandlers`, `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27621666.ee600b4`
------------------------------

### Reproduction

`nuxi generate`
[reproducer.zip](https://github.com/nuxt/bridge/files/9075294/reproducer.zip)

### Describe the bug

Umlauts are broken
`ÖÄÜ öäü`

It works in Nuxt 2 without the bridge.
And it works with `nuxi dev` with the bridge.

Result:
`Fehlercode 404 Ã– OE Ã„ AE Ãœ UE Ã¤ ae Ã¶ oe Ã¼ ue`
instead of
`Fehlercode 404 Ö OE Ä AE Ü UE ä ae ö oe ü ue`

`&ouml;` instead of `ö` is also broken in `nuxi generate`

### Additional context

N/A

### Logs

```shell
No errors
```

**Comment by danielroe** [comment]
I can't reproduce this. Here's the bit of code that I see in the error handler:

```js
return e("div",{staticClass:"d-flex justify-center",attrs:{id:"ErrorView"}},[t._v("\n  Fehlercode "+t._s(t.error.statusCode)+"\n  Ö OE Ä AE Ü UE ä ae ö oe ü ue\n")])})
```

And here's a stackblitz working fine: https://stackblitz.com/edit/github-in3815.

**Comment by MartinX3** [comment]
Does you and stackblitz use `node .output/server/index.mjs`?
Then it works for me as well.

Only if I use the static content on a static website it breaks.
Or if I execute the index.html in chromium.

**Comment by danielroe** [comment]
No, the reproduction is using `serve` to serve the static files.

**Comment by MartinX3** [comment]
I have the problem locally executing the `.output/public/index.html` in my chrome browser and if I upload the `.output/public/` folder on a webserver.

If I understand `seve` correctly it creates a local node server to deliver http content?
I think that doesn't trigger the bug like executing `node .output/server/index.mjs`

**Comment by danielroe** [comment]
What do you see when you look in the source files directly?

**Comment by MartinX3** [comment]
The steps I did:
- Uploaded the content of `.output/public` to the root of a http server
- Accessing the website `myserver.com/adsads` (`adsads` to trigger the 404 page)

Webbrowser shows me `Fehlercode 404 Ã– OE Ã„ AE Ãœ UE Ã¤ ae Ã¶ oe Ã¼ ue`
I opened the developer tools of chromium and I get
```
index
--
fb95def.js
favicon.ico
8dd872b.js
2530676.js
0fc232f.js
```

Content of the files:
[response.zip](https://github.com/nuxt/bridge/files/9076518/response.zip)

**Comment by danielroe** [comment]
Okay. Looking at the uploaded files in `public.zip`, they are fine. No corruption.

When served in FF, also fine. When served in Chrome directly from disk, not, but that's not an issue with the files themselves.

Rather, the issue is that the charset of these files is UTF-8. You need to ensure that's how your web server is serving them.

Take away points:

1. you should configure your web server to set default encoding to utf-8. (e.g. for [Apache](https://stackoverflow.com/questions/913869/how-to-change-the-default-encoding-to-utf-8-for-apache))
2. as a workaround, you could also add `<meta charset="UTF-8">` to your `<head>`

Ultimately we need to render a basic `<head>` for `ssr: false` (including that as a default!), so this is a bug we need to resolve.

**Comment by danielroe** [comment]
we will track in ~> https://github.com/nuxt/bridge/issues/20.

**Comment by MartinX3** [comment]
@danielroe thanks for the tracking issue ticket.

Sadly I can't edit the webserver, since the hoster only gives me a ftp space and a ip address and dns name to use (including subdomains)

It's great to know that #20 will restore the working behaviour with nuxt 2 without the bridge.

I'll take a look how to manually add `<meta charset="UTF-8">` into `<head>`
