### ISSUE TITLE
[fatal] [bridge] Bridge must be enabled by using `defineNuxtConfig` to wrap your Nuxt configuration.

### ISSUE THREAD

**Issue by some-user123** [nuxt/bridge#411]
### Environment

Nuxt project info:                                                                                                                                               15:21:34

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@1.22.15`
- Builder:          `webpack`
- User Config:      `loading`, `css`, `render`, `buildModules`, `modules`, `build`, `serverMiddleware`, `bridge`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/auth-next@5.0.0-1643365392.dae6516`
- Build Modules:    `()`, `@nuxtjs/vuetify@1.12.3`, `@nuxt/bridge@3.0.0-27628458.686e3a9`
------------------------------

### Reproduction

https://github.com/some-user123/nuxt-bridge

### Describe the bug

Error message "Bridge must be enabled by using `defineNuxtConfig` to wrap your Nuxt configuration." even though the nuxt configuration is wrapped with `defineNuxtConfig`.

### Logs

```shell
yarn run v1.22.19
$ nuxi build
[log] Nuxt CLI v3.0.0-rc.4
[fatal] [bridge] Bridge must be enabled by using `defineNuxtConfig` to wrap your Nuxt configuration.
  at setup (node_modules/@nuxt/bridge/dist/chunks/module.mjs:1307:13)
  at ModuleContainer.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:582:29)
Error:  [bridge] Bridge must be enabled by using `defineNuxtConfig` to wrap your Nuxt configuration.
  at setup (node_modules/@nuxt/bridge/dist/chunks/module.mjs:1307:13)
  at ModuleContainer.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:582:29)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by aldarund** [comment]
as a workaround add section bridge : {} into config
