### ISSUE TITLE
Enabling Vite with Nuxt-Bridge prevents events from firing, but it works with Nitro.

### ISSUE THREAD

**Issue by FieldMarshallVague** [nuxt/bridge#418]
### Versions
"@nuxt/bridge": "npm:@nuxt/bridge-edge@^3.0.0-27374015.eb14eca",
"nuxt-edge": "latest",
Nuxt-Vite: ~I don't see a separate dep for nuxt/vite, I assume it's part of the nuxt-bridge package?

### Reproduction

I can't share my repo and I'm not sure how to provide a cut-down version for this.  It's a Nuxt 2 install with an update to Nuxt-Bridge (having followed the migration steps).

Here is an example of a component with the problem, though.  

NOTE: It's showing it emitting an event, but it doesn't matter if I emit or just call the local 'onClickLeftButton' method, the console.log doesn't happen in the browser.

```tsx
<template>
  <nav class="pagination">
    <button
      class="paginationButton"
      @click="$emit('clickLeft')"
    >
      <img class="paginationButtonImageLeft" src="~~/assets/images/chevron-right-blue.svg" />
    </button>
  </nav>
</template>

<script lang="ts">
import { defineComponent } from '#imports';

interface PaginationProps {
  showPages: boolean;
}

export default defineComponent<PaginationProps>({
  name: 'PaginationWrapper',
  props: {
    showPages: {
      required: false,
      type: Boolean,
      default: false,
    },
  },
  emits: ['clickLeft', 'clickRight'],
  setup (props, { emit }) {
    const onClickLeftButton = () => {
      alert('clicked Left pagination')
      emit('clickLeft');
    }

    return {
      onClickLeftButton
    };
  },
});
</script>
```

I'm also using Vite-Plugin-Checker (^0.3.4) with this config:

```js
import Checker from 'vite-plugin-checker'

export default {
  plugins: [Checker({ vueTsc: true })],
  css: {
    preprocessorOptions: {
      scss: {
          // https://vitejs.dev/config/#css-postcss
         // example : additionalData: `@import "./src/design/styles/variables";`
         // You dont need to include .scss extension.
         // this only seems to include the referenced file and NOT the dependencies of that file
         // - so include ALL files, not root files.
         additionalData: `
          @import "./assets/scss/base/responsive-breakpoints";
          @import "./assets/scss/base/font-vars";
          @import "./assets/scss/partials/_colors";
         `
     },
    },
  }
}

```

### Description

I'm using Nuxt bridge with Vite enabled, but when I assign an event handler (e.g. @click) and create a function to call alert('test'), it doesn't fire.  I've tried emitting an event and handling it, but it doesn't work even if I remove the emit and just use the local handler to console.log.

I'm using SSR: true in nuxt.config.  What's interesting is that I see these items logged to the server console when I refresh the page.  But it looks liek the events handlers aren't being assigned on the content that reaches the client.

If I switch back to Nitro, it works fine, which I've done for now.

I feel like I might be missing something really obvious, but I've checked my browser debugger for console filters, it's in verbose mode and there are no event handlers assigned to the element, and the fact it works with Nitro is a clue.

**Comment by danielroe** [comment]
I'm going to close this as there's not a lot to trace down from here. But feel free to raise a [minimal reproduction](https://stackblitz.com/github/nuxt/starter/tree/v2-bridge) and I'll happily reopen.
