### ISSUE TITLE
nuxt-bridge apollo composable

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/bridge#423]
### Environment

Operating System: Darwin
Node Version: v16.15.0
Nuxt Version: 2.16.0-27358576.777a4b7f
Package Manager: yarn@1.22.19
Builder: webpack
User Config: srcDir, ssr, dev, alias, privateRuntimeConfig, plugins, buildModules, modules, apollo, vuetify, build, bridge
Runtime Modules: @nuxtjs/apollo@4.0.1-rc.5
Build Modules: @nuxtjs/vuetify@1.12.3, @nuxt/bridge@3.0.0-27495135.4d1a6ba

### Reproduction

https://github.com/stephenjason89/nuxt-bridge

### Describe the bug

Apollo composable throws 
```
[vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function.
```

When page is rendered from the server side.
Error is not present while navigating to that page on the client side.

Try refreshing the page to see the error while on composition.vue page or by visiting composition.vue directly

**Comment by antlionguard** [comment]
You should try remove yarn.lock and install all packages again. I think new version of nuxt bridge will fix your problem.

**Comment by stephenjason89** [comment]
Hello @antlionguard 
   Removing yarn.lock and reinstalling all the dependencies together with removing vue peerDependencies, did work.
   
   Thank you so much 
   
   However, i find that script setup doesn't work properly now
   
   
<img width="278" alt="image" src="https://user-images.githubusercontent.com/3810177/179838107-d37b2e6a-2aa7-420b-825a-4436dc645ec0.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3810177/179838165-6ae4229a-49ce-4861-a4bd-f52eb2221c64.png">
<img width="619" alt="image" src="https://user-images.githubusercontent.com/3810177/179838211-2e4bce38-3e20-4e40-873c-46e4ae0740f4.png">


doing it like so works though,
<img width="390" alt="image" src="https://user-images.githubusercontent.com/3810177/179838268-89a58f48-6f0e-42ba-9666-424d149b2947.png">

**Comment by antlionguard** [comment]
Please can you try to enable autoImports in nuxt.config?

Like this: 
```ts

bridge: {
   autoImports: true
},
```

**Comment by stephenjason89** [comment]
@antlionguard I pushed a new commit to the repo that shows the problem.

Adding this didn't seem to help, I think it is autoImports:true by default right?
```
bridge: {
   autoImports: true
},
```

**Comment by stephenjason89** [comment]
@antlionguard vue-template-babel-compiler is what caused the script setup to not work properly.
removing it fixed the issue.
