### ISSUE TITLE
nuxt-bridge plugins

### ISSUE THREAD

**Issue by freezboi** [nuxt/bridge#425]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@1.22.10`
- Builder:          `webpack`
- User Config:      `bridge`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `axios`, `vuetify`, `build`, `typescript`, `vite`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`
- Build Modules:    `()`, `@nuxtjs/vuetify@1.12.3`, `@pinia/nuxt@0.3.0`, `@nuxt/bridge@3.0.0-27628751.3df21c7`

### Reproduction

https://stackblitz.com/edit/github-er4gxj?file=pages%2Findex.vue

### Describe the bug

https://v3.nuxtjs.org/guide/directory-structure/plugins#automatically-providing-helpers

It seems that type inference does not work properly when using it in a component after creating a custom plugin by following the guide in the link.
In the case of the newly created $first plugin, the type is any.

**Comment by dwightjack** [comment]
I guess this issue is related to https://github.com/nuxt/bridge/issues/539.

**Comment by wattanx** [comment]
This issue was resolved at https://github.com/nuxt/bridge/issues/539.
