### ISSUE TITLE
nuxt-bridge breaking public folder

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/bridge#427]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `srcDir`, `bridge`, `ssr`, `dev`, `alias`, `privateRuntimeConfig`, `plugins`, `buildModules`, `modules`, `apollo`, `vuetify`, `build`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `@nuxtjs/apollo@4.0.1-rc.5`
- Build Modules:    `()`, `@nuxtjs/vuetify@1.12.3`, `@nuxt/bridge@3.0.0-27636329.42ea75b`
------------------------------

### Reproduction

<img width="624" alt="image" src="https://user-images.githubusercontent.com/3810177/179846087-6fccf572-e595-46ac-9621-0f9181b7bcbc.png">

### Describe the bug

old static folder that was renamed to public folder is now not working.

**Comment by danielroe** [comment]
Yes, the folder should still be `static/` for Nuxt Bridge.
