### ISSUE TITLE
nuxt-bridge js is found but is not used because the request credentials mode does not match

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/bridge#428]
### Environment

Operating System: Darwin
Node Version: v16.15.0
Nuxt Version: 2.16.0-27616340.013f051b
Package Manager: yarn@1.22.19
Builder: webpack
User Config: srcDir, bridge, ssr, dev, alias, image, generate, head, typescript, publicRuntimeConfig, privateRuntimeConfig, css, loading, loadingIndicator, plugins, components, buildModules, modules, apollo, proxy, axios, vuetify, build, serverHandlers, devServerHandlers
Runtime Modules: @nuxt/image@0.6.2, @nuxtjs/axios@5.13.6, @nuxtjs/apollo@4.0.1-rc.5, @nuxtjs/proxy@2.1.0, nuxt-social-meta@1.0.0
Build Modules: (), nuxt-storm@1.1.3, @nuxtjs/router@1.7.0, nuxt-compress@5.0.0, @nuxtjs/vuetify@1.12.3, @nuxt/bridge@3.0.0-27636329.42ea75b

### Reproduction

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/3810177/179847048-99c6f306-1b44-45c1-9909-156a24c31efb.png">
https://github.com/stephenjason89/nuxt-bridge

### Describe the bug

I get a console warnings for a preload/resource

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/3810177/179847208-19e768d8-3c1e-4dbe-91e6-1b5a55f961ff.png">

**Comment by danielroe** [comment]
Should be resolved when https://github.com/nuxt-contrib/vue-bundle-renderer/pull/30 lands.

**Comment by stephenjason89** [comment]
Thank you @danielroe
