### ISSUE TITLE
nuxt-bridge script setup broken

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/bridge#429]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `srcDir`, `bridge`, `ssr`, `dev`, `alias`, `privateRuntimeConfig`, `plugins`, `buildModules`, `modules`, `apollo`, `vuetify`, `build`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `@nuxtjs/apollo@4.0.1-rc.5`
- Build Modules:    `()`, `@nuxtjs/vuetify@1.12.3`, `@nuxt/bridge@3.0.0-27636329.42ea75b`
------------------------------

### Reproduction

Here's a reproduction https://github.com/stephenjason89/nuxt-bridge

### Describe the bug

<img width="341" alt="image" src="https://user-images.githubusercontent.com/3810177/179850716-eb3fcf21-5d40-433a-a860-91f7f6931614.png">

Script setup doesn't work properly
using setup function works

sample error
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/3810177/179850932-e549c028-4d19-47ec-9292-1b3942f4d091.png">

**Comment by danielroe** [comment]
Here's an example of it working fine: https://stackblitz.com/edit/github-f7sp42. Maybe you can start from there and narrow it down to identify which dependency/module is responsible for the issue you're experiencing?

**Comment by stephenjason89** [comment]
i'll try it out @danielroe

**Comment by stephenjason89** [comment]
'vue-template-babel-compiler' is what caused the issue.

Thank you @danielroe 
I believe optional chaining and nullish coalescing in the template is now integrated here in bridge.
