### ISSUE TITLE
nuxt-bridge Uncaught ReferenceError: webpackHotUpdate is not defined

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/bridge#430]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@3.2.1`
- Builder:          `webpack`
- User Config:      `srcDir`, `ssr`, `dev`, `alias`, `image`, `generate`, `head`, `typescript`, `publicRuntimeConfig`, `privateRuntimeConfig`, `css`, `loading`, `loadingIndicator`, `plugins`, `components`, `buildModules`, `modules`, `apollo`, `proxy`, `axios`, `vuetify`, `build`, `serverHandlers`, `devServerHandlers`, `bridge`
- Runtime Modules:  `@nuxt/image@0.6.2`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/apollo@4.0.1-rc.5`, `@nuxtjs/proxy@2.1.0`, `nuxt-social-meta@1.0.0`
- Build Modules:    `()`, `nuxt-storm@1.1.3`, `@nuxtjs/router@1.7.0`, `nuxt-compress@5.0.0`, `@nuxtjs/vuetify@1.12.3`, `@nuxt/bridge@3.0.0-27636329.42ea75b`
------------------------------

### Reproduction

<img width="444" alt="image" src="https://user-images.githubusercontent.com/3810177/179930451-35ca47d7-219d-4918-88b5-2c7427a68b53.png">

### Describe the bug

From time to time, I get this warning in my console after page refresh.

**Comment by dargmuesli** [comment]
Did you see https://github.com/nuxt/bridge/issues/43?

**Comment by stephenjason89** [comment]
@dargmuesli  thank you for the reply. Let me try some solutions provided there and get back to you.

**Comment by dargmuesli** [comment]
What did you find out?

**Comment by stephenjason89** [comment]
Hello @dargmuesli sorry wasn't able to get back to you.
I don't see the error now 
```
    bridge: {
        nitro: false,
        autoImports: true,
    },
```

Because i turned off nitro.
Issue might be related to vite

**Comment by dargmuesli** [comment]
If the error is gone, feel free to close this issue.

**Comment by stephenjason89** [comment]
@dargmuesli It is not yet resolved, i believe. 
The link you sent me referenced doing this
<img width="739" alt="image" src="https://user-images.githubusercontent.com/3810177/181574587-29fbe718-0835-4eb9-abaa-39b6e3af4b5d.png">

Which kinda removes the error but I believe it is just a work around.

**Comment by dargmuesli** [comment]
Correct. But that's why #43 is still open. Can we close this issue to not have duplicates?

**Comment by stephenjason89** [comment]
no worries @dargmuesli ,
By the way #43  says error during extractCSS.
Mine errors even without extractCSS
