### ISSUE TITLE
Cannot call functions with template refs

### ISSUE THREAD

**Issue by antlionguard** [nuxt/bridge#433]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.17.6`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `srcDir`, `alias`, `server`, `bridge`, `head`, `css`, `styleResources`, `plugins`, `buildModules`, `gtm`, `modules`, `postcss`, `tailwindcss`, `typescript`, `sentry`, `buefy`, `image`, `axios`, `proxy`, `render`, `i18n`, `router`, `build`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `@nuxt/image@0.6.2`, `@nuxtjs/sentry@5.1.7`, `nuxt-buefy@0.3.31`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/proxy@2.1.0`, `cookie-universal-nuxt@2.2.1`, `@nuxtjs/i18n@7.2.2`, `nuxt-sweetalert2@1.0.0`
- Build Modules:    `()`, `@pinia/nuxt@0.2.0`, `@nuxtjs/eslint-module@3.1.0`, `@nuxtjs/style-resources@1.2.1`, `@nuxtjs/gtm@2.4.0`, `@nuxtjs/tailwindcss@4.2.1`, `@nuxtjs/dotenv@1.4.1`, `@nuxt/bridge@3.0.0-27636329.42ea75b`
------------------------------

### Reproduction

https://github.com/nor1c/nuxt-bridge-template-refs-reproduction/

### Describe the bug

In previous "nuxt bridge" versions, I was able to access functions in components with template ref as follows.
```ts
const test_ref = ref();

test_ref.value.save()
```

But in the new version i need to do it like this.

```ts
test_ref.value._setupState.save()
```
or
```ts
test_ref.value._setupProxy.save()
```

Are these usages now valid? I'm not sure if there is an bug or something. And i saw reproduction from @nor1c.

**Comment by danielroe** [comment]
This is a change in Vue itself between the composition API plugin and 2.7.

**Comment by antlionguard** [comment]
> This is a change in Vue itself between the composition API plugin and 2.7.

Is this now valid usage? Have I got it right?

**Comment by antlionguard** [comment]
> I think you should use `defineExpose`: https://vuejs.org/api/sfc-script-setup.html#defineexpose.

Yep. That's works. Thanks!
