### ISSUE TITLE
 ERROR  Cannot find nitro.json. Nuxi preview when nitro is off

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/bridge#440]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@3.2.1`
- Builder:          `webpack`
- User Config:      `srcDir`, `bridge`, `ssr`, `dev`, `webpackOptimisations`, `alias`, `image`, `generate`, `head`, `typescript`, `publicRuntimeConfig`, `privateRuntimeConfig`, `css`, `loading`, `loadingIndicator`, `plugins`, `components`, `buildModules`, `modules`, `proxy`, `axios`, `vuetify`, `build`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `@nuxtjs/vuetify@1.12.3`, `@nuxt/image@0.6.2`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/proxy@2.1.0`, `nuxt-social-meta@1.0.0`
- Build Modules:    `()`, `nuxt-storm@1.1.3`, `nuxt-compress@5.0.0`, `nuxt-webpack-optimisations@2.2.4`, `@pinia/nuxt@0.3.0`, `@nuxt/bridge@3.0.0-27636329.42ea75b`
------------------------------

### Reproduction

First, make sure 
```
    bridge: {
        nitro: false,
    },
```
Then nuxi build
then nuxi preview

Thank you

### Describe the bug

<img width="707" alt="image" src="https://user-images.githubusercontent.com/3810177/180836784-6ece868b-cadd-432b-a111-e37669ab63db.png">

**Comment by danielroe** [comment]
When Nitro is not enabled, you will need to run `nuxt start` rather than `nuxi preview`. If there are any issues, you may need to run specifically `./node_modules/.bin/nuxt start`.
