### ISSUE TITLE
auto-imports and composables ide auto completion

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/bridge#442]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@3.2.1`
- Builder:          `webpack`
- User Config:      `srcDir`, `bridge`, `ssr`, `dev`, `webpackOptimisations`, `alias`, `image`, `generate`, `head`, `typescript`, `publicRuntimeConfig`, `privateRuntimeConfig`, `css`, `loading`, `loadingIndicator`, `plugins`, `components`, `buildModules`, `modules`, `proxy`, `axios`, `vuetify`, `build`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `@nuxtjs/vuetify@1.12.3`, `@nuxt/image@0.6.2`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/proxy@2.1.0`, `nuxt-social-meta@1.0.0`
- Build Modules:    `()`, `nuxt-storm@1.1.3`, `nuxt-compress@5.0.0`, `nuxt-webpack-optimisations@2.2.4`, `@pinia/nuxt@0.3.1`, `@nuxt/bridge@3.0.0-27636329.42ea75b`
------------------------------

### Reproduction

useNuxtApp()
or create a composable

### Describe the bug

On a non TS file i see warnings on my editor.
<img width="629" alt="image" src="https://user-images.githubusercontent.com/3810177/181191472-0eaed8c5-b114-4e72-8458-60ad90374b8e.png">
<img width="470" alt="image" src="https://user-images.githubusercontent.com/3810177/181191535-8f05c01d-2b55-427e-bed0-1354429d62b9.png">

on a ts file however, no warnings are present.
<img width="163" alt="image" src="https://user-images.githubusercontent.com/3810177/181191682-7e74d186-e6ea-4c14-b29f-b67bb42b50b5.png">

### Additional context

This is my tsconfig
<img width="359" alt="image" src="https://user-images.githubusercontent.com/3810177/181191923-fcf84b2d-9013-494c-8834-6ac4e9460a2e.png">

and this is nuxt/tsconfig auto generated
```
// Generated by nuxi
{
  "compilerOptions": {
    "jsx": "preserve",
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Node",
    "skipLibCheck": true,
    "strict": true,
    "allowJs": true,
    "noEmit": true,
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "types": [
      "@types/graphql",
      "@pinia/nuxt",
      "@types/node",
      "@nuxt/types",
      "@nuxtjs/axios",
      "@nuxt/image",
      "@types/offscreencanvas",
      "nuxt-webpack-optimisations",
      "node"
    ],
    "baseUrl": "..",
    "paths": {
      "~~": [
        "."
      ],
      "~~/*": [
        "./*"
      ],
      "@@": [
        "."
      ],
      "@@/*": [
        "./*"
      ],
      "~": [
        "client"
      ],
      "~/*": [
        "client/*"
      ],
      "@": [
        "client"
      ],
      "@/*": [
        "client/*"
      ],
      "assets": [
        "client/assets"
      ],
      "assets/*": [
        "client/assets/*"
      ],
      "static": [
        "client/static"
      ],
      "static/*": [
        "client/static/*"
      ],
      "tslib": [
        "tslib/tslib.es6"
      ],
      "fflate": [
        "fflate/esm/browser"
      ],
      "pinia": [
        "pinia/dist/pinia"
      ],
      "#app": [
        "node_modules/@nuxt/bridge/dist/runtime/index"
      ],
      "nuxt3/app": [
        "node_modules/@nuxt/bridge/dist/runtime/index"
      ],
      "nuxt/app": [
        "node_modules/@nuxt/bridge/dist/runtime/index"
      ],
      "#build": [
        ".nuxt"
      ],
      "#build/*": [
        ".nuxt/*"
      ],
      "defu": [
        "defu"
      ],
      "@nuxtjs/composition-api": [
        "node_modules/@nuxt/bridge/dist/runtime/capi"
      ],
      "#head": [
        ".nuxt/meta"
      ],
      "~image": [
        "node_modules/@nuxt/image/dist/runtime"
      ],
      "~image/*": [
        "node_modules/@nuxt/image/dist/runtime/*"
      ],
      "#imports": [
        ".nuxt/imports"
      ]
    },
    "lib": [
      "ESNext",
      "ESNext.AsyncIterable",
      "DOM",
      "webworker"
    ]
  },
  "include": [
    "./nuxt.d.ts",
    "../**/*",
    "../client/**/*"
  ],
  "vueCompilerOptions": {
    "target": 2.7
  }
}
```

**Comment by danielroe** [comment]
Try https://github.com/nuxt/framework/issues/2320#issuecomment-995884000.
