### ISSUE TITLE
TypeError for bridge:{autoImports} in nuxt.config.ts

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/bridge#443]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@3.2.1`
- Builder:          `webpack`
- User Config:      `srcDir`, `bridge`, `ssr`, `dev`, `webpackOptimisations`, `alias`, `image`, `generate`, `head`, `typescript`, `publicRuntimeConfig`, `privateRuntimeConfig`, `css`, `loading`, `loadingIndicator`, `plugins`, `components`, `buildModules`, `modules`, `proxy`, `axios`, `vuetify`, `build`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `@nuxtjs/vuetify@1.12.3`, `@nuxt/image@0.6.2`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/proxy@2.1.0`, `nuxt-social-meta@1.0.0`
- Build Modules:    `()`, `nuxt-storm@1.1.3`, `nuxt-compress@5.0.0`, `nuxt-webpack-optimisations@2.2.4`, `@pinia/nuxt@0.3.1`, `@nuxt/bridge@3.0.0-27636329.42ea75b`
------------------------------

### Reproduction

Add this to nuxt.config.ts
```
    bridge: {
        autoImports: {
            dirs: [
                // Scan composables from nested directories
                'composables/**',
            ],
        },
    },
```

### Describe the bug

<img width="662" alt="image" src="https://user-images.githubusercontent.com/3810177/181233910-1c0e5cbc-4d7a-4ba9-94f7-34c2d9f38c8b.png">

**Comment by antlionguard** [comment]
You can set autoimports only `false` or `true`.

**Comment by stephenjason89** [comment]
@antlionguard 
is this only applicable for nuxt 3?
<img width="757" alt="image" src="https://user-images.githubusercontent.com/3810177/181238034-728dc58a-5c46-4008-802c-fccceb54243c.png">

**Comment by antlionguard** [comment]
> @antlionguard is this only applicable for nuxt 3? <img alt="image" width="757" src="https://user-images.githubusercontent.com/3810177/181238034-728dc58a-5c46-4008-802c-fccceb54243c.png">

No but you using wrong. You need to put directly inside the defineConfig not the bridge object.

**Comment by stephenjason89** [comment]
@antlionguard Thank you for pointing it out. It works like a charm.
I would suggest however to group all autoImport related to that object.

so instead of
    // Auto import components (https://go.nuxtjs.dev/config-components)
    components: true,
we can maybe do it like 
    autoImports: {
        components: true,
        composables:{
            dirs: [
                // Scan composables from nested directories
                'composables/**',
            ]
        }
    },

**Comment by antlionguard** [comment]
> @antlionguard Thank you for pointing it out. It works like a charm. I would suggest however to group all autoImport related to that object.
> 
> so instead of
> 
> ```
>     // Auto import components (https://go.nuxtjs.dev/config-components)
>     components: true,
> ```
> 
> we can maybe do it like
> 
> ```
>     autoImports: {
>         components: true,
>         composables:{
>             dirs: [
>                 // Scan composables from nested directories
>                 'composables/**',
>             ]
>         }
>     },
> ```

I think it might too. You should open new discussion for this suggestion and you feel free closing this issue.

**Comment by stephenjason89** [comment]
@antlionguard I'm sorry,
i thought it was working
<img width="580" alt="image" src="https://user-images.githubusercontent.com/3810177/181254601-aa220aa8-cedd-4a86-9151-2f5ecbe1ddd5.png">
<img width="214" alt="image" src="https://user-images.githubusercontent.com/3810177/181254657-7df308b3-d165-4070-af98-d10764adbe9d.png">

**Comment by antlionguard** [comment]
This problem should have been resolved with #145 but i guess it still is. @danielroe

**Comment by danielroe** [comment]
Ah, yes. This was an upstream change in `unimport`. Please see [this migration guide](https://github.com/nuxt/framework/pull/6025). It is for Nuxt 3 but applies in this case.

**Comment by stephenjason89** [comment]
@danielroe ![image](https://user-images.githubusercontent.com/3810177/181486710-0a3e5834-7489-435c-82af-390672da702a.jpeg)

This works but only for named exports

Default exports doesn't work

**Comment by stephenjason89** [comment]
@danielroe 
<img width="358" alt="image" src="https://user-images.githubusercontent.com/3810177/181571150-1521b752-39c5-481f-9ea2-b0060367628c.png">

for non named exports(default)
should i do it like
export { default as useToast } from './utils/useToast'

**Comment by danielroe** [comment]
To be clear, `bridge.imports` (we've recently renamed it) should be set to true/false. Configuration is provided in a top-level `imports` key.
