### ISSUE TITLE
TypeError ExtractCss

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/bridge#448]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@3.2.1`
- Builder:          `webpack`
- User Config:      `buildDir`, `srcDir`, `bridge`, `ssr`, `dev`, `alias`, `image`, `generate`, `head`, `typescript`, `publicRuntimeConfig`, `privateRuntimeConfig`, `css`, `loading`, `loadingIndicator`, `plugins`, `components`, `buildModules`, `modules`, `proxy`, `axios`, `vuetify`, `build`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `@nuxtjs/vuetify@1.12.3`, `@nuxt/image@0.7.1`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/proxy@2.1.0`, `nuxt-social-meta@1.0.0`
- Build Modules:    `()`, `nuxt-storm@1.1.3`, `nuxt-compress@5.0.0`, `@pinia/nuxt@0.3.1`, `@nuxt/bridge@3.0.0-27639120.e7a7f9b`
------------------------------

### Reproduction

<img width="669" alt="image" src="https://user-images.githubusercontent.com/3810177/181613172-24e25422-a438-4a29-b997-e47b7f9d12fa.png">

### Describe the bug

TypeError when using an object.
Only boolean or undefined is accepted

**Comment by wattanx** [comment]
This issue was resolved at https://github.com/nuxt/bridge/pull/785
