### ISSUE TITLE
cross-request state pollution 

### ISSUE THREAD

**Issue by antlionguard** [nuxt/bridge#451]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.19.1`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@1.22.18`
- Builder:          `webpack`
- User Config:      `srcDir`, `alias`, `server`, `bridge`, 
`head`, `serverMiddleware`, `css`, `styleResources`, `plugins`, `buildModules`, `gtm`, `modules`, `postcss`, `tailwindcss`, `typescript`, `sentry`, `buefy`, `image`, `axios`, `proxy`, `render`, `i18n`, `router`, `build`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `@nuxt/image@0.6.2`, `@nuxtjs/sentry@5.1.7`, `nuxt-buefy@0.3.31`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/proxy@2.1.0`, `cookie-universal-nuxt@2.2.1`, `@nuxtjs/i18n@7.2.2`, `nuxt-sweetalert2@1.0.0`
- Build Modules:    `()`, `@pinia/nuxt@0.3.0`, `@nuxtjs/eslint-module@3.1.0`, `@nuxtjs/style-resources@1.2.1`, `@nuxtjs/gtm@2.4.0`, `@nuxtjs/tailwindcss@4.2.1`, `@nuxtjs/dotenv@1.4.1`, `@nuxt/bridge@3.0.0-27639120.e7a7f9b`
------------------------------

### Reproduction

I cannot reproduce because this situation happens very comlex code base.

### Describe the bug

Although cache-control: max-age=0, private is set in Response Header, nuxt caches this request and this response is returned to other users. Because of this, I am experiencing an info leak.

This only happening on ssr.

### Additional context

Our project running in docker and AWS.

**Comment by danielroe** [comment]
@antlionguard Would you provide a simple reproduction showing how a route ends up being cached? Have you enabled nitro caching on any routes?

**Comment by antlionguard** [comment]
> @antlionguard Would you provide a simple reproduction showing how a route ends up being cached? Have you enabled nitro caching on any routes?

I will try to create reproductions. And i don't use nitro. Nitro is set false in bridge config.

**Comment by danielroe** [comment]
If you are not using nitro then this is almost certainly not an issue with Bridge. But will happily look at reproduction just in case!

**Comment by antlionguard** [comment]
> If you are not using nitro then this is almost certainly not an issue with Bridge. But will happily look at reproduction just in case!

Oh probably there's completely different problem exist from pinia. Not related with "cache-control" header or axios, nitro etc.

I have a question. Pinia has any ssr caching mechanism? Do you know this? 

There's simple code example from my nuxt-bridge project.


Part of <script setup> inside Country Select Component (This component wrapped by <client-only>. That's an important point ):
```ts
...
// Country Fetch
const isFetching = ref(true);
const countryOptions = ref();
typeStore.fetchCountryList().then(() => {
  countryOptions.value = typeStore.countryList;
  isFetching.value = false;
});
...
```

countryList method inside typeStore(pinia): 
```ts
...
    async fetchCountryList() {
      try {
        if (isEmpty(this.countryList)) {
          const { data } = await this.$nuxt.$api.commonServicesV2.fetchCountryList();
          this.countryList = data.data;
        }
      } catch (error) {
           **********
      }
    },
...
```

When i refresh the page i cannot see in network tab ```commonServicesV2.fetchCountryList``` was called but countryList is filled. It seems like pinia states was stored on server side. That's very interesting to me. Or there is something I missed about pinia.

**Comment by danielroe** [comment]
Ah. Wrapping in `<client-only>` doesn't mean that those components don't load on the server - it only means that no HTML is emitted. They may all still run. So if you are initialising and filling a store there, it will be filled even though the HTML isn't rendered.

**Comment by antlionguard** [comment]
I'm facing a problem similar to 
https://github.com/aws-amplify/amplify-js/discussions/7611

And i added cache-control header and that's didn't work. I removed all ssr fetching for user information for temporarily until this problem is fixed. 

And again i'm trying to create minimal reproduction.

**Comment by antlionguard** [comment]
Oh that's not related with headers or caching. 

![image](https://user-images.githubusercontent.com/26603638/189124210-bcd5ccbd-69a9-45c9-902f-ee31e79adb1c.png)

The code i marked causing problem. If i try read cookie on ssr nuxt(or node idk) returns another user token if both users refresh same time. Any ideas for this? @danielroe am i missing something? Or is this method the wrong method?

**Comment by antlionguard** [comment]
> That sounds cross-request state pollution and I would investigate pinia in that case. It doesn't _sound_ like a Bridge issue.

https://vuejs.org/guide/scaling-up/ssr.html#cross-request-state-pollution 

There's some recommendations here but i couldn't figure out how to do in nuxt.

**Comment by danielroe** [comment]
It shouldn't be something you need to do. Both Nuxt + pinia should ensure this. Would you create a minimal reproduction so I can look into it further? :pray:

**Comment by antlionguard** [comment]
> It shouldn't be something you need to do. Both Nuxt + pinia should ensure this. Would you create a minimal reproduction so I can look into it further? 🙏

Here's the reproduction -> https://github.com/antlionguard/cross-request-state-pollution-pinia-nuxt

Reproduction steps: 

1. install deps. 
2. yarn build and yarn start (because this not happening on development)
3. open 2 browser (i tried with firefox and chrome)
4. press set token button in the browser on the right
5. and refresh left side browser and browser on the right asap

example image

![reproduction](https://user-images.githubusercontent.com/26603638/189142933-51454d83-aceb-43c0-8317-9e1f7b972470.png)

**Comment by danielroe** [comment]
The issue is that you are defining your state outside of the factory function:

```js
const InitialAuthState: AuthState = {
  token: '',
};

export const useAuthStore = defineStore('auth', {
  state: (): AuthState => InitialAuthState,
})
```

That is why it is shared.
