### ISSUE TITLE
Build error in bridge version "Could not load node-fetch in unenv" when use nuxi build 

### ISSUE THREAD

**Issue by 0xinhua** [nuxt/bridge#454]
### Environment

Nuxt project info:                                                                                           11:44:36

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.16.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@1.17.3`
- Builder:          `webpack`
- User Config:      `telemetry`, `hooks`, `mode`, `target`, `head`, `css`, `plugins`, `components`, `modules`, `build`, `srcDir`, `server`, `loading`, `render`, `publicRuntimeConfig`, `privateRuntimeConfig`, `proxy`, `serverMiddleware`, `router`, `serverHandlers`, `devServerHandlers`, `bridge`, `buildModules`
- Runtime Modules:  `@nuxtjs/proxy@2.1.0`, `@nuxt/http@0.5.13`, `@nuxtjs/device@1.2.7`, `@nuxtjs/svg@0.1.12`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27636329.42ea75b`

### Reproduction

when use nuxi build

### Describe the bug

use `nuxi build` to bundle for production env get the error as follow：
>  ERROR  Rollup error: Could not load /Users/M1seRy/workspace/bpro/pro-a/alpapro-a_web/node_modules/unenv/runtime/npm/node-fetch/lib/index.js.cjs: ENOENT: no such file or directory, open '/Users/M1seRy/workspace/bpro/pro-a/alpapro-a_web/node_modules/unenv/runtime/npm/node-fetch/lib/index.js.cjs'

I also add an issue in package unenv => https://github.com/unjs/unenv/issues/44

Need some helps and Thanks for your time.

**Comment by pi0** [comment]
Would you please provide a reproduction @M1seRy 🙏🏼

**Comment by M1seRy** [comment]
> Would you please provide a reproduction @M1seRy 🙏🏼
 
Thank you for your quick reply @pi0 。but It is difficult to prepare a online reproduction 😢 I'll update here if there's any progress.

**Comment by wattanx** [comment]
It has not responded for a while, so I am closing it.
Reopen is welcome.
