### ISSUE TITLE
Global middleware is not working

### ISSUE THREAD

**Issue by Tcharlyson** [nuxt/bridge#456]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.19.3`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@1.22.18`
- Builder:          `webpack`
- User Config:      `head`, `ssr`, `css`, `plugins`, `components`, `buildModules`, `modules`, `axios`, `dayjs`, `vuetify`, `publicRuntimeConfig`, `privateRuntimeConfig`, `storybook`, `i18n`, `build`, `router`, `serverHandlers`, `devServerHandlers`, `bridge`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `8n`, `@nuxtjs/dayjs@1.4.1`
- Build Modules:    `()`, `@nuxtjs/stylelint-module@4.1.0`, `@nuxtjs/vuetify@1.12.3`, `@pinia/nuxt@0.1.9`, `@nuxt/bridge@3.0.0-27657000.c87fdbe`
------------------------------

### Describe the bug

When you add a file as test.global.ts inside your middleware folder with a simple console.log('Hello World'). This last is not triggered at all. Same on RC6.

**Comment by danielroe** [comment]
This feature (and most other auto-scan features) is unique to Nuxt 3 and is not available on Nuxt Bridge.
