### ISSUE TITLE
`$config` doesn't work on client

### ISSUE THREAD

**Issue by danielroe** [nuxt/bridge#458]
In old format plugins with $config from context it still dont work on client. On server its there but on client its not which breaks a lot of modules that coudl work
https://codesandbox.io/s/immutable-fast-eypbmn?file=/plugins/plugin.js:0-33

_Originally posted by @aldarund in https://github.com/nuxt/bridge/issues/9#issuecomment-1176362021_

**Comment by aldarund** [comment]
@danielroe any news?
