### ISSUE TITLE
TypeError nuxtApp.nuxt2Context.app & nuxtState

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/bridge#465]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.7.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@3.2.1`
- Builder:          `webpack`
- User Config:      `buildDir`, `srcDir`, `target`, `bridge`, `components`, `ssr`, `dev`, `alias`, `image`, `generate`, `head`, `typescript`, `publicRuntimeConfig`, `privateRuntimeConfig`, `css`, `loading`, `loadingIndicator`, `plugins`, `buildModules`, `modules`, `proxy`, `axios`, `vuetify`, `build`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `cookie-universal-nuxt@2.2.1`, `@nuxtjs/vuetify@1.12.3`, `@nuxt/image@0.7.1`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/proxy@2.1.0`, `nuxt-social-meta@1.0.0`
- Build Modules:    `()`, `nuxt-storm@1.1.3`, `nuxt-compress@5.0.0`, `@pinia/nuxt@0.3.1`, `~/modules/apolloSSR`, `@nuxt/bridge@3.0.0-27639120.e7a7f9b`
------------------------------

### Reproduction

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/3810177/182958565-d84287ce-4c25-4fa5-8ec7-c1804841d43a.png">

<img width="517" alt="image" src="https://user-images.githubusercontent.com/3810177/182958648-fa88356b-1e79-4ace-91c8-32c51390f693.png">

<img width="516" alt="image" src="https://user-images.githubusercontent.com/3810177/182958743-b04c1f1a-e93c-43ce-9632-9130333d1d0c.png">

<img width="574" alt="image" src="https://user-images.githubusercontent.com/3810177/182958795-bb0b6848-3e69-4a31-bcdc-ae824e5ae953.png">

### Describe the bug

IDE errors

**Comment by wattanx** [comment]
The issue has been resolved in the following Pull Request:
https://github.com/nuxt/bridge/pull/749
