### ISSUE TITLE
String-based middleware is not resolved properly with Vite enabled

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt/bridge#468]
### Environment

See reproduction...

### Reproduction

https://stackblitz.com/edit/nuxt-bridge-test?file=nuxt.config.ts

### Describe the bug

When enabling Vite, string-based middleware is not resolved correctly. This is especially problematic because it blocks projects using the `auth module` from upgrading to Bridge and therefore from preparing/upgrading to v3.

If there is a possibility to fix this with a Vite configuration (alias or something like that) it would be great to add it to the migration guide.

🙏🏽

### Additional context

This problem does not occur when using Nuxt 2 + nuxt-vite or Nuxt Bridge without Vite.

**Comment by JerryKusenberger** [comment]
I'm also experiencing this. Is there a workaround?

**Comment by matthewfee** [comment]
Just adding that this is also a problem with upgrading our current project. Any advice on a workaround would be really appreciated.

**Comment by danielroe** [comment]
resolved in #797
