### ISSUE TITLE
cannot disable use nitro ?

### ISSUE THREAD

**Issue by Stvchm9703** [nuxt/bridge#486]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `target`, `ssr`, `mode`, `buildModules`, `modules`, `css`, `components`, `bridge`, `plugins`, `unocss`, `runtimeConfig`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `@pinia/nuxt@0.4.0`
- Build Modules:    `()`, `@unocss/nuxt@0.26.4`, `@vueuse/core/nuxt@7.7.1`, `@nuxt/bridge-edge@3.0.0-27672061.a645f7f`
------------------------------

### Reproduction

// simply clone from https://github.com/antfu/vitesse-nuxt-bridge
// and edit the config file to disable nitro

yarn build 
yarn start

### Describe the bug

I setup the nuxt config as the SSR, and I try to turn off nitro feature for other reason 

```
// nuxt.config.ts
export default defineNuxtConfig({
  target: 'server',
  ssr: true,
  mode: "universal",
//....
  components: true,
  bridge: {
    vite: true,
    nitro: false,
    nitroGenerator: false,
    capi: true,
  },

//....
})
```
,
so far, I try to run `yarn nuxi build && yarn nuxi start`  , and I got 
```
 ERROR  Cannot find nitro.json. Did you run nuxi build first? Search path:                                    02:56:39
 [
  'C:/Users/Steven Chm/project/centanet-v6/.output/nitro.json',
  'C:/Users/Steven Chm/project/centanet-v6/nitro.json'
]
```

while I also try `yarn nuxt build && yarn nuxt start`, and got :

```
 ERROR  bundle export should be a function when using { runInNewContext: false }.                             02:53:27

  at node_modules\vue-server-renderer\build.prod.js:1:77001
  at new Promise (<anonymous>)
  at node_modules\vue-server-renderer\build.prod.js:1:76851
  at Object.renderToString (node_modules\vue-server-renderer\build.prod.js:1:80049)
  at SSRRenderer.render (node_modules\@nuxt\vue-renderer-edge\dist\vue-renderer.js:239:38)
```

it seem to be  the Nuxi is not adapt to non-nitro server case, 

### Additional context

since the nitropack (node_modules\nitropack\dist\shared\nitro.mjs, function _build) during the rollup bundle using `symlink` and throw out `EISDIR`, 
somehow I sort out the issue is about ExFAT file system.

however, I cannot move the project to other drive.
and I just wonder at least the project can be turn off the nitro.

**Comment by torbenwilkening** [comment]
I was running into the same issue.
The problem is, your project is build without nitro, and then it tries to run it with nitro for some reason. Can you try running `yarn nuxt-start` ? That is how you can do it in nuxt2, the "old" way without nitro.

That fixed it for me, its still confusing why it tries starting nitro when its `nitro: false` in the config

**Comment by danielroe** [comment]
`nuxi start` is not compatible with a non-nitro project. If you are not building a nitro server, you should use `nuxt-start` directly.

**Comment by Stvchm9703** [comment]
I see, maybe I try it later. thanks for answering
