### ISSUE TITLE
Nuxt Bridge breaks on the client side

### ISSUE THREAD

**Issue by enkot** [nuxt/bridge#499]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Nuxt Bridge Version: `3.0.0-27690335.da95eff`
- Package Manager:  `pnpm@7.9.4`
- Builder:          `webpack`

### Reproduction

https://codesandbox.io/s/infallible-shamir-2gdft8?file=/pages/index.vue:18-29

### Describe the bug

Looks like Nuxt Bridge doesn't run any client side hooks. For example, `mounted` hook in the reproduction should show "test" in the console. It doesn't show it for Nuxt Bridge , but works fine for Nuxt 3.

**Comment by avinean** [comment]
The same shit.
It looks like JS even doesn't load to client side

<img width="773" alt="image" src="https://user-images.githubusercontent.com/22274408/187446037-139fe304-4094-4936-8ded-984248242e00.png">


- Operating System: `Darwin`
- Node Version:     `v18.6.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `pnpm@7.8.0`
- Builder:          `webpack`
