### ISSUE TITLE
Bridge with nuxt/content v1 & PNPM (export createHooks was not found)

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/bridge#506]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.7.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `unknown`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Create a nuxt-bridge project
"@nuxt/bridge": "npm:@nuxt/bridge-edge@3.0.0-27690335.da95eff",

then pnpm i @nuxt/content@^1 

pnpm dev

### Describe the bug

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/3810177/187790710-904976cc-acf8-440e-99c3-a26c0218df7e.png">

It is throwing this error after i run 

```pnpm i @nuxt/content@^1 ```
```pnpm dev```

.npmrc
```
shamefully-hoist=true
strict-peer-dependencies=false
```

**it seems to be working with Yarn2 so I temporarily changed my package manager to Yarn2 for now**

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/3810177/187792083-21b8b446-43e7-408d-9abf-0a4e92ce8c49.png">

This is not working for me
https://github.com/nuxt/bridge/issues/162#issuecomment-1097974386

_No response_

**Comment by AlexandrKlepikov** [comment]
> Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> 
> More info
I have the same problem. Here is a reproduction: https://stackblitz.com/edit/nuxt-bridge-pnpm
The error occurs in the file .nuxt/dev/index.mjs where is the import { createHooks } from hookable version 4 instead of version 5.

**Comment by stephenjason89** [comment]
Hello I'm using nuxt 3 now, this issue was opened a year ago. Please feel free to close it.

**Comment by wattanx** [comment]
Resolved at https://github.com/nuxt/bridge/pull/1086
It will be released in `3.1.0`.
(If you want to try it now, you can try `@nuxt/bridge-edge@3.0.1-28436495.f604cdf`.)

https://stackblitz.com/edit/github-wuyjgw-vr4sfq
