### ISSUE TITLE
Public RuntimeConfig is empty

### ISSUE THREAD

**Issue by joel-wenzel** [nuxt/bridge#508]
### Environment

Nuxt CLI v3.0.0-rc.8
RootDir: C:/code/test-nuxt-2
Nuxt project info: 

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`- Package Manager:  `npm@8.18.0`
- Builder:          `webpack`
- User Config:      `runtimeConfig`, `publicRuntimeConfig`, `ssr`, `target`, `head`, `css`, 
`plugins`, `components`, `buildModules`, `modules`, `axios`, `vuetify`, `build`, `serverHandlers`, `devServerHandlers`, `bridge`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`    
- Build Modules:    `()`, `@nuxtjs/vuetify@1.12.3`, `@nuxt/bridge@3.0.0-27699693.0bb392e`   
------------------------------

### Reproduction

`git clone https://github.com/joel-wenzel/nuxt-bridge-bug`
`npm i`
`npm run dev`

check console logs to see empty public runtime config - it comes from `plugins/test-config.ts`

### Describe the bug

Public runtime config doesn't appear to come through despite presence in nuxt.config.
I tried using both `runtimeConfig/public` and the deprecated `publicRuntimeConfig` but neither come through.

### Additional context

```
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      test: 'thing',
    },
  },
  publicRuntimeConfig: {
    test: 'thing',
  },
})
```

**Comment by danielroe** [comment]
... and let's track in https://github.com/nuxt/bridge/issues/311.
