### ISSUE TITLE
Errors after enabling vite

### ISSUE THREAD

**Issue by shmidtelson** [nuxt/bridge#509]
### Environment

Nuxt CLI v3.0.0-rc.8                                                                                                                                                                                    18:19:53
RootDir: /Users/roman.vzn/WebstormProjects/cms-front                                                                                                                                                    18:19:54
Nuxt project info:                                                                                                                                                                                      18:19:54

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `bridge`, `ssr`, `target`, `head`, `css`, `styleResources`, `plugins`, `components`, `buildModules`, `modules`, `axios`, `dayjs`, `i18n`, `publicRuntimeConfig`, `build`, `vuetify`, `googleFonts`, `loading`, `loadingIndicator`, `toast`, `generate`, `storybook`, `resolve`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `@nuxtjs/style-resources@1.2.1`, `@nuxtjs/toast@3.3.1`, `@nuxtjs/i18n@7.2.3`, `@nuxtjs/dayjs@1.4.1`, `@nuxtjs/axios@5.13.6`
- Build Modules:    `()`, `@nuxtjs/google-fonts@1.3.0`, `@nuxtjs/eslint-module@3.1.0`, `@nuxtjs/stylelint-module@4.1.0`, `@nuxtjs/vuetify@1.12.3`, `@nuxt/bridge@3.0.0-27672061.a645f7f`
------------------------------

### Reproduction

 nuxi dev

### Describe the bug

After start command (yarn dev) i got this errors
<img width="923" alt="image" src="https://user-images.githubusercontent.com/6944443/187951365-f2244096-2913-433e-a5f8-ce306cdd0510.png">

**Comment by nestle49** [comment]
Same error with npm

**Comment by Towerism** [comment]
@danielroe here is a minimal reproduction repo: https://github.com/Towerism/nuxt-bridge-vite-fails-imports

my team encountered this, and as a result we cannot enable vite. I was going to create an issue, but I noticed this issue first. I hope this reproduction repo helps!

**Comment by shmidtelson** [comment]
Close it pls. I really didnt find the time to send details
