### ISSUE TITLE
Hotmodule reloading does not work when router.base is set

### ISSUE THREAD

**Issue by Towerism** [nuxt/bridge#513]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@1.22.15`
- Builder:          `webpack`
- User Config:      `components`, `router`, `serverHandlers`, `devServerHandlers`, `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27700335.6dfc006`

### Reproduction

https://github.com/Towerism/nuxt-bridge-routerbase

### Describe the bug

When you set `router.base` in the nuxt config, hot module reloading does not work. Check the network tab and you'll see a 404 error when it tries to load `client.js`.

1. run `yarn dev`
2. make a change to `pages/index.vue`
3. notice that the change will not show up in the browser until you manually refresh the page.

### Additional context

Sorry, I tried using the codesandbox. But I kept getting the error message: `A sandbox error occurred, you can refresh the page to restart the container.`

**Comment by wattanx** [comment]
This problem seems to have been solved.
