### ISSUE TITLE
HMR does not work on pages/components with style block when vite is disabled

### ISSUE THREAD

**Issue by k-urtica** [nuxt/bridge#540]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `2.16.0-27720022.54e852f`
- Nitro Version:    `0.5.3`
- Package Manager:  `yarn@1.22.17`
- Builder:          `webpack`
- User Config:      `bridge`, `target`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `build`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27719991.c20d90e`
------------------------------

### Reproduction

This is the smallest project immediately after it was created with `create nuxt app` and migrated to bridge.
https://github.com/k-urtica/nuxt-bridge-test

1. `yarn dev`
2. change h1 tag string in index.vue

You can confirm that the changes are not reflected.

### Describe the bug

With vite disabled in nuxt.config and `<style></style>` block present, HMR does not work and changes are not reflected when pages or components are modified.

### Additional context

Oddly enough, the HMR seems to work correctly for pages or components without `<style></style>` blocks.
Also, when vite is enabled, HMR seems to work correctly with or without style block.

**Comment by wattanx** [comment]
Is this still occurring?
I have tried using the latest version and I have not been able to reproduce it.

https://stackblitz.com/edit/github-3fgb91-qrcccu

Also, as a temporary workaround, if you do not use `nitro` or `vite`, you can use the `nuxt` command instead of `nuxi`.
