### ISSUE TITLE
Please add a Stackblitz link for reproductions to this issue-template

### ISSUE THREAD

**Issue by HendrikJan** [nuxt/bridge#549]
### Environment

Github

### Reproduction

Start a new issue on https://github.com/nuxt/bridge and see that there is no link to a Stackblitz sandbox to create a reproduction.

### Describe the bug

Ths Codesandbox sandbox link does not start on my PC.
In nuxt/framework there is a Stackblitz sandbox link that does start on my PC.

Adding a Stackblitz link would make it easier for users to open an issue with a working reproduction.

**Comment by danielroe** [comment]
Thanks for the suggestion! ~> https://github.com/nuxt/bridge/commit/3bcd0e01aee8b793c735b8f8e5fdd974f7a58d6c
