### ISSUE TITLE
useRoute stopped working inside watch()

### ISSUE THREAD

**Issue by HendrikJan** [nuxt/bridge#550]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `2.15.8`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.11.0`
- Builder:          `webpack`
- User Config:      `rootDir`, `env`, `bridge`, `telemetry`, `nitro`, `head`, `publicRuntimeConfig`, `css`, `plugins`, `components`, `buildModules`, `vuetify`, `i18n`, `modules`, `compilerOptions`, `build`, `watchers`, `ssr`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `@nuxtjs/i18n@7.3.0`
- Build Modules:    `()`, `@nuxtjs/vuetify@1.12.3`, `@nuxtjs/dotenv@1.4.1`, `@nuxt/bridge@3.0.0-27729871.378ce3d`
------------------------------

### Reproduction

Reproduction of the issue:
https://jake.stackblitz.com/edit/nuxt-starter-6pzb8h?file=composables/useCount.js

Reproduction for the older version of nuxt/bridge where things were still working:
https://jake.stackblitz.com/edit/nuxt-starter-srzq3j?file=package.json

### Describe the bug

In version "^2.16.0-27616340.013f051b" of `nuxt-edge` you could use `useRoute()` inside a composable inside `watch()`,

```javascript [/composables/useCount.js]
watch(addUp, (newValue, oldValue) => {
    const r = useRoute();
    const c = r.query.count;
    count.value = parseInt(c) + addUp.value;
});
```

Now, in version "^2.16.0-27720022.54e852f, you get the following error in your browser console:
```
useRouter() must be called inside <script setup> or setup().
```

**Comment by HendrikJan** [comment]
I could not create a reproduction of the version that worked before -- so there is probably something else happening.

**Comment by danielroe** [comment]
This change in behaviour probably because we now re-export `useRouter` from `vue-router` rather than our own.

You will need to call `const router = useRouter()` outside of the watch function, and then use `router` within watch.
