### ISSUE TITLE
ERROR  Nitro is not initialized yet. You can call useNitro() only after ready hook.

### ISSUE THREAD

**Issue by antlionguard** [nuxt/bridge#566]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.17.6`
- Nuxt Version:     `2.16.0-27720022.54e852f`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.19.2`
- Builder:          `webpack`
- User Config:      `bridge`, `serverHandlers`, `devServerHandlers`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxt/bridge@0.10.1`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-nrsxrr?file=package.json,nuxt.config.ts

- yarn build

### Describe the bug

Build command fails with `ERROR  Nitro is not initialized yet. You can call useNitro() only after ready hook.` error. This bug occurred after rc.11. 

I just set `nitro: false`in nuxt config.

**Comment by antlionguard** [comment]
![image](https://user-images.githubusercontent.com/26603638/193859682-41fdff96-3a9f-47ec-b37a-9f3f1b11e9df.png)

**Comment by Draccano** [comment]
I am having the same issue declaring the nitro property in the bridge config.

**Comment by matthewfee** [comment]
I am also having this issue when attempting to run with Nitro set to false.

**Comment by marabesi** [comment]
I am trying to upgrade a nuxt app v2 using bridge and I am facing the same issue:

<img width="777" alt="image" src="https://github.com/nuxt/bridge/assets/2129872/b25ddd1b-a634-46c9-95d5-7313eab0e8d5">

nuxt.config.ts:

<img width="252" alt="image" src="https://github.com/nuxt/bridge/assets/2129872/5d6cd74e-6306-44eb-ab8b-3e76f20c9b55">

**Comment by danielroe** [comment]
@marabesi What version of Bridge are you using?
