### ISSUE TITLE
nuxt bridge not auto importing

### ISSUE THREAD

**Issue by Juicesus** [nuxt/bridge#568]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.12`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Trying to auto-import on nuxt bridge

### Describe the bug

Trying to add auto import from local module on nuxt-bridge like so:
```ts
addImportsSources([
      defineUnimportPreset({
        from: 'my-package',
        imports: ['usePackage']
      })
    ])
```

However 'usePackage' is not imported automatically, nor is it to be found in '#imports'
What might be happening?

### Additional context

I have my imports.autoImports on

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? :pray:

**Comment by Juicesus** [comment]
> Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? pray

https://stackblitz.com/edit/js-xs6blg?file=nuxt.config.ts

In this reproduction I tried addImports instead, and it seems to have no affect as well

**Comment by danielroe** [comment]
My apologies for the request; I've resolved in the latest edge release. Let me know if that doesn't fix it for you and I'll reopen.

**Comment by Juicesus** [comment]
Issue is still there for me, not sure if I'm doing something wrong. I reinstalled and updated my deps, still says function that's imported is undefined

**Comment by danielroe** [comment]
Seems to be working for me - would you check the version in your lockfile?

https://stackblitz.com/edit/github-drghuh?file=nuxt.config.ts,.nuxt%2Fimports.mjs

**Comment by Juicesus** [comment]
You are right, after deleting lockfile and running yarn again it works at runtime.
However I still get squiggly lines where I use auto-imported function, even if I'm extending auto-generated one from .nuxt

Is there anything I can do to please my IDE?

**Comment by danielroe** [comment]
First, make sure your tsconfig.json is set to extend from `./.nuxt/tsconfig.json`.

If you are using Webstorm you can follow these suggestions: https://github.com/nuxt/framework/issues/2320.

Otherwise, what is your IDE? And your tsconfig?

**Comment by Juicesus** [comment]
Yes, I was using WebStorm, and followed the steps in the linked issue

Now it all works, may god bless you, and thanks for amazing work on the technology 🙏🏻
