### ISSUE TITLE
SSR+data fetching+ bridge-meta option together stuck the app

### ISSUE THREAD

**Issue by MatthD** [nuxt/bridge#571]
### Environment

Nuxi 3.0.0-rc.11                                                                                                                     17:26:03
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `2.16.0-27720022.54e852f`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.11.0`
- Builder:          `webpack`
- User Config:      `bridge`, `ssr`, `alias`, `head`, `css`, `plugins`, `components`, `buildModules`, `tailwindcss`, `modules`, `basic`, `robots`, `sentry`, `gtm`, `runtimeConfig`, `auth`, `axios`, `build`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `@nuxtjs/auth-next@5.0.0-1648802546.c9880dc`, `@nuxtjs/sentry@5.1.7`, `@nuxtjs/i18n@7.2.3`, `@nuxtjs/gtm@2.4.0`, `@nuxtjs/robots@2.5.0`, `nuxt-basic-auth-module@1.4.1`, `@nuxtjs/axios@5.13.6`
- Build Modules:    `()`, `@nuxtjs/tailwindcss@4.2.1`, `nuxt-storm@1.1.3`, `@nuxt/bridge@3.0.0-27737014.fcf636d`

### Reproduction

`nuxt.config.ts`

```typescript
export default defineNuxtConfig({
  bridge: {
    meta: true,
  },
  // ssr: false, // the two option above seems not compatible :/ whe cannot have meta and ssr enabled
...
}
```

`pages/index.vue`

```vue
<template>
  <div v-if="page">
    <template v-for="(section, i) in page.sections">
      <!-- eslint-disable-next-line vue/require-component-is -->
      <component v-bind="section" :key="i" />
    </template>
  </div>
</template>

<script setup lang="ts">
import Page from "../types/page";

useHead({
  title: 'test'
})

const { data: page } = useLazyFetch<Page>('/api/v1/en-GB/page')
console.log('here')

</script>
```

### Describe the bug

While running the app in dev mod, in loop forever and we cannot access the index page.

- If I uncomment `ssr: false` in the config so that it disable it, **it correctly work and the page does not stuck**
- If I remove the fetch call and just use a variable data **it correctly work and the page does not stuck**
- If I remove `meta: true` in the config **it correctly work and the page does not stuck**

### Logs

```shell
There is no error logged , the app just stuck
```

**Comment by wattanx** [comment]
Are you still encountering this? Would you be able to provide a reproduction if so? 🙏
https://stackblitz.com/github/nuxt/starter/tree/v2-bridge
