### ISSUE TITLE
Nitro required for RC-11?

### ISSUE THREAD

**Issue by nmackey** [nuxt/bridge#576]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `2.16.0-27720022.54e852f`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@3.1.1`
- Builder:          `webpack`
- User Config:      `env`, `bridge`, `imports`, `alias`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `axios`, `build`, `publicRuntimeConfig`, `serverMiddleware`, `telemetry`, `ssr`, `sentry`, `ignore`, `vuetify`, `toast`, `router`, `redirect`, `proxy`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/proxy@2.1.0`, `@nuxtjs/toast@3.3.1`, `@nuxtjs/sentry@5.1.7`, `@nuxtjs/redirect-module@0.3.1`
- Build Modules:    `()`, `@nuxtjs/eslint-module@3.1.0`, `@nuxtjs/vuetify@1.12.3`, `@nuxtjs/svg@0.4.0`, `@nuxt/postcss8@1.1.3`, `@nuxt/bridge@3.0.0-27747000.69db93e`
------------------------------

### Reproduction

https://codesandbox.io/p/github/nmackey/nuxt-bridge-nitro-bug/v2-bridge-codesandbox?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A9%7D%5D&create=true&file=%2Fnuxt.config.js&workspace=%257B%2522activeFileId%2522%253A%2522cl8vsjnpt000qlqi9e2ue03op%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fnuxt.config.js%2522%252C%2522%252Fpackage.json%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cl8vsnpqg0012lqi9gsuvgdzw%2522%252C%2522key%2522%253A%2522cl8vsnpmp02y73b6h7torj1f5%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

### Describe the bug

Trying to upgrade from RC-8 to RC-11 and using bridge.

I have `nitro: false` set under `bridge` in my `nuxt.config.ts` b/c of this bug: https://github.com/nuxt/bridge/issues/20 (`ssr` is also false)

When doing a `nuxi build` I get the following error:

```
ERROR  Nitro is not initialized yet. You can call useNitro() only after ready hook.                                                                     10:13:31

  at useNitro (node_modules/@nuxt/kit/dist/index.mjs:210:11)
  at Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:40:29)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by antlionguard** [comment]
duplicate #566
