### ISSUE TITLE
meta tags should be at the end of the head

### ISSUE THREAD

**Issue by zhancheng** [nuxt/bridge#603]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `2.16.0-27720022.54e852f`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `buildModules`, `css`, `target`, `components`, `bridge`, `unocss`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@unocss/nuxt@0.26.4`, `@vueuse/core/nuxt@7.7.1`, `@nuxt/bridge-edge@3.0.0-27747000.69db93e`

### Reproduction

![image](https://user-images.githubusercontent.com/2122947/198927946-152ddff8-f96c-4f16-8e82-986f9abf1eae.png)

https://user-images.githubusercontent.com/2122947/198931188-e4d479da-291f-4b99-ad15-297124f7adb7.mp4

### Describe the bug

Because the declaration of the viewport does not appear at the front of the head but at the end, when the page is loaded on the mobile side, it is displayed in the style without the viewport. This is not a bug of nuxt2, I am not sure if it is a problem of nuxt bridge

config with ssr : false !!!

**Comment by wattanx** [comment]
Would you be able to provide a reproduction if so? 🙏
https://stackblitz.com/github/nuxt/starter/tree/v2-bridge
