### ISSUE TITLE
Updating to latest nuxt-bridge version breaks Webpack HMR

### ISSUE THREAD

**Issue by linhmtran168** [nuxt/bridge#607]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `2.16.0-27720022.54e852f`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `webpack`
- User Config:      `bridge`, `head`, `css`, `plugins`, `components`, `buildModules`, `build`, `serverHandlers`, `devServerHandlers`, `typescript`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxtjs/stylelint-module@4.1.0`, `@nuxt/bridge@3.0.0-27778503.de9e5c2`

### Reproduction

https://github.com/linhmtran168/test-nuxt-bridge

Just a clean `create-nuxt-app` updated to use latest `nuxt-bridge` version

### Describe the bug

Nuxt Bridge latest version: `@nuxt/bridge@3.0.0-27778503.de9e5c2` breaks webpack HMR with the following error in browser console:
```
GET http://localhost:3001/__webpack_hmr/client 404 (Not Found)
```

Downgrading to `3.0.0-27747000.69db93e` fixes the problem

**Comment by Draccano** [comment]
Me downgrading to bridge 3.0.0-27747000.69db93e did not help. Why is the bridge so useless. Many bugs, not stable.

**Comment by linhmtran168** [comment]
@Draccano Did you actually downgrade to `bridge 3.0.0-27747000.69db93e`?
It seems that there are problems with `Nuxi 3.0.0-rc.12`, and `bridge 3.0.0-27747000.69db93e` uses `Nuxi 3.0.0-rc.11` which doesn't have the problems.
Please check when running `npm run dev`, the version of Nuxi displayed is `3.0.0-rc.11`

**Comment by Draccano** [comment]
@linhmtran168 I use `nuxt bridge` together with the `nuxt-edge.` The `Nuxi 3.0.0-rc.11` is related to nuxt 3, no?

**Comment by linhmtran168** [comment]
@Draccano Yes.`nuxt-bridge` use `nuxi` for all command line operations.
For me, I fixed the `nuxt-bridge` version in `package.json` as follows and ran `npm install` again, then Webpack HRM worked normally
 ```
 @nuxt/bridge": "npm:@nuxt/bridge-edge@3.0.0-27747000.69db93e"
 ```

**Comment by Draccano** [comment]
I ran your version, together with `"nuxt-edge": "latest", and it showed 404 error :/

**Comment by mlbiche** [comment]
Same here 👍 I do confirm that `@nuxt/bridge-edge@3.0.0-27747000.69db93e` seems not to have the issue, but `@nuxt/bridge-edge@3.0.0-27778503.de9e5c2` does.

I could reproduce it from starter template:

```
npx nuxi init nuxt-bridge-app -t v2-bridge
```

**Comment by phoenix-ru** [comment]
Any progress on that?
@danielroe

**Comment by daniluk4000** [comment]
I've downgraded to 3.0.0-27747000.69db93e and now other bridge methods stopped working for me...

**Comment by mlbiche** [comment]
The issue still exists on `@nuxt/bridge-edge@3.0.0-27830071.32c4527`

**Comment by priverop** [comment]
Confirmed that it's still happening on 3.0.0-27846691.4aaf4eb. [Here it's a repo](https://github.com/priverop/color-mode) I created to reproduce the error.

**Comment by 604587986** [comment]
same in 3.0.0-27851925.695ddd7

**Comment by oemer-sellwerk** [comment]
This issue still persists. Using an old version works, as described earlier:
```
// works
@nuxt/bridge": "npm:@nuxt/bridge-edge@3.0.0-27747000.69db93e"
// doesn't work
@nuxt/bridge": "npm:@nuxt/bridge-edge@latest"
```

**Comment by oemer-sellwerk** [comment]
> To use Webpack HMR with latest `nuxt-bridge`, you can patch `@nuxt/webpack-edge` package by using npm's `patch-package` package or pnpm. New versions of Nitro require node middleware to be converted to `h3` handler and the hook for running middleware also changed. The following patch works for me:
> 
> ```diff
> diff --git a/node_modules/@nuxt/webpack-edge/dist/webpack.js b/node_modules/@nuxt/webpack-edge/dist/webpack.js
> index ebe49a8..290907d 100644
> --- a/node_modules/@nuxt/webpack-edge/dist/webpack.js
> +++ b/node_modules/@nuxt/webpack-edge/dist/webpack.js
> @@ -41,6 +41,7 @@ const createResolver = require('postcss-import-resolver');
>  const Watchpack = require('watchpack');
>  const objectToMap = require('webpack/lib/util/objectToMap');
>  const nodeExternals = require('webpack-node-externals');
> +const h3 = require('h3')
>  
>  function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }
>  
> @@ -1929,6 +1930,7 @@ class WebpackBundler {
>        });
>        await nuxt.callHook("build:resources", this.mfs);
>      });
> +
>      if (options.dev) {
>        if (["client", "modern"].includes(name)) {
>          return new Promise((resolve, reject) => {
> @@ -1992,7 +1994,7 @@ class WebpackBundler {
>          }
>        )
>      );
> -    await this.buildContext.nuxt.callHook("server:devMiddleware", this.middleware);
> +    await this.buildContext.nuxt.callHook("server:devHandler", h3.fromNodeMiddleware(this.middleware));
>    }
>    async middleware(req, res, next) {
>      const name = utilsEdge.isModernRequest(req, this.buildContext.options.modern) ? "modern" : "client";
> ```

This also fixed HMR for me. I am using yarn and this worked for me:
```bash
yarn patch @nuxt/webpack-edge
```

Then just do what the command line prompts. Open the file, change it and then commit the patch. It should look something like this:
```bash
yarn patch-commit -s /private/var/folders/jg/5g_62ljn0dz2y1x3bnd9q31r0000gn/T/xfs-5730634f/user
```

**Comment by sreuss** [comment]
Instead of patching `node_modules` you can also do the conversion within the `ready` hook in your `nuxt.config.ts`:

```typescript
import { fromNodeMiddleware, type NodeMiddleware } from 'h3';

export default defineNuxtConfig({
  hooks: {
    ready(nuxt) {
      // https://github.com/nuxt/bridge/issues/607
      // translate nuxt 2 hook from @nuxt/webpack-edge to nuxt bridge hook
      nuxt.hook('server:devMiddleware' as any, async (devMiddleware: NodeMiddleware) => {
        await nuxt.callHook('server:devHandler', fromNodeMiddleware(devMiddleware));
      });
    },
  },
});
```

**Comment by psahni** [comment]
@sreuss 
Great Job!

**Comment by Suniron** [comment]
@sreuss you fixed this problem 
![image](https://user-images.githubusercontent.com/36677774/228782181-aa53ab1f-0225-4398-a702-cc2ea8ce2652.png)

And the hot reload in my nuxt bridge project <3

These problems was with the packages versions bellow (pnpm)
![image](https://user-images.githubusercontent.com/36677774/228782416-089b1d5d-fb05-42d1-acb7-b0d68c7f3743.png)

**Comment by katerynagulyaeva** [comment]
@sreuss Thanks a lot! Finally, it works

For those who are not using typescript: 

`import { fromNodeMiddleware } from 'h3';

export default defineNuxtConfig({
  hooks: {
    ready (nuxt) {
      // https://github.com/nuxt/bridge/issues/607
      // translate nuxt 2 hook from @nuxt/webpack-edge to nuxt bridge hook
      nuxt.hook('server:devMiddleware', async (devMiddleware) => {
        await nuxt.callHook('server:devHandler', fromNodeMiddleware(devMiddleware));
      });
    },
  },
});`

**Comment by Suniron** [comment]
But after coding few hours with this workaround, i constated that my web app crash sometimes.
I had to kill the server and run the `dev` command again.

I haven't any error

**Comment by wtagain** [comment]
> ```ts
> NodeMiddleware
> ```

It works!
Can you fix this issue at the next version?
@danielroe

**Comment by danielroe** [comment]
Absolutely! A PR would be very welcome 🙏

**Comment by bradley-varol** [comment]
I have this issue currently with the latest version of bridge. 

```
webpackHotUpdate("app", {

    /***/
    "./assets/scss/tailwind.css": /*!**********************************!*\
  !*** ./assets/scss/tailwind.css ***!
  \**********************************/
    /*! no static exports found */
    /***/
 ```

```
