### ISSUE TITLE
How to to jest test inside nuxt-bridge

### ISSUE THREAD

**Issue by MatthD** [nuxt/bridge#610]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `2.16.0-27720022.54e852f`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.11.0`
- Builder:          `webpack`
- User Config:      `alias`, `head`, `css`, `plugins`, `components`, `buildModules`, `tailwindcss`, `modules`, `basic`, `robots`, `sentry`, `i18n`, `gtm`, `runtimeConfig`, `auth`, `axios`, `build`, `serverHandlers`, `devServerHandlers`, `bridge`
- Runtime Modules:  `@nuxtjs/sentry@5.1.7`, `@nuxtjs/i18n@7.3.0`, `@nuxtjs/gtm@2.4.0`, `@nuxtjs/robots@2.5.0`, `nuxt-basic-auth-module@1.4.1`
- Build Modules:    `()`, `@nuxtjs/tailwindcss@4.2.1`, `nuxt-storm@1.1.3`, `@nuxt/bridge@3.0.0-27747000.69db93e`
------------------------------

### `composables/config.ts`

```typescript
type Config = {
  categories: string[];
  featureFlags: string[];
  languages: string[];
};

const config = reactive<Config>({
  categories: [],
  featureFlags: [],
  languages: [],
});
export const useConfig = () => {
  $fetch<Config>('/url')
    .then(({ categories }) => {
      config.categories = categories;
    })
    .catch(console.error);
  return config;
};
```

### `config.spec.ts`

```typescript
import { mount } from '@vue/test-utils';
import flushPromises from 'flush-promises';
import { useConfig } from './config'; //importing the composable

const mockedGetConfig = {
  categories: ['first'],
  featureFlags: ['header', 'footer'],
  languages: ['fr'],
};

describe('Config', () => {
  afterEach(() => {
    jest.resetAllMocks();
  });
  it('Should return config from hook when called', async () => {
    const Comp = {
      template: `<div>Fake component {{config}}</div>`,
      setup() {
        const config = useConfig();
        return { config };
      },
    };
    const wrapper = mount(Comp);
    await flushPromises();
    expect(wrapper.vm.config).toStrictEqual({
      categories: ['first'],
      featureFlags: ['header', 'footer'],
      languages: ['fr'],
    });
  });
});
```
### The error

<img width="627" alt="Capture d’écran 2022-11-03 à 14 27 14" src="https://user-images.githubusercontent.com/7901366/199733045-6fdbd8ff-a962-4180-a63a-82f184f001aa.png">

### Describe the bug

Jest failed to execute test when auto import composables of nuxt are used

Trying to test a composables that use  `reactive` auto-import lead to ` ReferenceError: reactive is not defined` 
I tried to install `@nuxt/test-utils` but it's not compatible with nuxt-bridge.

What is the way to do unit testing on nuxt-bridge with auto import inside ?

**Comment by antlionguard** [comment]
can you share small reproduction?

**Comment by MatthD** [comment]
Yes sure (will add it to the reproduction inside the desc)

### `composables/config.ts`

```typescript
type Config = {
  categories: string[];
  featureFlags: string[];
  languages: string[];
};

const config = reactive<Config>({
  categories: [],
  featureFlags: [],
  languages: [],
});
export const useConfig = () => {
  $fetch<Config>('/url')
    .then(({ categories }) => {
      config.categories = categories;
    })
    .catch(console.error);
  return config;
};
```

### `config.spec.ts`

```typescript
import { mount } from '@vue/test-utils';
import flushPromises from 'flush-promises';
import { useConfig } from './config'; //importing the composable

const mockedGetConfig = {
  categories: ['first'],
  featureFlags: ['header', 'footer'],
  languages: ['fr'],
};

describe('Config', () => {
  afterEach(() => {
    jest.resetAllMocks();
  });
  it('Should return config from hook when called', async () => {
    const Comp = {
      template: `<div>Fake component {{config}}</div>`,
      setup() {
        const config = useConfig();
        return { config };
      },
    };
    const wrapper = mount(Comp);
    await flushPromises();
    expect(wrapper.vm.config).toStrictEqual({
      categories: ['first'],
      featureFlags: ['header', 'footer'],
      languages: ['en', 'fr', 'de', 'es', 'nl', 'it', 'sv', 'da', 'fi', 'pt'],
    });
  });
});
```
### The error

<img width="627" alt="Capture d’écran 2022-11-03 à 14 27 14" src="https://user-images.githubusercontent.com/7901366/199733045-6fdbd8ff-a962-4180-a63a-82f184f001aa.png">

**Comment by wattanx** [comment]
I believe there's no way to solve Auto Import with Jest.
It's not impossible if you do something like this:

```
// jest.setup.ts
import * as vue from 'vue';
for (const key of Object.keys(vue)) {
  global[key] = vue[key];
}
```

However, personally, I think it would be better to use https://github.com/antfu/unplugin-auto-import with Vitest.

**Comment by wattanx** [comment]
It will be closed as there is no reaction for some time.
You can open it again if you have bugs or questions.
