### ISSUE TITLE
Missing type import nuxi auto generated components.d.ts

### ISSUE THREAD

**Issue by serialine** [nuxt/bridge#622]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `2.16.0-27720022.54e852f`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `webpack`
- User Config:      `components`, `serverHandlers`, `devServerHandlers`, `typescript`, `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxt/bridge@0.10.1`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-kkjxpz?file=.nuxt/nuxt.d.ts

### Describe the bug

`.nuxt/nuxt.d.ts` missing reference auto generated imports dts `.nuxt/components.d.ts`

expected

```
/// <reference path="components.d.ts" />
```

generated `.nuxt/nuxt.d.ts`

```
// Generated by nuxi
/// <reference types="@nuxt/bridge" />
/// <reference types="@nuxt/components" />
/// <reference types="@nuxt/telemetry" />
/// <reference path="types/components.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/nitro.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="imports.d.ts" />

export {}
```

**Comment by danielroe** [comment]
should be resolved in latest edge release via https://github.com/nuxt/bridge/pull/758
