### ISSUE TITLE
SSR context request headers lost on error page

### ISSUE THREAD

**Issue by IlyaSemenov** [nuxt/bridge#631]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `2.16.0-27720022.54e852f`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `serverHandlers`, `devServerHandlers`, `typescript`, `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27778503.de9e5c2`

### Reproduction

https://github.com/IlyaSemenov/nuxt-error-page-lost-headers

### Describe the bug

When I access http request headers with `ssrContext?.req.headers` on the error page (`layouts/error.vue`) all the headers are missing except of the fake `{ "host": "localhost" }` header (which always shows `localhost` regardless of the actual host being accessed).

This is not happening on "normal" pages.

### Additional context

This makes it impossible to perform host-based customization.

**Comment by IlyaSemenov** [comment]
This quick patch helps to a certain extent:

```
diff --git a/dist/runtime/nitro/error.mjs b/dist/runtime/nitro/error.mjs
index 2084803cb7fc5d827ffe0737c14019d03f2a2bb6..aa4f68d56ea628daae7e16f46da43435795a16ba 100644
--- a/dist/runtime/nitro/error.mjs
+++ b/dist/runtime/nitro/error.mjs
@@ -21,7 +21,7 @@ export default (async function errorhandler(_error, event) {
     return;
   }
   const url = withQuery("/__nuxt_error", errorObject);
-  const html = await $fetch(url).catch((error) => {
+  const html = await $fetch(url, { headers: event.req.headers }).catch((error) => {
     console.error("[nitro] Error while generating error response", error);
     return errorObject.statusMessage;
   });
```

although it'd be better to pass the original `req.rawHeaders` just in case, and possibly pass the original IP somehow.

**Comment by danielroe** [comment]
Yes, this is resolved in Nuxt 3 upstream and we need to port the fix to bridge.
