### ISSUE TITLE
@nuxt/bridge breaks nuxt v2.16.0 due to postcss8

### ISSUE THREAD

**Issue by robinscholz** [nuxt/bridge#701]
### Environment

Nuxi 3.0.0                                                                                                                                      16:22:17
                                                                                                                                                16:22:17
RootDir: /Users/robinscholz/Repositories/@intmagic/thenightleague/packages/frontend/hiibiza                                                     16:22:17
Nuxt project info: (copied to clipboard)                                                                                                        16:22:17

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.18.1`
- Nuxt Version:     `2.16.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `head`, `ssr`, `runtimeConfig`, `components`, `css`, `bridge`, `build`, `buildModules`, `modules`, `plugins`, `serverMiddleware`, `gtm`, `serverHandlers`, `devServerHandlers`, `devServer`, `typescript`
- Runtime Modules:  `@nuxtjs/i18n@7.3.1`, `portal-vue/nuxt`, `@nuxtjs/gtm@2.4.0`
- Build Modules:    `()`, `@nuxtjs/svg@0.4.0`, `@nuxt/bridge@3.0.0-27909973.a4c5d19`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                                16:22:17

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

…

### Describe the bug

Running this module together with the `nuxt@2.16.0` throws the following error:

```
Module build failed (from /Users/robinscholz/Repositories/@intmagic/thenightleague/node_modules/postcss-loader/dist/cjs.js):    friendly-errors 16:15:10
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'plugins'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap?, implementation? }
    at validate (/Users/robinscholz/Repositories/@intmagic/thenightleague/node_modules/schema-utils/dist/validate.js:105:11)
    at Object.loader (/Users/robinscholz/Repositories/@intmagic/thenightleague/node_modules/postcss-loader/dist/index.js:43:29)
``` 

This is due to bridge requiring `@nuxt/postcss8`, if not explicitly disabled. 

I think the default for bridge should be to disable the settings for postcss8, now that 2.16.0 of nuxt is released.

**Comment by robinscholz** [comment]
https://github.com/nuxt/bridge/blob/ddd8eccdcba58c61cc335a64acbc99fbf446b295/packages/bridge/src/module.ts#L94

This is the block that breaks things

**Comment by manniL** [comment]
As a workaround, you can set `postcss8` to `false` via module options ☺️
