### ISSUE TITLE
getting the 'Expected a JavaScript module script but the server responded with a MIME type of "text/html"' error on monorepo

### ISSUE THREAD

**Issue by tassioFront** [nuxt/bridge#714]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `2.16.2`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.4`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
- Nx
- Monorepo

### Reproduction

[codesandbox link](https://codesandbox.io/p/github/tassioFront/issue-nuxt-bridge-nx/main?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A15%2C%22endLineNumber%22%3A6%2C%22startColumn%22%3A15%2C%22startLineNumber%22%3A6%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522clf4lswrk001fg1gohieh9tvl%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fpackage.json%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clf4lszw600113b6jeqyrp7px%2522%253A%257B%2522key%2522%253A%2522clf4lszw600113b6jeqyrp7px%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%255D%257D%252C%2522clf4lx1ja00hz3b6jo3xywxnw%2522%253A%257B%2522key%2522%253A%2522clf4lx1ja00hz3b6jo3xywxnw%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A8000%252C%2522key%2522%253A%2522clf4lzv2q008o3b6jhvyx7tse%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522clf4lzrzg007b3b6jujrf6yog%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522key%2522%253A%2522clf4lzrjf00193b6jnzl6s1rh%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Atrue%257D%255D%252C%2522name%2522%253A%2522start%2522%257D%257D%252C%2522currentSpace%2522%253A%2522clf4lx1ja00hz3b6jo3xywxnw%2522%252C%2522spacesOrder%2522%253A%255B%2522clf4lszw600113b6jeqyrp7px%2522%252C%2522clf4lx1ja00hz3b6jo3xywxnw%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

You can also find the [origin repository here](https://github.com/tassioFront/issue-nuxt-bridge-nx)

### Describe the bug

We use Nuxt 2.15.7 with [Nx](https://nx.dev/) where I work and everything has been working great. Recently, we decided to work with Vite also.

To do so, we followed the [Migration guide to use Nuxt Bridge](https://nuxt.com/docs/bridge/overview#overview), but when I tried to run the project locally (by `nuxi dev`)  we got an error and we just see a white page:
![186f8f5082c3dfd61437818769a78b63](https://user-images.githubusercontent.com/47509510/224516756-4443d0c5-0df5-4daf-ade4-55c5dde2797e.gif)

I tried to follow [this issue](https://github.com/nuxt/nuxt/issues/14485), but it is not clear to me what I need to do. 

### Logs

```shell
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**Comment by adityatejas562** [comment]
how did you resolved this issue?
