### ISSUE TITLE
Modifying pages causes dev server restart (when use router.extendRoutes option)

### ISSUE THREAD

**Issue by serialine** [nuxt/bridge#717]
### Environment

Nuxi 3.1.2                                                                                                                                                    16:59:31
                                                                                                                                                              16:59:32
RootDir: /home/projects/github-dwx287                                                                                                                         16:59:32
Nuxt project info:                                                                                                                                            16:59:32

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `2.16.3-27980660.7576a98`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `webpack`
- User Config:      `router`, `build`, `serverHandlers`, `devServerHandlers`, `devServer`, `typescript`, `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxt/bridge@0.10.1`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-dwx287?file=pages/index.vue

### Describe the bug

1. add `router.extendRoutes` option and run devserver

nuxt.config.ts
```ts
import { defineNuxtConfig } from '@nuxt/bridge';

export default defineNuxtConfig({
  router: {
    extendRoutes(routes, resolve) {
      routes.push({
        path: '/contact/*',
        redirect: { path: '/', hash: '#contact' },
      });
    },
  },
});
```

2. edit `pages/*.vue` to trigger hmr

3. it causes restart dev server

```
ℹ Pages enabled. Restarting nuxt...                                                                                                                           
ℹ Preparing project for development  
...
```

### Additional context

workaround add `pages: true` option

**Comment by wattanx** [comment]
It seems that this issue does not occur in the latest version.
https://stackblitz.com/edit/github-dwx287-jqhdvt
