### ISSUE TITLE
Missing BODY_PREPEND placeholder in app template

### ISSUE THREAD

**Issue by dwightjack** [nuxt/bridge#722]
In the [renderer](https://github.com/nuxt/bridge/blob/b4b2daca16ff531edf65e4c5db150477d1bf6637/packages/bridge/src/runtime/nitro/renderer.ts#L235), the `htmlContext.bodyPreprend` array is assigned to the `BODY_PREPEND` property placeholder in the app template (`.nuxt/views/document.template.mjs`) but the template (and `.nuxt/views/app.template.html` as well), does not contain that placeholder.

I can submit a PR to fix this issue, but I'd like to know what's your opinion on the best solution:

1. add the `BODY_PREPEND` to the app template (not sure where it is stored)
2. prepend the contents to APP like we already do for the `bodyAppend` property:
```diff
- BODY_PREPEND: joinTags(htmlContext.bodyPreprend),
- APP: _rendered.html + joinTags(htmlContext.bodyAppend)
+ APP: joinTags(htmlContext.bodyPreprend) + _rendered.html + joinTags(htmlContext.bodyAppend)
```

**Comment by danielroe** [comment]
The pattern to follow here is the renderer from https://github.com/nuxt/nuxt.

https://github.com/nuxt/nuxt/blob/4671294229fb8574a36778c09a6c54cb87445dee/packages/nuxt/src/core/runtime/nitro/renderer.ts#L376-L382

The document template is generated from the Nuxt 2 template here:

https://github.com/nuxt/bridge/blob/ddd8eccdcba58c61cc335a64acbc99fbf446b295/packages/bridge/src/nitro.ts#L488-L500

We may need to update this somewhat to align better with Nuxt 3, so this may be a tricky PR, but it would definitely be welcome.

**Comment by dwightjack** [comment]
@danielroe Thanks

A couple of questions to better understand what needs to be done:
1. Could it be useful to keep the old template rendering function when `nuxt.options.appTemplatePath` is defined? If I understand it correctly `nuxt.options.appTemplatePath` is a Nuxt2-only feature and is not available in Nuxt3. If so the only change is to add the `htmlContext.bodyPreprend` to the `APP` placeholder (and maybe fix the `bodyPreprend` typo like we already did in Nuxt3)
2. By default (ie: when `nuxt.options.appTemplatePath` is not defined) port the rendering template of Nuxt3 to Nuxt bridge.

What do you think?
