### ISSUE TITLE
asyncData return value is not synchronized with setup return value

### ISSUE THREAD

**Issue by yinfoyuan** [nuxt/bridge#728]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `2.16.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `webpack`
- User Config:      `serverHandlers`, `devServerHandlers`, `devServer`, `typescript`, `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27998567.a12a710`

### Reproduction

https://stackblitz.com/edit/nuxt-bridge-windicss-whkkt8?file=pages/index.vue

### Describe the bug

Click Refresh data on the client
Is this usage limitation?  Or you can only use computed to differentiate the client data from the server data

**Comment by wattanx** [comment]
As this also occurs with Nuxt 2 x `@nuxtjs/composition-api`, I don't think it's an issue with Nuxt Bridge.
https://stackblitz.com/edit/github-u5vanu?file=pages%2Findex.vue

I believe that when there are properties with the same name in both asyncData and setup, the `asyncData` and `data` options are prioritized.
