### ISSUE TITLE
Auto imported components are not typed

### ISSUE THREAD

**Issue by Suniron** [nuxt/bridge#756]
### Environment

- Nuxi: 3.4.2
- Operating System: Linux
- Node Version:     v18.14.0
- Nuxt Version:     3.4.0
- Nitro Version:    2.3.3
- Package Manager:  pnpm@7.27.0
- Builder:          vite
- User Config:      build, css, head, components, loading, modules, plugins, runtimeConfig, ssr, telemetry, typescript, vuetify, serverHandlers, devServerHandlers, devServer, bridge, buildModules
- Runtime Modules:  @nuxtjs/axios@5.13.6, @nuxtjs/i18n@7.3.1, @nuxtjs/vuetify@1.12.3, @pinia/nuxt@0.4.9
- Build Modules:    (), @nuxt/bridge@3.0.0-28039463.3e234e3

### Reproduction

I add this line in my `nuxt.config.ts`:

```ts
components: true,
```

### Describe the bug

After this, auto-imports works in the app but not the typing (it's always `any` on all auto imported components)

**Comment by Suniron** [comment]
> Are you using Bridge or Nuxt 3? Do you have Volar installed?

I'm using Volar and also volar as ts server.

Also, I have a Nuxt 3 Project where the typing is OK. 

But, here, my problem is in a Nuxt Bridge project

**Comment by danielroe** [comment]
this should be resolved in latest edge release via https://github.com/nuxt/bridge/pull/758
