### ISSUE TITLE
"Nuxt instance is unavailable!" crash when bridge: false

### ISSUE THREAD

**Issue by strokirk** [nuxt/bridge#774]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.19.1`
- Nuxt Version:     `2.16.3`
- Nitro Version:    `2.4.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `app`, `server`, `ssr`, `target`, `quiet`, `head`, `components`, `loading`, `css`, `router`, `plugins`, `buildModules`, `routerExtras`, `googleFonts`, `modules`, `bootstrapVue`, `gtm`, `axios`, `sentry`, `proxy`, `alias`, `vue`, `build`, `serverHandlers`, `devServerHandlers`, `devServer`, `typescript`, `nitro`, `bridge`
- Runtime Modules:  `@nuxtjs/gtm@2.4.0`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/proxy@1.3.3`, `vue-social-sharing/nuxt`, `vue-scrollto/nuxt`, `bootstrap-vue/nuxt`, `portal-vue/nuxt`
- Build Modules:    `()`, `@nuxtjs/google-fonts@2.0.0`, `@nuxtjs/router-extras@1.1.1`, `@storyblok/nuxt-2/module@1.2.3`, `unplugin-icons/nuxt`, `@nuxt/bridge@3.0.0-28058116.064ab77`

### Reproduction

Having `bridge: false` in `defineNuxtConfig`.

### Describe the bug

This gives a very unclear error message, that can take a while to figure out:

```
 ERROR  Nuxt instance is unavailable!
  at useNuxt (node_modules/@nuxt/kit/dist/index.mjs:32:11)
  at useNitro (node_modules/@nuxt/kit/dist/index.mjs:881:16)
  at Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:48:29)
  at async Object.invoke (node_modules/nuxi/dist/chunks/generate.mjs:35:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:48:20)
```

**Comment by wattanx** [comment]
Are you still encountering this? Would you be able to provide a reproduction if so? 🙏
https://stackblitz.com/github/nuxt/starter/tree/v2-bridge

**Comment by wattanx** [comment]
Are you still encountering this?
Let me know if not. I'm happy to reopen.

**Comment by strokirk** [comment]
Yes, this is still ”relevant”. As alluded to in the report, the source of the error is when you do a configuration mistake, but the error message is quite unclear when that situation happens.

**Comment by wattanx** [comment]
I agree that the error message is difficult to understand.
If we know under what circumstances this error occurs, it would be helpful in improving the situation.
(`Having bridge: false in defineNuxtConfig.` alone does not generate the error, so I cannot investigate further.)

**Comment by strokirk** [comment]
@wattanx Interesting, when I follow the link you shared and replace set `bridge: false`, I still get a startup crash (not the exact same one as in my original post, but still):

<img width="684" alt="image" src="https://github.com/nuxt/bridge/assets/1257824/4f8f340e-3c17-4c43-a82a-73181cc63bed">

I'll see if I can make a small repro of the `useNitro->useNuxt` error as well.

**Comment by wattanx** [comment]
I think I may have found the cause.
Are you using the `nuxi` command even with `bridge: false`?
If `bridge: false`, you need to use the `nuxt` command. (e.g. `nuxt dev`)
