### ISSUE TITLE
vueuse don't auto import anymore

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt/bridge#81]
### Environment

Nuxt project info:                                                                                                                                                                                                  

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.18`
- Builder:          `webpack`
- User Config:      `ssr`, `buildModules`, `bridge`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/core/nuxt@7.7.1`, `@nuxt/bridge@3.0.0-27467056.93c4dfe`
------------------------------

### Reproduction

reproduction: https://codesandbox.io/s/nuxt-bug-report-n8j1hv?file=/pages/index.vue

### Describe the bug

vueuse don't auto import anymore

**Comment by projct1** [comment]
Autoimports still not working :"(
Without `import { useDebounceFn } from '@vueuse/core'` got error: `500 useDebounceFn is not defined` =\
```vue
<script setup lang="ts">
const search = useDebounceFn(async q => {
    //some code
}, 500)
</script>
```
