### ISSUE TITLE
Using addRouteMiddleware results in blank page, error in console

### ISSUE THREAD

**Issue by Towerism** [nuxt/bridge#826]
### Environment

```
Nuxi 3.5.3

RootDir: /Users/martin.fracker/source/other/nuxt-bridge-routerbase
Nuxt project info: (copied to clipboard)

------------------------------
- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     2.16.3
- Nitro Version:    2.5.1
- Package Manager:  yarn@1.22.19
- Builder:          webpack
- User Config:      components, ssr, plugins, build, serverHandlers, devServerHandlers, devServer, typescript, nitro, bridge, buildModules
- Runtime Modules:  -
- Build Modules:    (), @nuxt/bridge@3.0.0-28122276.3c2e715
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com
```

### Reproduction

https://github.com/Towerism/nuxt-bridge-routerbase/tree/latest-nuxtbridge-814-issue

### Describe the bug

1. start with empty nuxt bridge project; or start with the reproduction repo, run yarn, and skip to step 4
2. add a plugin using defineNuxtPlugin
3. use addRouteMiddleware within the plugin
4. run yarn dev
5. observe a white screen with error in the console

### Additional context

3.0.0-28109745.a6e6787 is the last version of nuxt bridge that works. That is the most recent version that doesn't include #814 which is the PR that introduced this bug.

### Logs

From the console within chrome:

```shell
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting '_processingMiddleware')
    at _callee$ (composables.mjs:126:40)
    at tryCatch (runtime.js:64:15)
    at Generator.invoke (runtime.js:299:1)
    at Generator.eval [as next] (runtime.js:124:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at eval (asyncToGenerator.js:32:1)
    at new Promise (<anonymous>)
    at eval (asyncToGenerator.js:21:1)
    at eval (composables.mjs:136:4)
```

**Comment by wattanx** [comment]
Nuxt Bridge does not support the use of `defineNuxtRouteMiddleware` outside of the middleware directory.
(What has worked so far is not what we expected.)

For example, addRouteMiddleware in the reproduction is intended to be used as follows
```diff
- const authMiddleware = defineNuxtRouteMiddleware((to, from) => {
-   console.log("we're doing some authy things")
- });

+ const authMiddleware = (to, from) => {
+   console.log("we're doing some authy things")
+}

export default defineNuxtPlugin((_nuxt) => {
  addRouteMiddleware('auth', authMiddleware, { global: true })
})
```

I apologize for the lack of documentation.

**Comment by Towerism** [comment]
This makes sense. We were essentially relying on a bug, and now that the bug is fixed, we have to modify our code to do it the right way. Thank you very much for the help.
