### ISSUE TITLE
useLazyFetch with nitro: false option doesn't work

### ISSUE THREAD

**Issue by deleteme** [nuxt/bridge#841]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `2.17.0`
- Nitro Version:    `2.5.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `axios`, `build`, `bridge`, `serverHandlers`, `devServerHandlers`, `devServer`, `typescript`, `nitro`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-28125529.9b0a98e`

### Reproduction

https://github.com/deleteme/nuxt2-starter-with-bridge/tree/repro-use-lazy-fetch-error

This is a fresh Nuxt 2 app with Bridge. The only modification to the nuxt bridge config is `nitro: false`.

### Describe the bug

Calling `useLazyFetch` in a Nuxt page Vue component's `setup()` method throws an error about not having  `$fetch` defined.

### Additional context

I didn't find any mention of having to define or implement `$fetch` in the readme or the Bridge docs. I also didn't find anything mentioning not being able to use select composables with only the Nitro server.

### Logs

```shell
ERROR  [Vue warn]: Error in setup: "ReferenceError: $fetch is not defined"                                          3:52:15 PM

found in

---> <IndexPage> at pages/index.vue
       <Nuxt>
         <.nuxt/layouts/default.vue> at .nuxt/layouts/default.vue
           <Root>
```

**Comment by danielroe** [comment]
You're right, this should be documented. The isomorphic `$fetch` helper relies on Nitro.

**Comment by wattanx** [comment]
It is already in the latest documentation.
https://nuxt.com/docs/bridge/nuxt3-compatible-api#useasync-and-usefetch

**Comment by pawmanaloto** [comment]
Hello @wattanx @danielroe  is there a way to use useFetch with nitro disabled?

**Comment by wattanx** [comment]
`useFetch` is not available in Nuxt Bridge. Also, there is no way to use `useLazyFetch` with `nitro: false`. 
Instead, `useLazyAsyncData` can be used even with `nitro: false`.
