### ISSUE TITLE
nuxi build and preview with bridge vite: true option throws ReferenceError: process is not defined

### ISSUE THREAD

**Issue by deleteme** [nuxt/bridge#845]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `2.17.0`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `axios`, `build`, `bridge`, `serverHandlers`, `devServerHandlers`, `devServer`, `typescript`, `nitro`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-28132497.798694a`

### Reproduction

https://github.com/deleteme/nuxt2-bridge-vite-bug/tree/vite-build

Steps to reproduce:

1. git clone https://github.com/deleteme/nuxt2-bridge-vite-bug and check out the vite-build branch
2. yarn
3. yarn build
4. yarn start
5. open localhost:3000
6. view `ReferenceError: process is not defined` in the browser console

### Describe the bug

After changing setting the`vite: true` bridge option in nuxt.config.js, building the a brand new Nuxt 2 app and starting it, an error appears in the browser console.

![Screenshot 2023-06-28 at 2 43 26 PM](https://github.com/nuxt/bridge/assets/9389/a39706a4-f61b-41ff-92c2-576dbeeb3738)

Looking at the nearby minified code, I see mention of `$config.axios` and `process.browser`. It's likely that `@nuxtjs/axios` didn't run properly and install axios in nuxt.

### Additional context

This [reproduction git repository](https://github.com/deleteme/nuxt2-bridge-vite-bug/tree/vite-build) contains a fresh Nuxt 2 project via (yarn create nuxt-app), with Nuxt Bridge being the only additional package.

This bug was encountered while evaluating Nuxt Bridge. I wanted to know if Nuxt Bridge works (or what parts of it work) in a brand new Nuxt 2 app to determine if it's suitable for use in the migration of a large Nuxt 2 app to Nuxt 3.

### Logs

```shell
I  ~/s/nuxt2-bridge-vite-bug vite-build 0.6s ❱ yarn build
yarn run v1.22.19
$ nuxi build
Nuxi 3.6.0
Nuxt 2.17.0 with Nitro 2.5.2
🧪  Vite mode is experimental and some nuxt modules might be incompatible
    If you find a bug, please report via https://github.com/nuxt/bridge/issues with a minimal reproduction.
ℹ Production build
ℹ Bundling for server and client side
ℹ Target: server
ℹ Using components loader to optimize imports
ℹ Discovered Components: .nuxt/components/readme.md
✔ Builder initialized
✔ Nuxt files generated
ℹ Client built in 4709ms
ℹ Building server...
✔ Server built in 206ms
✔ Generated public .output/public
ℹ Building Nitro Server (preset: node-server)
✔ Nitro server built
  ├─ .output/server/chunks/app/chunks/index.mjs (1.09 kB) (495 B gzip)
  ├─ .output/server/chunks/app/chunks/index.mjs.map (665 B) (319 B gzip)
  ├─ .output/server/chunks/app/chunks/NuxtLogo.mjs (2.35 kB) (1.16 kB gzip)
  ├─ .output/server/chunks/app/chunks/NuxtLogo.mjs.map (802 B) (350 B gzip)
  ├─ .output/server/chunks/app/chunks/Tutorial.mjs (7.05 kB) (3.21 kB gzip)
  ├─ .output/server/chunks/app/chunks/Tutorial.mjs.map (753 B) (352 B gzip)
  ├─ .output/server/chunks/app/client.manifest.mjs (3.19 kB) (571 B gzip)
  ├─ .output/server/chunks/app/client.manifest.mjs.map (2.88 kB) (559 B gzip)
  ├─ .output/server/chunks/app/server.mjs (255 kB) (70.9 kB gzip)
  ├─ .output/server/chunks/app/server.mjs.map (381 kB) (42.7 kB gzip)
  ├─ .output/server/chunks/error-500.mjs (4.26 kB) (1.82 kB gzip)
  ├─ .output/server/chunks/error-500.mjs.map (1.09 kB) (412 B gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs (105 kB) (36.2 kB gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs.map (493 kB) (25.3 kB gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs (27 kB) (7.84 kB gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs.map (94 kB) (6.67 kB gzip)
  ├─ .output/server/index.mjs (539 B) (283 B gzip)
  └─ .output/server/package.json (816 B) (375 B gzip)
Σ Total size: 2.13 MB (396 kB gzip)
✔ You can preview this build using node .output/server/index.mjs
✨  Done in 7.67s.
```
Starting the server:

```shell
 I  ~/s/nuxt2-bridge-vite-bug vite-build 7.8s ❱ yarn start
yarn run v1.22.19
$ nuxi preview
Nuxi 3.6.0
ℹ Node.js version: 18.15.0
ℹ Preset: node-server
ℹ Working dir: .output
ℹ Loading .env. This will not be loaded when running the server in production.
ℹ Starting preview command: node ./server/index.mjs

Listening http://[::]:3000
```

**Comment by wattanx** [comment]
I think it is a `@nuxtjs/axios` problem, as it does not occur when `nuxtjs/axios` is not used.
https://stackblitz.com/edit/github-3fgb91-zh67wg

**Comment by danielroe** [comment]
We probably need to configure `process.browser` within `vite.define`.

**Comment by wattanx** [comment]
The latest version is `process.client` instead of `process.browser`.
https://github.com/nuxt-community/axios-module/blob/main/lib/plugin.js#L196

Since `process.browser` seems to be deprecated, I don't think it should be in the vite define.
https://github.com/nuxt/nuxt/issues/4106

I believe the problem is that `@nuxtjs/axios` is still using `process.browser` in `.nuxt/axios.js` even after installing the latest version.

**Comment by danielroe** [comment]
I think we should probably still include it in the vite define as there will be nuxt 2 modules relying on it.

**Comment by wattanx** [comment]
Sure. Thanks, I will work on this!
