### ISSUE TITLE
vite mode struggles with resolving @nuxtjs/composition-api imports

### ISSUE THREAD

**Issue by deleteme** [nuxt/bridge#846]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `2.17.0`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `axios`, `build`, `bridge`, `serverHandlers`, `devServerHandlers`, `devServer`, `typescript`, `nitro`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-28132497.798694a`

### Reproduction

https://github.com/deleteme/nuxt2-bridge-vite-bug/tree/vite-with-%40nuxtjs/composition-api

Steps to Reproduce:

1. Clone the https://github.com/deleteme/nuxt2-bridge-vite-bug repo and checkout the `vite-with-@nuxtjs/composition-api` branch
2. yarn
3. yarn dev
4. visit http://localhost:3000/useroute

### Describe the bug

Importing `useRoute` from `@nuxtjs/composition-api` is partially working when `vite: true` is set. The server-generated page looks correct, but the server logs errors and some js for the page fails to load.

![Screenshot 2023-06-28 at 3 13 11 PM](https://github.com/nuxt/bridge/assets/9389/a318bc72-33e8-4149-9ccf-82a05d90d487)

### Additional context

The repo contains a fresh Nuxt 2 app, one `useroute.vue` page with `import { defineComponent, useRoute } from '@nuxtjs/composition-api'`, and Nuxt Bridge with `vite: true` set.

* The errors don't happen with `vite: false`
* The problem also goes away when using auto imports instead or `imports: false` is set in the nuxt config and manually importing from `#app`.

### Logs

After running `yarn dev`:

```shell
Nuxi 3.6.0
Nuxt 2.17.0 with Nitro 2.5.2

  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.50.190:3000/
  > Network:  http://[fdb8:5d0e:71a3:4345:1c4e:2edc:cbc9:8bfd]:3000/

ℹ Module nuxt-bridge took 4.02ms to setup.
ℹ Module imports took 0.47ms to setup.
🧪  Vite mode is experimental and some nuxt modules might be incompatible
    If you find a bug, please report via https://github.com/nuxt/bridge/issues with a minimal reproduction.
ℹ Module nuxt-bridge:vite took 0.56ms to setup.
ℹ Preparing project for development
ℹ Initial build may take a while
ℹ Discovered Components: .nuxt/components/readme.md
✔ Builder initialized
✔ Nuxt files generated
ℹ Vite warmed up in 2ms
✔ Nitro built in 218 ms
ℹ Waiting for file changes
```

After visiting http://localhost:3000/useroute, the server logs the following:

```shell
[3:07:58 PM] [bridge] [legacy capi] @nuxtjs/composition-api is deprecated. Please see https://nuxt.com/docs/bridge/bridge-composition-api for more information.
[3:07:58 PM] [bridge] [legacy capi] You are using useRoute, which has a Nuxt 3-compatible replacement. Please see https://nuxt.com/docs/bridge/bridge-composition-api for more information.
✘ [ERROR] Could not resolve "#build/composition-globals.mjs"

    node_modules/@nuxt/bridge/dist/runtime/capi.legacy.mjs:5:29:
      5 │ import { isFullStatic } from "#build/composition-globals.mjs";
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "#build/composition-globals.mjs" as external to exclude it from the bundle,
  which will remove this error.


 ERROR  3:07:58 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@nuxt/bridge/dist/runtime/capi.legacy.mjs:5:29: ERROR: Could not resolve "#build/composition-globals.mjs"
    at failureErrorWithLog (/Users/deleteme/src/nuxt2-bridge-vite-bug/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/deleteme/src/nuxt2-bridge-vite-bug/node_modules/esbuild/lib/main.js:1048:25
    at /Users/deleteme/src/nuxt2-bridge-vite-bug/node_modules/esbuild/lib/main.js:1512:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

The browser network panel shows that a request to `http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/@nuxtjs_composition-api.js?v=15a013a3` fails with a "504 Outdated Optimized Dep" status.

The browser console logs a TypeError:

```
TypeError: error loading dynamically imported module: http://localhost:3000/_nuxt/pages/useroute.vue
```

**Comment by wattanx** [comment]
If you change `jsconfig.json` as follows, the error will not occur.
```
{
  "extends": ". /.nuxt/tsconfig.json"
}
```

> Overwriting options such as "compilerOptions.paths" with your own configuration will lead TypeScript to not factor in the module resolutions from ./.nuxt/tsconfig.json. This can lead to module resolutions such as #imports not being recognized.
https://nuxt.com/docs/guide/concepts/typescript

**Comment by Migushthe2nd** [comment]
Note to others: `[ERROR] Could not resolve "#build/composition-globals.mjs"` may occur when you fogot to update an old `@.../composition-api` import somewhere.
