### ISSUE TITLE
Correct way to read environment variables from a .js file using Webpack

### ISSUE THREAD

**Issue by Jesus82** [nuxt/bridge#855]
### Environment

Nuxi 3.6.1 

### Reproduction

I have set the .env variables in nuxt.config.ts (using webpack)
```
runtimeConfig: {
    public: {
      MY_VAR: process.env.MY_VAR,
   }
}
```
Then, in .vue files, I can access them via `$config.public.MY_VAR` On the server folder I can access them with `process.env.MY_VAR`

### Describe the bug

I have several `.js` files with constants that I import to my `.vue` components. There I cannot access them neither `this.$config / $config`, nor via `process.env.` With `$config` I get an error, while with [process.env](url) I get `null`.

Example
`constant.js`

```
export const mySlugCollection = [
  {
    slug: 'mySlug',
    links: 'a-cool-slug',
  },
  {
    slug: 'myOtherSlug',
    links: process.env.MY_VAR,
  },
```
`myComponent.vue`
```
<template>
    <nuxt-link v-for="slug in mySlugCollection" :to="slug">
</template>
    
<script>
import { mySlugCollection } from './constant'
data() {
    return {
      mySlugCollection,
    }
}
```

What would be the recommended way to to this?

**Comment by wattanx** [comment]
- `process.env` is only available on the Server Side.
- If you want to use it on the Client Side, you need to set it to `runtimeConfig.public`.
- `this.$config` can only be used with Vue components.

If you want to separate them into different files, how about making them composables?
(`useRuntimeConfig` is also only available for Vue components or Composables.)

```ts
export const useSlugCollection = () => {
  const config = useRuntimeConfig();
  const mySlugCollection = [
    {
      slug: 'mySlug',
      links: 'a-cool-slug',
    },
    {
      slug: 'myOtherSlug',
      links: config.MY_VAR,
    },
  ]
  return { mySlugCollection }
}
```

**Comment by Jesus82** [comment]
@wattanx I can see an easy way of using composables with a constant .js file. However, I have other use case where I use a service that makes API calls to an endpoint, and it is called by a Vuex hook. Here I cannot find the way to make it work with composables in order to be able to use environment variables. See SO question [here](https://stackoverflow.com/questions/76693950/nuxt-3-load-service-based-in-env-variable-through-vuex-store) and minimal reproduction [here](https://stackblitz.com/edit/github-dwx287-oygyaf?file=composables%2FuseApi.js,nuxt.config.ts,pages%2Findex.vue,store%2Findex.js).

**Comment by wattanx** [comment]
@Jesus82 
In nuxtServerInit, you can use `$config` to get the value from the second argument, context.
(composables are intended for use within Vue Component or composables.)

```js
export const actions = {
  async nuxtServerInit(vuexContext, { $config }) {
    console.log($config.API_URL)
    vuexContext.dispatch('loadApiData');
  },
};
```

**Comment by Jesus82** [comment]
@wattanx thanks a lot for your quick response. I see I could make it work, but this would also break a bit the service structure, where I set the base api call in one place, and then I implement several methods based on that and in other different api calls.

```
const apiClient = axios.create({
    baseURL: process.env.API_URL,
})
  
const anotherApiClient = axios.create({
    baseURL: process.env.ANOTHER_API_URL,
})



export const fetchApiData = () => {
    return apiClient.get()
}

export const fetchAnotherApiData = () => {
    return anotherApiClient.get()
}
```

I'm trying to pass instead the nuxt context from Vuex to the composable or to a plain services.js file, something like 

```
loadApiData({commit}, context) {
  const myApiData = useApi(context)
  commit('SET_API_DATA', myApiData)
}
```

And then being able to access `context.config` there, but I get a `context is not defined` error when doing so. Is there any way to do that in order to be able to keep current architecture?

**Comment by wattanx** [comment]
@Jesus82 
I think the method of passing config as an argument looks good.
How about like this?
https://stackblitz.com/edit/github-dwx287-xvszrr
