### ISSUE TITLE
Error when trying to render dynamic components

### ISSUE THREAD

**Issue by Jesus82** [nuxt/bridge#857]
### Environment

Nuxi 3.6.1

### Reproduction

[https://stackblitz.com/edit/github-dwx287-gvmmd4?file=pages%2Findex.vue](https://stackblitz.com/edit/github-dwx287-gvmmd4?file=pages%2Findex.vue)

### Describe the bug

When trying to render a dynamic component, as per the [docs](https://nuxt.com/docs/guide/directory-structure/components), we should use the `resolveComponent` helper that is provided by Vue 3.

But when trying to do that, I'm getting a `ReferenceError: resolveComponent is not defined`

**Comment by wattanx** [comment]
The `resolveComponent` is only available in Vue 3, so it can only be used in Nuxt 3.
Nuxt Bridge is not Vue 3, so you need to follow the Vue 2 guide.
https://v2.vuejs.org/v2/guide/components-dynamic-async.html
