### ISSUE TITLE
Using process.env variables in app.html

### ISSUE THREAD

**Issue by iandevlin** [nuxt/bridge#881]
I have a Nuxt 2.17.1 project which uses an `app.html` file to define various things.

Within that `app.html` file it accesses variables like `process.env.CDN_PATH` to load such things as fonts from a CDN.

These appear to be completely inaccessible with Nuxt Bridge.

Can anyone tell me how to get these environment variables to work in this case?

And if it's not possible, first of all why, and secondly, what would be an alternative method? I cannot find anything at all in the documentation with regards to this.

Thanks in advance.

**Comment by danielroe** [comment]
I'll have a look. would you provide a minimal reproduction?

**Comment by iandevlin** [comment]
Unfortunately that's not possible at the moment, but the simple fact that you didn't reply with "oh no that won't work because of X" tells me that it should be possible to access `process.env` variables in a HTML file.

**Comment by danielroe** [comment]
Well, honestly half the reason I asked was that it really doesn't seem like that should work.

**Comment by iandevlin** [comment]
Ah ok, interesting, it works fine with Nuxt 2, but perhaps it's a webpack thing.

**Comment by wattanx** [comment]
Close as no further investigation is possible as no reproduction is available.
If it is still occurring, please create a reproduction.
