### ISSUE TITLE
Nuxi doesn't work with TS decorators

### ISSUE THREAD

**Issue by BulatSa** [nuxt/bridge#882]
### Environment

- Operating System: Win10
- Node Version: v18.15.0
- Nuxt Version: 2.17.1
- Nitro Version: 2.5.2
- Package Manager: npm@8.19.4
- Builder: vite, webpack
- User Config: bridge, typescript, nitro
- Runtime Modules: -
- Build Modules: (), @nuxt/bridge@3.0.0-28200790.d820607

### Reproduction

My project is private. 

### Describe the bug

I use inversify@6.0.1 with TS@5.1.2 and after adding nuxt-bridge with nuxi i have issue
![image](https://github.com/nuxt/bridge/assets/8298469/5e2a3130-285f-47e3-8f4d-c59991e94ed8)
![image](https://github.com/nuxt/bridge/assets/8298469/06444b99-eb06-46c3-8c15-701be2b9f0d1)

But if i use config 
```
buildModules: [
  '@nuxt/typescript-build'
],
bridge: {
  typescript: false,
},
```
and run with `npm run nuxt` all work fine

### Additional context

tsconfig.json
```
{
  "extends": "./.nuxt/tsconfig.json",
  "vueCompilerOptions": {
    "target": 2.7,
  },
  "compilerOptions": {
    "module": "esnext",
    "target": "es2018",
    "moduleResolution": "node",
    "strict": true,
    "lib": [
      "ESNext",
      "ESNext.AsyncIterable",
      "DOM",
      "DOM.Iterable"
    ],
    "esModuleInterop": true,
    "allowJs": true,
    "sourceMap": true,
    "noEmit": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strictPropertyInitialization": false,
    "skipLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "~/*": [
        "./*"
      ],
      "@/*": [
        "./*"
      ]
    },
    "types": [
      "reflect-metadata",
      "@nuxt/types",
      "@types/node",
      "@nuxtjs/axios",
      "@nuxtjs/auth-next",
    ],
  },
  "include": [
    "./**/*"
  ],
  "exclude": [
    "node_modules",
    ".nuxt",
    "dist"
  ]
}
```

**Comment by BulatSa** [comment]
Some issue https://github.com/nuxt/nuxt/issues/14126

**Comment by BulatSa** [comment]
With vite have some issue
https://github.com/vitejs/vite/issues/13736

**Comment by toyopilgrim** [comment]
This config worked. 

```
export default defineNuxtConfig({
  bridge: {
    capi: true,
    nitro: true,
    vite: true
  },
  vite: {
    esbuild: {
      tsconfigRaw: {
        compilerOptions: {
          experimentalDecorators: true
        }
      }
    }
  },
}
```

**Comment by BulatSa** [comment]
I think, it can help to resolve this issue
https://stackoverflow.com/questions/52557878/babel-7-inversify-4-webpack-4-unexpected-character-on-inject

**Comment by WojciechxFalkowski** [comment]
Is it still open I have same issue after upgrading nuxt from 3.2.3 to 3.8?

**Comment by wattanx** [comment]
The latest version seems to solve this problem by setting the `experimentalDecorators` option in tsconfig.
https://stackblitz.com/edit/github-yw5f4n

**Comment by gaucj-t** [comment]
@wattanx when you run yarn build it gives errors. I think the issue still persists.
![Screenshot 2024-04-11 at 13 03 24](https://github.com/nuxt/bridge/assets/56966814/fe616e92-9e39-4819-bf56-d9d070d93f05)

**Comment by Dmoulart** [comment]
Hi,
I also encountered this issue today and the problem is related to TS decorators in general. 
Setting experimentalDecorators in tsconfig has no effect, downgrading nuxi and nuxt-bridge does not help either.

**Comment by wattanx** [comment]
Sorry, you reproduced the environment incorrectly.
It works when configured as follows.

https://stackblitz.com/edit/github-yw5f4n?file=nuxt.config.ts
```ts
import { defineNuxtConfig } from '@nuxt/bridge';

export default defineNuxtConfig({
  ssr: false,
  bridge: {
    vite: true,
    nitro: true,
  },
  vite: {
    esbuild: {
      tsconfigRaw: {
        compilerOptions: {
          experimentalDecorators: true
        }
      }
    }
  }
});

```
