### ISSUE TITLE
Nuxt bridge issue when upgrading nodejs version from 18 to 20

### ISSUE THREAD

**Issue by hadelnasr** [nuxt/bridge#894]
### Environment

Nuxt project info:                                                                                                                       10:41:17 AM

------------------------------
- Operating System: Linux
- Node Version:     v20.5.1
- Nuxt Version:     2.17.1
- Nitro Version:    2.6.2
- Package Manager:  npm@9.8.0
- Builder:          webpack
- User Config:      sourcemap, dev, head, loading, reactiveLoading, css, plugins, buildModules, googleAnalytics, moment, modules, webfontloader, build, router, auth, hooks, runtimeConfig, serverHandlers, devServerHandlers, devServer, typescript, nitro, bridge
- Runtime Modules:  @nuxtjs/google-analytics@2.4.0, @nuxtjs/moment@1.6.1, nuxt-webfontloader@1.1.0, @nuxtjs/i18n@7.3.1, @nuxtjs/axios@5.13.6, @nuxtjs/dotenv, @nuxtjs/auth@4.9.1, ~/src/modules/news/Index.js, ~/src/modules/logisticsCenters/Index.js, ~/src/modules/currencies/Index.js, ~/src/modules/tariff/Index.js, ~/src/modules/faq/Index.js
- Build Modules:    (), @pinia/nuxt@0.4.11, bootstrap-vue/nuxt, @nuxtjs/device@2.2.0, @nuxt/bridge@3.0.0-28200790.d820607

### Reproduction

running npm run nux-dev => NODE_OPTIONS=--openssl-legacy-provider nuxi dev --port 3000

### Describe the bug

when running npm run nuxi-dev command it's failing with the below errors and warning and the server is not starting anymore

 FATAL  Cannot read properties of null (reading 'close')                                                                                  9:38:07 AM

  at Builder.unwatch (node_modules/@nuxt/builder-edge/dist/builder.js:713:30)
  at Builder.close (node_modules/@nuxt/builder-edge/dist/builder.js:721:10)
  at node_modules/@nuxt/builder-edge/dist/builder.js:179:42
  at node_modules/hable/dist/hable.js:1:990
  at node_modules/hable/dist/hable.js:1:208
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Nuxt.callHook (node_modules/hable/dist/hable.js:1:959)
  at async Nuxt.close (node_modules/@nuxt/core-edge/dist/core.js:359:5)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:178:11)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:97:10)

 WARN  Compiled with 75 warnings                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/logisticsCenters/Inject.js                                                                          friendly-errors 10:47:17

"export 'ContactsAndFacilitiesResponseInterface' was not found in '~/src/modules/logisticsCenters/application/dtos/ContactsAndFacilitiesResponseInterface'
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/currencies/Inject.js                                                                                friendly-errors 10:47:17

"export 'CurrenciesRepositoryInterface' was not found in '~/src/modules/currencies/application/contract/CurrenciesRepositoryInterface'
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/currencies/Inject.js                                                                                friendly-errors 10:47:17

"export 'CurrenciesResponseInterface' was not found in '~/src/modules/currencies/application/dtos/CurrenciesResponseInterface'
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/currencies/Inject.js                                                                                friendly-errors 10:47:17

"export 'CurrencyHistoryResponseInterface' was not found in '~/src/modules/currencies/application/dtos/CurrencyHistoryResponseInterface'
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'EMPTY_ARR' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'           friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'EMPTY_OBJ' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'           friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/faq/Inject.js                                                                                       friendly-errors 10:47:17

"export 'FaqDetailsResponseInterface' was not found in '~/src/modules/faq/application/dtos/FaqDetailsResponseInterface'     friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/faq/Inject.js                                                                                       friendly-errors 10:47:17

"export 'FaqHelpfulResponseInterface' was not found in '~/src/modules/faq/application/dtos/FaqHelpfulResponseInterface'     friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/faq/Inject.js                                                                                       friendly-errors 10:47:17

"export 'FaqListResponseInterface' was not found in '~/src/modules/faq/application/dtos/FaqListResponseInterface'           friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/faq/Inject.js                                                                                       friendly-errors 10:47:17

"export 'FaqRepositoryInterface' was not found in '~/src/modules/faq/application/contract/FaqRepositoryInterface'           friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/faq/Inject.js                                                                                       friendly-errors 10:47:17

"export 'FaqsCategoriesListResponseInterface' was not found in '~/src/modules/faq/application/dtos/FaqsCategoriesListResponseInterface'
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/faq/Inject.js                                                                                       friendly-errors 10:47:17

"export 'FaqsTopTagsResponseInterface' was not found in '~/src/modules/faq/application/dtos/FaqsTopTagsResponseInterface'   friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/shared/Inject.js                                                                                            friendly-errors 10:47:17

"export 'HttpErrorHandlingInterface' was not found in '~/src/shared/interfaces/HttpErrorHandlingInterface'                  friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/shared/Inject.js                                                                                            friendly-errors 10:47:17

"export 'HttpServiceCreatorInterface' was not found in '~/src/shared/interfaces/HttpServiceCreatorInterface'                friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/shared/Inject.js                                                                                            friendly-errors 10:47:17

"export 'HttpServiceInterface' was not found in '~/src/shared/interfaces/HttpServiceInterface'                              friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/logisticsCenters/Inject.js                                                                          friendly-errors 10:47:17

"export 'LogisticCentersAreasResponseInterface' was not found in '~/src/modules/logisticsCenters/application/dtos/LogisticCentersAreasResponseInterface'
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/logisticsCenters/Inject.js                                                                          friendly-errors 10:47:17

"export 'LogisticCentersRepositoryInterface' was not found in '~/src/modules/logisticsCenters/application/contract/LogisticCentersRepositoryInterface'
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/logisticsCenters/Inject.js                                                                          friendly-errors 10:47:17

"export 'LogisticCentersResponseInterface' was not found in '~/src/modules/logisticsCenters/application/dtos/LogisticCentersResponseInterface'
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'NO' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'                  friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'NOOP' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'                friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/news/Inject.js                                                                                      friendly-errors 10:47:17

"export 'NewsCategoryResponseInterface' was not found in '~/src/modules/news/application/dtos/NewsCategoryResponseInterface'
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/news/Inject.js                                                                                      friendly-errors 10:47:17

"export 'NewsItemsInterface' was not found in '~/src/modules/news/application/dtos/NewsItemsInterface'                      friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/news/Inject.js                                                                                      friendly-errors 10:47:17

"export 'NewsRepositoryInterface' was not found in '~/src/modules/news/application/contract/NewsRepositoryInterface'        friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/news/Inject.js                                                                                      friendly-errors 10:47:17

"export 'NewsResponseInterface' was not found in '~/src/modules/news/application/dtos/NewsResponseInterface'                friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/news/Inject.js                                                                                      friendly-errors 10:47:17

"export 'NewsTopListResponseInterface' was not found in '~/src/modules/news/application/dtos/NewsTopListResponseInterface'  friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/news/Inject.js                                                                                      friendly-errors 10:47:17

"export 'NewsYearsResponseInterface' was not found in '~/src/modules/news/application/dtos/NewsYearsResponseInterface'      friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/faq/Inject.js                                                                                       friendly-errors 10:47:17

"export 'RelatedFaqResponseInterface' was not found in '~/src/modules/faq/application/dtos/RelatedFaqResponseInterface'     friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/news/Inject.js                                                                                      friendly-errors 10:47:17

"export 'SingleNewsResponseInterface' was not found in '~/src/modules/news/application/dtos/SingleNewsResponseInterface'    friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/tariff/Inject.js                                                                                    friendly-errors 10:47:17

"export 'TariffChaptersResponseInterface' was not found in '~/src/modules/tariff/application/dtos/TariffChaptersResponseInterface'
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/tariff/Inject.js                                                                                    friendly-errors 10:47:17

"export 'TariffDetailsInterface' was not found in '~/src/modules/tariff/application/dtos/TariffDetailsInterface'            friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/tariff/Inject.js                                                                                    friendly-errors 10:47:17

"export 'TariffDetailsResponseInterface' was not found in '~/src/modules/tariff/application/dtos/TariffDetailsResponseInterface'
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/tariff/Inject.js                                                                                    friendly-errors 10:47:17

"export 'TariffItemsInterface' was not found in '~/src/modules/tariff/application/dtos/TariffItemsInterface'                friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/tariff/Inject.js                                                                                    friendly-errors 10:47:17

"export 'TariffItemsResponseInterface' was not found in '~/src/modules/tariff/application/dtos/TariffItemsResponseInterface'
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./src/modules/tariff/Inject.js                                                                                    friendly-errors 10:47:17

"export 'TariffRepositoryInterface' was not found in '~/src/modules/tariff/application/contract/TariffRepositoryInterface'  friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'camelize' (imported as 'camelize$1') was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'camelize' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'            friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'capitalize' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'          friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'def' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'                 friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@nuxt/bridge/dist/runtime/app.plugin.mjs                                                           friendly-errors 10:47:17

"export 'default' (imported as 'Vue') was not found in 'vue'                                                                friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'extend' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'              friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'getGlobalThis' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'       friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'hasChanged' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'          friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'hasOwn' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'              friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'hyphenate' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'           friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'includeBooleanAttr' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'  friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@nuxt/bridge/node_modules/vue/dist/vue.runtime.esm-bundler.js                                      friendly-errors 10:47:17

"export 'initCustomFormatter' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs' friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'invokeArrayFns' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'      friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'isArray' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'             friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'isBuiltInDirective' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'  friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'isGloballyWhitelisted' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'isHTMLTag' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'           friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'isMap' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'               friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'isModelListener' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'     friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'isObject' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'            friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'isOn' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'                friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'isPlainObject' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'       friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'isPromise' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'           friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'isRegExp' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'            friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'isReservedProp' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'      friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'isSVGTag' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'            friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'isSet' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'               friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'isSpecialBooleanAttr' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'isString' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'            friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'looseEqual' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'          friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'looseIndexOf' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'        friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'looseToNumber' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'       friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'makeMap' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'             friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'normalizeClass' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'      friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'normalizeStyle' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'      friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'remove' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'              friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@nuxt/bridge/dist/runtime/composables.mjs                                                          friendly-errors 10:47:17

"export 'set' was not found in 'vue'                                                                                        friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'toHandlerKey' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'        friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js                                                   friendly-errors 10:47:17

"export 'toNumber' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'            friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js                                                 friendly-errors 10:47:17

"export 'toRawType' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'           friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 WARN  in ./node_modules/@nuxt/bridge/node_modules/vue/dist/vue.runtime.esm-bundler.js                                      friendly-errors 10:47:17

"export 'warn' was not found in '/var/www/html/vuejs-nuxt-newnode-20/.nuxt/runtime.vue2-bridge.027cdae8.mjs'                friendly-errors 10:47:17
                                                                                                                            friendly-errors 10:47:17

 ERROR  Failed to compile with 1 errors                                                                                     friendly-errors 10:47:17

 ERROR  in ./.nuxt/capi.plugin.mjs                                                                                          friendly-errors 10:47:17

Module parse failed: Identifier 'defineNuxtPlugin' has already been declared (2:94)                                         friendly-errors 10:47:17
File was processed with these loaders:
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
You may need an additional loader to handle the result of these loaders.
| import { defineNuxtPlugin } from '#app';
> import"core-js/modules/es.array.map.js";import"core-js/modules/es.object.to-string.js";import{defineNuxtPlugin}from'#app';export default defineNuxtPlugin(function(nuxtApp){var _originalSetup=nuxtApp.nuxt2Context.app.setup;nuxtApp.nuxt2Context.app.setup=function(){var result=_originalSetup instanceof Function?_originalSetup.apply(void 0,arguments):{};var hookResult=nuxtApp.hooks.callHookWith(function(hooks){return hooks.map(function(hook){return hook();});},'vue:setup');if(process.dev&&hookResult&&hookResult.some(function(i){return i&&'then'in i;})){console.error('[nuxt] Error in `vue:setup`. Callbacks must be synchronous.');}return result;};});
                                                                                                                            friendly-errors 10:47:17
 @ ./.nuxt/index.js 14:0-77 54:2305-2336 54:2402-2433
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js

**Comment by wattanx** [comment]
It's the same problem as https://github.com/nuxt/bridge/issues/832, so I'll track it over it.

**Comment by hadelnasr** [comment]
@wattanx it's not the same issue
the errors and the warnings thrown are not the same and i'm using node version 20 not 18

**Comment by wattanx** [comment]
The error below is the same, so we have determined that it is the same problem.

```log
FATAL Cannot read properties of null (reading 'close') 9:38:07 AM

at Builder.unwatch (node_modules/@nuxt/builder-edge/dist/builder.js:713:30)
at Builder.close (node_modules/@nuxt/builder-edge/dist/builder.js:721:10)
at node_modules/@nuxt/builder-edge/dist/builder.js:179:42
at node_modules/hable/dist/hable.js:1:990
at node_modules/hable/dist/hable.js:1:208
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Nuxt.callHook (node_modules/hable/dist/hable.js:1:959)
at async Nuxt.close (node_modules/@nuxt/core-edge/dist/core.js:359:5)
at async load (node_modules/nuxi/dist/chunks/dev.mjs:178:11)
at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:97:10)
```

I would like to check a few things,
- Does this occur on node 18?
- Are there any repositories that reproduce it?

**Comment by hadelnasr** [comment]
@wattanx no, i'm not facing it with node 18
