### ISSUE TITLE
runtimeConfig is empty in plugins

### ISSUE THREAD

**Issue by AndreyYolkin** [nuxt/bridge#9]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Builder:          `webpack`
- User Config:      `privateRuntimeConfig`, `publicRuntimeConfig`, `plugins`, `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27495976.e31c604`

### Reproduction

Old configuration: https://codesandbox.io/s/hardcore-dream-07bz0n?file=/nuxt.config.js  
New configuration: https://codesandbox.io/s/peaceful-williamson-vddeiq?file=/nuxt.config.js

### Describe the bug

I've just copied the example from https://github.com/nuxt/framework/pull/4254, created new plugin and page, which prints config values in console. It logs nothing in plugin (plugins/plugin.js) but outputs public values at runtime (see pages/index.js)

**Comment by fabis94** [comment]
@pi0 Hi, any estimate for when this could be fixed (or when you plan to make the move to that new repo)? In my case I don't get any runtimeConfig values on the serverside when accessing them through this.$config in Vue components, and I'm guessing it's the same issue.

**Comment by pi0** [comment]
Checking against the latest version (`v3.0.0-27497942.c519cee`) it is fully compatible with both new and old syntax. Please check and ping to reopen if still having problems with runtimeConfig.

**Comment by fabis94** [comment]
@pi0 I don't see any such version on npm, but the latest one available (3.0.0-27498038.f18e68b) has that same issue.

Here's how the config is defined in the nuxt config:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/938316/163342152-747eded1-06fb-48d5-909e-5b592b1d28e1.png">

Here's how I'm reading it in my component/mixin:
<img width="457" alt="image" src="https://user-images.githubusercontent.com/938316/163342223-510138db-d07b-423b-a79a-5ebeeda10c41.png">

And here's how it executes on the server-side:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/938316/163342264-436891ee-a51d-4363-a358-937a320311c8.png">

**Comment by baixiaoyu2997** [comment]
> Checking against the latest version (`v3.0.0-27497942.c519cee`) it is fully compatible with both new and old syntax. Please check and ping to reopen if still having problems with runtimeConfig.

work for me, i use `setup syntax` 

and  i think runtimeConfig it's just `nitro` only , when `bridge : { nitro : false } `,will show error,  It would be better if there was more detailed documentation or just tell users not to do this

**Comment by danielroe** [comment]
I can't reproduce the original issue here: https://stackblitz.com/edit/github-frh3le.

Splitting @aldarund's issue into a separate one.
