### ISSUE TITLE
bridge: false results in "Cannot start nuxt: Cannot read properties of undefined (reading 'hook')"

### ISSUE THREAD

**Issue by jschroeter** [nuxt/bridge#900]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.17.0`
- Nuxt Version:     `2.17.1`
- CLI Version:      `3.7.3`
- Nitro Version:    `2.6.2`
- Package Manager:  `npm@9.6.7`
- Builder:          `webpack`
- User Config:      `bridge`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

- install Nuxt 2.17.1
- install Nuxt Bridge
- set `bridge: false` as [described in docs](https://nuxt.com/docs/bridge/overview#update-nuxtconfig)
- run `nuxi dev`

see StackBlitz: https://stackblitz.com/edit/nuxt2-17-bridge-false?file=nuxt.config.ts

### Describe the bug

Nuxt doesn't start with the following error:

```
 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'hook')      10:46:46

  at _load (node_modules/nuxi/dist/chunks/dev-internal.mjs:215:39)
  at async load (node_modules/nuxi/dist/chunks/dev-internal.mjs:261:9)
  at async Object.run (node_modules/nuxi/dist/chunks/dev-internal.mjs:283:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.57fa43de.mjs:1671:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.57fa43de.mjs:1665:7)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.57fa43de.mjs:1783:7)
```

### Additional context

Same happens in my large application which I want to migrate to Nuxt 3 but also in a minimal setup.

**Comment by danielroe** [comment]
I think with `bridge: false` you should run `nuxt dev` and not `nuxi dev`.

**Comment by jschroeter** [comment]
Hi Daniel, thanks for looking into this. Unfortunately it doesn't seem to make any difference.

**Comment by wattanx** [comment]
It looks like `nitro` is running on `nuxt dev` as well.
