### ISSUE TITLE
nuxt/bridge - minimal codesandbox does not start

### ISSUE THREAD

**Issue by mbyrne00** [nuxt/bridge#908]
### Environment

Codesandbox

### Reproduction

As per the [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs#create-a-minimal-reproduction), the [v2-bridge-codesandbox](https://codesandbox.io/s/github/nuxt/starter/v2-bridge-codesandbox) does not load.

### Describe the bug
Codesandbox does not start and gives `502: Bad Gateway`

### Logs

If you fork and try to force it to load again you get logs like this

```
> Sandbox Container: Sandbox 7pwk9l started
yarn run v1.22.19
$ nuxt dev
/bin/sh: 1: nuxt: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ nuxt dev
/bin/sh: 1: nuxt: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ nuxt dev
/bin/sh: 1: nuxt: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19

```

**Comment by neversaynever88** [comment]
rm -rf node_modules
rm yarn.lock
rm -rf .nuxt
yarn cache clean -f
yarn install

**Comment by mbyrne00** [comment]
@neversaynever88 - I'm not sure I understand. This is a fresh codesandbox and it fails to start. I'm guessing an explicit `nuxt` dependency is needed to be added as a `dependency` to it, but I just wanted to check. Either way the fixed codesandbox should be linked to the [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs#create-a-minimal-reproduction) docs.


![image](https://github.com/nuxt/bridge/assets/5687982/73b71e8e-2751-4694-90e0-12b5c99098dc)
![image](https://github.com/nuxt/bridge/assets/5687982/9e963674-b44b-417a-b1ef-1feefc78e764)

**Comment by wattanx** [comment]
Fixed at https://github.com/nuxt/starter/pull/524
Until https://github.com/nuxt/bridge/issues/918 resolves the issue, you can change `nuxi: latest` to `nuxi: 3.8.4` to start.
