### ISSUE TITLE
allow extending `NuxtAppCompat`

### ISSUE THREAD

**Issue by danielroe** [nuxt/bridge#91]
> If I'm correct, useNuxtApp() returns an object of type NuxtAppCompat, and I can't add a type to it because this is not exported from Nuxt Bridge. Am I missing something?

see https://github.com/nuxt-community/dayjs-module/pull/396

**Comment by evgenii-code** [comment]
This approach didn`t work for me.    
> This is now possible.
> 
> ```ts
> declare module '#app' {
>   interface NuxtAppCompat {
>     $thing: boolean
>   }
> }
> export {}
> ```
 

I had to declare module for `'@nuxt/bridge-schema'` instead of `#app`
```ts
declare module '@nuxt/bridge-schema' {
  interface NuxtAppCompat {
     $thing: boolean
  }
}

export {}
```

Does this approach have any pitfalls?
