### ISSUE TITLE
Fresh Nuxt Bridge doesn't start, Cannot start nuxt:  Cannot read properties of undefined (reading 'hook')

### ISSUE THREAD

**Issue by chz** [nuxt/bridge#918]
### Environment

- Operating System: Darwin
- Node Version:     v16.17.1
- Nuxt Version:     2.17.2-28260019.6132947
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      bridge, serverHandlers, devServerHandlers, devServer, typescript, nitro, buildModules
- Runtime Modules:  -
- Build Modules:    (), @nuxt/bridge@3.0.0-28244705.131ac01

### Reproduction

Simple fresh nuxt 2 project add nuxt bridge.

```
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
  bridge: {
    nitro: true,
    vite: true,
  }
})
```

### Describe the bug

It doesn't start with error: `Cannot start nuxt:  Cannot read properties of undefined (reading 'hook')`
<img width="909" alt="Screenshot 2023-09-25 at 19 08 36" src="https://github.com/nuxt/bridge/assets/3233370/651578d0-1c4c-4112-a45e-4d8ad9030d86">

Also checked in node 16,18

**Comment by wattanx** [comment]
It seems to have occurred since `nuxi@3.9.0`.
Currently, the only workaround seems to be to use `3.9.0` or before.

**Comment by chz** [comment]
> It seems to have occurred since `nuxi@3.9.0`. Currently, the only workaround seems to be to use `3.9.0` or before.

I also checked before versions, same thing

**Comment by wattanx** [comment]
@chz 
I can't reproduce it with `nuxi@3.8.4`.
https://stackblitz.com/edit/github-3fgb91-asdpms

Do you have an environment that can be reproduced at `nuxi@3.8.4`?

**Comment by chz** [comment]
> @chz 
> 
> I can't reproduce it with `nuxi@3.8.4`.
> 
> https://stackblitz.com/edit/github-3fgb91-asdpms
> 
> 
> 
> Do you have an environment that can be reproduced at `nuxi@3.8.4`?

i,ve checked with 3.8.7 maybe 3.8.4 is working i will try to check today with 3.8.4 version

**Comment by chz** [comment]
> > @chz
> > I can't reproduce it with `nuxi@3.8.4`.
> > https://stackblitz.com/edit/github-3fgb91-asdpms
> > Do you have an environment that can be reproduced at `nuxi@3.8.4`?
> 
> i,ve checked with 3.8.7 maybe 3.8.4 is working i will try to check today with 3.8.4 version

Yes exactly i have 3.8.4 working. but problem still have in 3.9.0

**Comment by chz** [comment]
@wattanx i've created PR: https://github.com/nuxt/cli/pull/230 that will fix it.

**Comment by wattanx** [comment]
@chz 
I really appreciate your help ❤️

**Comment by chz** [comment]
Merged in : https://github.com/nuxt/nuxt/pull/23502
