### ISSUE TITLE
Middleware API not doing anything

### ISSUE THREAD

**Issue by Jesus82** [nuxt/bridge#942]
### Environment

Build Modules: nuxt/bridge@3.0.0-rc.1-28295948.913b8e5

### Reproduction

https://stackblitz.com/edit/github-dwx287-woy2qk?file=package.json

### Describe the bug

When adding a `test.global.ts` file in the `/middleware` folder (as per the [docs](https://nuxt.com/docs/bridge/plugins-and-middleware)), nothing happens.

**Comment by AndreyYolkin** [comment]
https://github.com/nuxt/bridge/pull/938 adds support for global middlewares

https://stackblitz.com/edit/github-dwx287-j7xsrx?file=middleware%2Ftest.global.ts check this out

**Comment by wattanx** [comment]
Global Middleware is included in `3.0.0-rc.2`.

**Comment by Jesus82** [comment]
@wattanx I reopen it as from parameters is always undefined (see [demo](https://stackblitz.com/edit/github-dwx287-ydqqtk?file=package.json)). Is it a known bug?
