### ISSUE TITLE
SSR: Error handling with useLazyAsyncData composable

### ISSUE THREAD

**Issue by evgenii-code** [nuxt/bridge#944]
### Environment

- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     2.17.2
- CLI Version:      3.9.1
- Nitro Version:    2.7.1
- Package Manager:  yarn@1.22.19
- Builder:          webpack
- User Config:      bridge, head, modules, axios, telemetry, serverHandlers, devServerHandlers, devServer, typescript, nitro, buildModules
- Runtime Modules:  @nuxtjs/axios@5.13.6
- Build Modules:    (), @nuxt/bridge@3.0.0-rc.1-28305662.d20768a

### Reproduction

Repository
https://github.com/evgenii-code/nuxt-bridge-error-page

Reproduction in sandbox  
https://codesandbox.io/p/sandbox/nuxt-bridge--uselazyasyncdata-with-error-ddcrgq

### Describe the bug

I want to redirect to an error page when an error occurs by fetching data with `useLazyAsyncData` composable.  
We can't use `await useLazyAsyncData` in `<script setup>` with Vue 2 and the data is fetching in `lazy` mode.
So the redirect happens only on client side, when `error.value === true`

There you can see how redirect occurs only on client side -- background flashes for a moment.

[Video reproduction](https://i.imgur.com/AeanKjh.mp4)
https://codesandbox.io/p/sandbox/nuxt-bridge--uselazyasyncdata-with-error-ddcrgq

It is mandatory to redirect on server side to the error page if an error occurs.
I can't understand how to achieve this behavior

### Additional context

I can achieve wanted behavior by using `asyncData` in the Options API, but since we want to update out project to Nuxt 3, we want to use Composition API.

**Comment by wattanx** [comment]
Sorry, Composables that block Navigation like asyncData cannot be implemented in nuxt 2.
refs: https://github.com/nuxt-community/composition-api/issues/596#issuecomment-1008972575

As a side note, asyncData can also be used in Nuxt 3.
https://nuxt.com/docs/api/utils/define-nuxt-component#asyncdata

**Comment by evgenii-code** [comment]
@wattanx 
Thank you for the quick response and provided recources,  
I get that we can't block navigation with composition API in Nuxt 2.  

But I think my original question was formulated incorrectly.

I want to get an error from the response, because I see the HTML rendered on the server with an error.
I was wondering, is there some kind of a hook triggering after `useLazyAsyncData` finishes that I can intercept error on server side?

Like
```
const { hook } = useNuxtApp();
const { data } = useLazyAsyncData(...);

hook('whatever:hook', ssrErrorHandler);
```

This is my approach to handle error on my own, but it feels wrong.  
Maybe I should give up and use Options API instead

```
<script setup>
const { $axios } = useNuxtApp()
const { data, pending } = useLazyAsyncData('fetch-todos', async () => {
  try {
    return {
      response: await $axios.$get(
        'https://jsonplaceholder.typicode.com/todos/-1'
      ),
      error: null,
    }
  } catch (error) {
    return { response: null, error }
  }
})
</script>
```
