### ISSUE TITLE
Runtime config is not properly typed in runtime

### ISSUE THREAD

**Issue by AndreyYolkin** [nuxt/bridge#948]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     2.17.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.1
- Package Manager:  npm@9.4.2
- Builder:          webpack
- User Config:      modules, serverHandlers, devServerHandlers, devServer, typescript, nitro, bridge, buildModules
- Runtime Modules:  ~/modules/nested
- Build Modules:    (), @nuxt/bridge@3.0.0-rc.2-28307913.ff6077a
------------------------------

### Reproduction

https://stackblitz.com/edit/github-dwx287-4aikde?file=README.md

install dependencies, then run `npx nuxi typecheck` to catch error

### Describe the bug

Nuxt generates types for RuntimeConfig during the build, we can find the types at `.nuxt/types/schema.d.ts`. However `useRuntimeConfig` returns runtimeConfig with another type, described in '@nuxt/schema` package, which doesn't have any generated fields. After resolving this issue I expect to see proper typings for runtimeConfig

**Comment by AndreyYolkin** [comment]
I tried to backport the code from https://github.com/nuxt/nuxt/blob/4b2608c74d80551eee857ab74ab470da839894f9/packages/nuxt/src/core/templates.ts#L134 and problem was fixed. The only thing we should have in mind is that we should declare "@nuxt/schema" instead of "nuxt/schema"

**Comment by wattanx** [comment]
I think `@nuxt/schema` will work.
I'm waiting for PR!
