### ISSUE TITLE
`useCookie` returns `undefined` on SSR

### ISSUE THREAD

**Issue by evgenii-code** [nuxt/bridge#991]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.18.2
- Nuxt Version:     2.17.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@9.8.1
- Builder:          webpack
- User Config:      bridge, head, css, plugins, components, modules, build, serverHandlers, devServerHandlers, devServer, typescript, nitro, buildModules
- Runtime Modules:  -
- Build Modules:    (), @nuxt/bridge@3.0.0-rc.3-28343365.3c40b3f

### Reproduction

Minimal repo
https://github.com/evgenii-code/nuxt-bridge-use-cookie-ssr

1. Clone repository
2. `npm i`
3. `npm run dev` 
4. Set value to cookie
5. Refresh the page to trigger SSR

### Describe the bug

Composable `useCookie` returns `undefined` on SSR, 
But on a client `useCookie` works as intended.

<details>
<summary>Code of a simple component, that uses cookie on SSR</summary>

```
<template>
  <div>
    <h1>Bug with useCookie on SSR</h1>

    <button @click="setCookie">Set cookie to 'foo'</button>

    <p>Cookie value: {{ `${foo}` }}</p>
  </div>
</template>

<script lang="ts" setup>
const foo = useCookie<string | undefined>('foo')

const setCookie = () => (foo.value = 'foo')
</script>
```

</details>

[Video of a bug](https://imgur.com/zI375iF)

**Comment by wattanx** [comment]
This is the same behavior in nuxt 3.
You may want to track the following PR.
https://github.com/nuxt/nuxt/pull/21940

**Comment by evgenii-code** [comment]
> This is the same behavior in nuxt 3. You may want to track the following PR. [nuxt/nuxt#21940](https://github.com/nuxt/nuxt/pull/21940)

@wattanx 
Are you sure this is a relevant issue?
Because I've recreated the same component in Nuxt 3 and cookie value on SSR is a valid value, not `undefined`.
In Nuxt 3 it doesn't cause hydration error, but in Nuxt Bridge it does.

[Video of Nuxt 3 useCookie SSR](https://imgur.com/gvD1014)

Nuxt 3:
![image](https://github.com/nuxt/bridge/assets/56561823/27e0a2bf-136a-4820-b6b4-8933a99d1bac)

Nuxt Bridge:
![image](https://github.com/nuxt/bridge/assets/56561823/4cb67035-cc31-40e8-9797-2fce42912822)

**Comment by evgenii-code** [comment]
It's just a simple page that reads cookie

```
<template>
  <div>
    <h1>Bug with useCookie on SSR</h1>

    <button @click="setCookie">Set cookie to 'foo'</button>

    <p>Cookie value: {{ `${foo}` }}</p>
  </div>
</template>

<script lang="ts" setup>
const foo = useCookie<string | undefined>('foo')

// `undefined` on a server side and 'foo' on a client, 
// but it should be 'foo' on a server side too
console.log('ssr foo.value', foo.value);

const setCookie = () => (foo.value = 'foo')
</script>
```

https://stackblitz.com/edit/github-zil2p9-fvxznq?file=app.vue

You have to open in a new tab
![image](https://github.com/nuxt/bridge/assets/56561823/87c047b7-6b9c-4860-bf76-b6fdbabb7ae8)

I have a repository with same setup in Nuxt Bridge too
https://github.com/evgenii-code/nuxt-bridge-use-cookie-ssr

**Comment by wattanx** [comment]
Oh sorry. I guess I needed to see it in a separate tab.
It seems like it was resolved in RC.4, but is my understanding correct?
https://stackblitz.com/edit/github-gmtfgt

**Comment by wattanx** [comment]
As you say, I think it is because `nitro: false`.

**Comment by wattanx** [comment]
Fixed at https://github.com/nuxt/bridge/issues/998
