### ISSUE TITLE
Type definition for `defineComponent` in capi.legacy.ts is `any`

### ISSUE THREAD

**Issue by konkarin** [nuxt/bridge#992]
### Environment

- Operating System: Linux
- Node Version: v18.18.0
- Nuxt Version: 2.17.2
- CLI Version: 3.10.0
- Nitro Version: 2.7.2
- Package Manager: npm@9.4.2
- Builder: webpack
- User Config: bridge, typescript, nitro
- Runtime Modules: -
- Build Modules: @nuxt/bridge@3.0.0-rc.3

### Reproduction

https://stackblitz.com/edit/github-heoruj?file=defineComponent.ts

### Describe the bug

Even with `bridge.capi: true`, the aliases for the legacy `@nuxtjs/composition-api` are still defined in .nuxt/tsconfig.json.

The return value of `defineComponent` in there is `any`, so the types for Vue components are not inferred correctly.

### Additional context

https://github.com/nuxt/bridge/blob/3c40b3f363f7f3c8b72322a8d6e89f9bb5389bb5/packages/bridge/src/runtime/capi.legacy.ts#L220-L227

It looks like this could fix the issue. What do you think?

```ts
import {defineComponent as defineComponentVue } from "vue"

export const defineComponent: typeof defineComponentVue = (options) => {
  if (!('head' in options)) { return options }

  return {
    ...options,
    ...getHeadOptions(options)
  }
}
```

**Comment by wattanx** [comment]
I think the solution described in the description is a good one!

**Comment by wattanx** [comment]
Fixed at https://github.com/nuxt/bridge/pull/994
